### ISSUE TITLE
Ingress Nginx SSH access

### ISSUE THREAD

**Issue by jasperf** [kubernetes/minikube#10031]
**Steps to reproduce the issue:** 

1. try ssh laradock@192.168.64.21 // based on minikube ip
2. get asked for password
3. enter it 
4. fail access

```
ssh laradock@192.168.64.21         
The authenticity of host '192.168.64.21 (192.168.64.21)' can't be established.
ECDSA key fingerprint is SHA256:X7Kgv7DfGxht5eBAAeo9j7d+qTet+jpBPOh4Mv3Zlts.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.64.21' (ECDSA) to the list of known hosts.
laradock@192.168.64.21's password: 
```

Seems Ingress Nginx does work with port 80 and also that port 22 is open, but access fails and or port forwarding to pod with workspace container fails See question at https://discuss.kubernetes.io/t/ingress-nginx-ssh-access-and-forwarding-to-workspace-container-pod/14219 (no answers) as well.

**Full output of `minikube start` command used, if not already included:**

```
minikube start
😄  minikube v1.16.0 on Darwin 10.15.7
✨  Using the hyperkit driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing hyperkit VM for "minikube" ...
🐳  Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
🔎  Verifying Kubernetes components...
🔎  Verifying ingress addon...
🌟  Enabled addons: storage-provisioner, default-storageclass, ingress, dashboard
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

Ingress resource

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
  namespace: smt-local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    # host can be set in /etc/host or with laravel valet `valet link`
  - host: smart48k8.local
    http:
      paths:
        # https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types 
        # `/` is all paths using Prefix
      - pathType: Prefix
        path: /
        backend:
          service:
            # refers to our app service exposed to the cluster
            name: nginx 
            port:
              number: 80
```

Workspace Service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: workspace-service
  namespace: smt-local
spec:
  # type not chosen so ClusterIP
  # type: NodePort
  selector:
    app: workspace
  ports:
    - protocol: TCP
      port: 22
      # targetport is the internal port where traffic is sent to
      # By default and for convenience, the targetPort is set to the same value
      # as the port field.
      # targetPort: 22
      # minikube service --url workspace-service -n smt-local
      # nodePort: 30007
```

Workspace Deployment

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace
  labels:
    tier: backend
  namespace: smt-local
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: workspace
      tier: backend
  template:
    metadata:
      labels:
        app: workspace
        tier: backend
    spec:
      containers:
        - name: workspace
          image: smart48/smt-workspace:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 22
          volumeMounts:
            - name: code-storage
              mountPath: /code
      volumes:
        - name: code-storage
          persistentVolumeClaim:
            claimName: code-pv-claim
```

Any ideas how I can make this work so I can ssh in via port 22 and wind up in workspace container without issues?
