### ISSUE TITLE
PVCs restored from VolumeSnapshots always stay in Pending state

### ISSUE THREAD

**Issue by mcred** [kubernetes/minikube#10139]
In a deployed k8s cluster, the workflow of creating a PVC, creating a snapshot, restoring that snapshot into a new PVC using the csi-hostpath-driver works, but when the same files and workflows are executed locally with minikube, they fail. The basic steps are below and after step 5, the PVC always remains in the Pending state. 

```bash
$ kubectl get pvc     
NAME                 STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
mysql-init-restore   Pending                                                                        csi-hostpath-sc   20h
mysql-pv-claim       Bound     pvc-2a55ceaa-66ec-4ff9-9d0e-b7b6b35b82c8   1Gi        RWO            csi-hostpath-sc   20h
```

**Steps to reproduce the issue:** 

1. `minikube start`
2.  enable volumesnapshot and csi-hostpath-driver addons based on [these instructions](https://minikube.sigs.k8s.io/docs/tutorials/volume_snapshots_and_csi/)
3. create a pvc with the csi-hostpath-driver
4. create a volumesnapshot from pvc created in step 3
5. create a pvc with the volumesnapshot from step 4 as the dataSource

PVC always stays in pending state and the logs show this error:
```
I0113 18:33:29.447959       1 event.go:291] "Event occurred" object="default/mysql-init-restore" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="ExternalProvisioning" message="waiting for a volume to be created, either by external provisioner \"hostpath.csi.k8s.io\" or manually created by system administrator"
```

## Detailed Steps

```bash
$ minikube start
$ minikube addons enable volumesnapshots
$ minikube addons enable csi-hostpath-driver
$ kubectl create -f mysql-pvc.yaml 
$ kubectl create -f mysql-init-snapshot.yaml
$ kubectl create -f mysql-init-restore.yaml
```
### Kubernetes configuration files
```yaml
# mysql-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
```yaml
# mysql-init-snapshot.yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: mysql-init-snapshot
spec:
  volumeSnapshotClassName: csi-hostpath-snapclass
  source:
    persistentVolumeClaimName: mysql-pv-claim
```
```yaml
# mysql-init-restore.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-init-restore
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: mysql-init-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
### minikube start
```bash 
$ minikube start
😄  minikube v1.16.0 on Darwin 10.15.7
✨  Using the hyperkit driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing hyperkit VM for "minikube" ...
🐳  Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
🔎  Verifying Kubernetes components...
🔎  Verifying csi-hostpath-driver addon...
🌟  Enabled addons: default-storageclass, storage-provisioner, volumesnapshots, dashboard, csi-hostpath-driver
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

```
### Confirm addons enabled
```bash
$ minikube addons list
|-----------------------------|----------|--------------|
|         ADDON NAME          | PROFILE  |    STATUS    |
|-----------------------------|----------|--------------|
| ambassador                  | minikube | disabled     |
| csi-hostpath-driver         | minikube | enabled ✅   |
| dashboard                   | minikube | enabled ✅   |
| default-storageclass        | minikube | enabled ✅   |
| efk                         | minikube | disabled     |
| freshpod                    | minikube | disabled     |
| gcp-auth                    | minikube | disabled     |
| gvisor                      | minikube | disabled     |
| helm-tiller                 | minikube | disabled     |
| ingress                     | minikube | disabled     |
| ingress-dns                 | minikube | disabled     |
| istio                       | minikube | disabled     |
| istio-provisioner           | minikube | disabled     |
| kubevirt                    | minikube | disabled     |
| logviewer                   | minikube | disabled     |
| metallb                     | minikube | disabled     |
| metrics-server              | minikube | disabled     |
| nvidia-driver-installer     | minikube | disabled     |
| nvidia-gpu-device-plugin    | minikube | disabled     |
| olm                         | minikube | disabled     |
| pod-security-policy         | minikube | disabled     |
| registry                    | minikube | disabled     |
| registry-aliases            | minikube | disabled     |
| registry-creds              | minikube | disabled     |
| storage-provisioner         | minikube | enabled ✅   |
| storage-provisioner-gluster | minikube | disabled     |
| volumesnapshots             | minikube | enabled ✅   |
|-----------------------------|----------|--------------|

```
### kubectl version
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by govargo** [comment]
This is because you must register the VolumeSnapshotClass `csi-hostpath-snapclass` manually.
https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/#the-volumesnapshotclass-resource

`volume-snapshot-controller` in `kube-system` output the following logs.

```
snapshot_controller.go:1022] failed to retrieve snapshot class csi-hostpath-snapclass from the informer: "volumesnapshotclass.snapshot.storage.k8s.io \"csi-hostpath-snapclass\" not found"
```

You can use snapshot and restore with following steps.

```
1. minikube start
2. minikube addons enable volumesnapshots
3. minikube addons enable csi-hostpath-driver
4. kubectl create -f mysql-pvc.yaml 
5. kubectl create -f snapshotclass.yaml
6. kubectl create -f mysql-init-snapshot.yaml
7. kubectl create -f mysql-init-restore.yaml
```

```
# snapshotclass.yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: csi-hostpath-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: hostpath.csi.k8s.io
deletionPolicy: Delete
parameters:
```
