### ISSUE TITLE
minikube and multus CNI

### ISSUE THREAD

**Issue by slowfranklin** [kubernetes/minikube#10664]
I can't get multus CNI to work with minikube. I'm net to K8 and minikube so I'm probably missing something obvious.

I realize that this is not the appropriate place for this kind of support request, but it seems the Slack channel is not accepting new users and the user mailing list is dead. If there's any other place (IRC channel? Matrix?) to ask such questions let me know.

**Steps to reproduce the issue:** 

0. Start minikube:
```
minikube start
😄  minikube v1.17.1 on Fedora 33
✨  Using the podman (experimental) driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing podman container for "minikube" ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.2 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass

❗  /usr/bin/kubectl is version 1.18.2, which may have incompatibilites with Kubernetes 1.20.2.
    ▪ Want kubectl v1.20.2? Try 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```
1. Install multus CNI
`kubectl apply -f images/multus-daemonset.yml`
2. Deploy a NetworkAttachmentDefinition
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: samba-ad-dc-static-ip-conf-1
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "lan",
    "type": "bridge",
    "bridge": "br-lan",
    "ipam": {
      "type": "static",
      "addresses": [
        {"address": "192.168.3.2/24"}
      ]
    }
  }'
```
3. Deploy a stateful-set that references the network definition:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dc
spec:
  selector:
    matchLabels:
      app: samba-ad-dc
  serviceName: samba-ad-dc
  replicas: 1
  template:
    metadata:
      labels:
        app: samba-ad-dc
      annotations:
        k8s.v1.cni.cncf.io/networks: samba-ad-dc-static-ip-conf-1
...
```

The running container doesn't have an additional IP.

Is multus actually supposed to work with minikube? Thanks for any pointers!
