### ISSUE TITLE
Invalid Kube Config

### ISSUE THREAD

**Issue by lukepolo** [kubernetes/minikube#10690]
**Steps to reproduce the issue:** 

1. minikube delete --purge
2. minikube start -p profile

 minikube stats up properly, but the config file is not correct and crashes lens. 

`/.kube/config` then contains empty cluster / user

```
- context:
    cluster: ""
    user: ""
  name: minikube
- context:
    cluster: qx-dev
    extensions:
    - extension:
        last-update: Tue, 02 Mar 2021 12:13:29 EST
        provider: minikube.sigs.k8s.io
        version: v1.17.1
      name: context_info
    namespace: default
    user: qx-dev
  name: qx-dev
current-context: qx-dev
kind: Config

```

The version of minikube. : 
```
minikube version: v1.17.1
commit: 043bdca07e54ab6e4fc0457e3064048f34133d7e
```

The driver you are using. (docker, virtualbox, hyperv....)
`hyperkit`

The Operation system you are using (windows, mac or linux and version of it)
`osx 11.2.2 `

The full output of the command you are using by adding --alsologtostderr -v=8 for example
```ill have to rebuild the entire cluster may need to wait till after the work day (5pm est)```
