### ISSUE TITLE
error execution phase upload-config/kubelet

### ISSUE THREAD

**Issue by jhoncemplok** [kubernetes/minikube#10739]
saya ingin menginisialisasi dari file kubeadm-config.yaml
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: stable
apiServer:
  certSANs:
   - "192.168.100.127"
controlPlaneEndpoint: "192.168.100.127:6443"
#api:
#  advertiseAddress: 192.168.100.127
etcd:
  external:
    endpoints:
    - https://192.168.100.127:2379
    - https://192.168.100.128:2379
    - https://192.168.100.129:2379
    caFile: /etc/etcd/ssl/ca.pem
    certFile: /etc/etcd/ssl/etcd.pem
    keyFile: /etc/etcd//ssl/etcd-key.pem
networking:
  podSubnet: 172.17.0.1/16
```
pada saat saya melakukan perintah init terjadi keterangan eror "error execution phase upload-config/kubelet: Error writing Crisocket information for the control-plane node: timed out waiting for the condition
To see the stack trace of this error execute with --v=5 or higher"
