### ISSUE TITLE
Ingress on docker driver - minikube v1.18.1 - ERR_CONNECTION_REFUSED - Could not resolve host:

### ISSUE THREAD

**Issue by vagdevik** [kubernetes/minikube#10966]
I am using Minikube(v1.18.1) with Docker-Driver(docker engine 20.10.5) on my Windows 10 Home.

**Steps to reproduce the issue:** 

1. minikube start
2. minikube addons enable ingress
3. kubectl apply -f namespace.yaml
4. kubectl apply -f deploy.yaml -n minikube-example

The namespace.yaml looks like this:
```
apiVersion: v1
kind: Namespace
metadata:
  name: minikube-example
  labels:
    name: minikube-example
```

The deploy.yaml looks like this:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insights-app
  labels:
    app: insights-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insights-app
  template:
    metadata:
      labels:
        app: insights-app
    spec:
      containers:
      - name: insights-app
        image: yeasy/simple-web:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    name: hello-app
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: hello-app
---
apiVersion: v1
kind: Service
metadata:
  name: insights-app
  labels:
    name: insights-app
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: insights-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minikube-example-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: minikube-example.com
      http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: hello-app
                port:
                  number: 8080    
          - path: /insights
            pathType: Prefix
            backend:
              service:
                name: insights-app
                port:
                  number: 80
```

Then, 
```
kubectl get ingress - minikube-example
```
gives the following:
```
NAME                                       CLASS           HOSTS                      ADDRESS      PORTS       AGE
minikube-example-ingress   <none>   minikube-example.com   192.168.49.2     80           42m
```

I have also configured the `192.168.49.2  minikube-example.com` in the `/etc/hosts` file on my windows system.

Also, basedon some reading somewhere, I used `minikube tunnel` for ingress on Windows. But the command does not even ask me for password and it is not working.
