### ISSUE TITLE
Docker local private registry in minikube using the docker driver

### ISSUE THREAD

**Issue by unfor19** [kubernetes/minikube#11036]
## My Setup

Minikube on Windows WSL2 using [minikube's docker driver](https://minikube.sigs.k8s.io/docs/drivers/docker/).

I've deployed [nginx-ingress-controller](https://kubernetes.github.io/ingress-nginx/deploy/) which listens on ports 80 and 443. The application is available via both HTTP and HTTPS (using [cert-manager](https://cert-manager.io/docs/installation/kubernetes/) for TLS certificates). And of course, I added `127.0.0.1 docker-registry.kubemaster.me` to my `C:\Windows\System32\drivers\etc\hosts` file.

## Steps to reproduce the issue:

1. **WSL2**: Minikube start
    ```bash
    minikube start --driver=docker --kubernetes-version=v1.20.2
    ```
1. **WSL2**: Clone repo
    ```bash
    git clone git@github.com:unfor19/kubernetes-localdev.git
    cd kubernetes-localdev
    git checkout feature/docker-registry
    ```
1. **WSL2**: Helm install NGINX Ingress Controller
    ```bash
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && \
    helm repo update && \
    helm upgrade --install nginx ingress-nginx/ingress-nginx --set controller.kind=DaemonSet
    ```
1. **Windows**: Edit `C:\Windows\System32\drivers\etc\hosts` with Notepad or [Notepad++](https://notepad-plus-plus.org/downloads/v7.9.5/) as Administrator and add
    ```bash
    127.0.0.1 docker-registry.kubemaster.me
    ```
1. **WSL2**: Deploy registry (Deployment, Service and Ingress) - [5-docker-registry.yaml](https://github.com/unfor19/kubernetes-localdev/blob/feature/docker-registry/5-docker-registry.yaml)
    ```bash
    kubectl apply -f 5-docker-registry.yaml
    ```
1. **WSL2**: Open a new terminal and start a tunnel, keep it running the background
   ```bash
   minikube tunnel

   # Output
   ❗  The service nginx-ingress-nginx-controller requires privileged ports to be exposed: [80 443]
   🔑  sudo permission will be asked for it.
   🏃  Starting tunnel for service nginx-ingress-nginx-controller.
   ```
1. **WSL2**: Attempt to push image to `docker-registry`
    ```bash
    docker pull ubuntu
    docker tag ubuntu docker-registry.kubemaster.me/test-image
    docker push docker-registry.kubemaster.me/test-image
    
    # Output
    Using default tag: latest
    The push refers to repository [docker-registry.kubemaster.me/test-image]
    Get http://docker-registry.kubemaster.me/v2/: dial tcp 127.0.0.1:80: connect: connection refused
    ```

## More details

- The host's Docker daemon doesn't reach nginx-ingress-controller, I can see that in the logs, there's no traffic at all when using `docker push`, though there's traffic when using `curl`

<details>

<summary>Attempts to access the private registry - Expand/Collapse</summary>

## Accessing the local registry

- From the **Windows Host**

  [![access-from-windows-host][1]][1]

- From the **WSL2 Ubuntu** guest machine.

  ```bash
  curl  http://docker-registry.kubemaster.me/v2/_catalog
  ```

  [![access-from-ubuntu-guest][2]][2]

- From **minikube's docker container**
  ```bash
  docker exec -it minikube bash
  root@minikube:/$ curl  http://docker-registry.kubemaster.me/v2/_catalog
  ```

  [![access-from-minikube-container][3]][3]
  
- Pushing from **minikube's docker container**
  ```bash
  docker exec -it minikube bash

  # in minikube's container
  root@minikube:/#     docker pull ubuntu

  # Output
  r-registry.kubemaster.me/test-image
    docker push docker-registry.kubemaster.me/test-imageUsing default tag: latest
  latest: Pulling from library/ubuntu
  a70d879fa598: Pull complete 
  c4394a92d1f8: Pull complete 
  10e6159c56c0: Pull complete 
  Digest: sha256:3c9c713e0979e9bd6061ed52ac1e9e1f246c9495aa063619d9d695fb8039aa1f
  Status: Downloaded newer image for ubuntu:latest
  docker.io/library/ubuntu:latest
  
  root@minikube:/#     docker tag ubuntu docker-registry.kubemaster.me/test-image

  root@minikube:/#     docker push docker-registry.kubemaster.me/test-image           Using default tag: latest

  # Output
  The push refers to repository [docker-registry.kubemaster.me/test-image]
  346be19f13b0: Pushed 
  935f303ebf75: Pushed 
  0e64bafdc7ee: Pushed 
  latest: digest: sha256:5403064f94b617f7975a19ba4d1a1299fd584397f6ee4393d0e16744ed11aab1 size: 943
  ```

</details>

<details>

<summary>YAML - Deployment, Service and Ingress - Expand/Collapse</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: docker-registry
  name: docker-registry
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      k8s-app: docker-registry
  template:
    metadata:
      labels:
        k8s-app: docker-registry
    spec:
      # volumes:
      #   - name: mkcert-ca-certs
      #     secret:
      #       secretName: kubemaster-me-ca-tls-secret
      containers:
        - image: registry:2
          imagePullPolicy: Always
          name: docker-registry
          # volumeMounts:
          # - name: mkcert-ca-certs
          #   mountPath: "/certs"
          #   readOnly: true
          env:
            - name: REGISTRY_HTTP_SECRET
              value: "some-secret"
            - name: REGISTRY_HTTP_ADDR
              value: "0.0.0.0:80"
            # - name: REGISTRY_HTTP_TLS_CERTIFICATE
            #   value: "/certs/tls.crt"
            # - name: REGISTRY_HTTP_TLS_KEY
            #   value: "/certs/tls.key"
          ports:
            - containerPort: 80
              # hostPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 400Mi
              cpu: "200m"
            requests:
              memory: 200Mi
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: docker-registry
  name: docker-registry
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s-app: docker-registry
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: docker-registry
  namespace: kube-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
spec:
  # tls:
  #   - hosts:
  #       - docker-registry.kubemaster.me
  #     secretName: kubemaster-me-app-tls-secret
  ingressClassName: nginx
  rules:
    - host: docker-registry.kubemaster.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: docker-registry
              servicePort: 80
```

</details>

  [1]: https://i.stack.imgur.com/Pa4Fz.png
  [2]: https://i.stack.imgur.com/kfmQV.png
  [3]: https://i.stack.imgur.com/t8uM0.png

Source code: https://github.com/unfor19/kubernetes-localdev/tree/feature/docker-registry

Also posted on Stackoverflow - https://stackoverflow.com/questions/67020152/docker-local-private-registry-in-minikube-using-the-docker-driver
