### ISSUE TITLE
Ingress addon: `Error: server.go:84] "failed to process webhook request" err="rejecting admission review because the request does not contain an Ingress resource but networking.k8s.io/v1, Kind=Ingress with name`

### ISSUE THREAD

**Issue by sherbang** [kubernetes/minikube#11121]
**Steps to reproduce the issue:** 

Minikube v1.19.0 docker driver on PopOS 20.10

Using the ingress plugin, installing an ingress always fails.

Exact same steps and yaml works in v1.18.1

Doesn't matter if the ingress is defined with `apiVersion: networking.k8s.io/v1` or `apiVersion: extensions/v1beta1` (yaml files used to test each work in v1.18.1)

Suspect that ansible/awx-operator#205 is the same issue.

Failing ingress definition:
```
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.global-static-ip-name":"not-used","networking.gke.io/managed-certificates":"not-used"},"labels":{"app":"cwacc-webapp"},"name":"cwacc-webapp","namespace":"gozynta-dev"},"spec":{"rules":[{"host":"cwacc.minikube.local","http":{"paths":[{"backend":{"service":{"name":"cwacc-webapp","port":{"number":5000}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["cwacc.minikube.local"]}]}}
      kubernetes.io/ingress.global-static-ip-name: not-used
      networking.gke.io/managed-certificates: not-used
    labels:
      app: cwacc-webapp
    name: cwacc-webapp
    namespace: gozynta-dev
  spec:
    rules:
    - host: cwacc.minikube.local
      http:
        paths:
        - backend:
            service:
              name: cwacc-webapp
              port:
                number: 5000
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - cwacc.minikube.local
kind: List
metadata: {}
```

**Full output of failed command:** 

kubectl error: `Error from server (InternalError): error when creating "gozynta-dev/profiles/cwacc": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": an error on the server ("") has prevented the request from succeeding`

Error in ingress-controller: `E0417 00:03:30.320457       7 server.go:84] "failed to process webhook request" err="rejecting admission review because the request does not contain an Ingress resource but networking.k8s.io/v1, Kind=Ingress with name cwacc-webapp in namespace gozynta-dev"`

**Full output of `minikube start` command used, if not already included:**
```
😄  [cwacc] minikube v1.19.0 on Debian bullseye/sid
✨  Automatically selected the docker driver. Other choices: kvm2, ssh, none
❗  Your cgroup does not allow setting memory.
    ▪ More information: https://docs.docker.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities
👍  Starting control plane node cwacc in cluster cwacc
🔥  Creating docker container (CPUs=3, Memory=4096MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.5 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "cwacc" cluster and "default" namespace by default
✅  minikube profile was successfully set to cwacc
Switched to context "cwacc".
minikube ssh --profile cwacc sudo sysctl fs.inotify.max_user_watches=1048576
fs.inotify.max_user_watches = 1048576
minikube addons enable ingress --profile cwacc
    ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
    ▪ Using image k8s.gcr.io/ingress-nginx/controller:v0.44.0
    ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
🔎  Verifying ingress addon...
🌟  The 'ingress' addon is enabled
```

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by btalbot** [comment]
Same exact failure on macos 11.2.3 as well

**Comment by robrich** [comment]
https://github.com/kubernetes/ingress-nginx/issues/5401 looks like a similar stream, and references errors in the last few days using Minikube.

I worked around it by disabling the Minikube ingress addon and using the ingress-nginx helm chart from Artifact Hub.  Minikube 1.19 currently uses ingress-nginx 0.44.0 and Helm's latest is 0.45.0.  Maybe it was a bug in ingress-nginx 0.44.0?

**Comment by balnbibarbi** [comment]
Confirm, disabling the Minikube ingress addon and using the ingress-nginx helm chart from Artifact Hub fixes this.
For both the Ingress and LoadBalancer to get an IP address, I have to `minikube tunnel`.
But avoiding this was my motivation for trying ingress-nginx, so this isn't ideal.

**Comment by btalbot** [comment]
Deleting the ValidatingWebhookConfiguration/ingress-nginx-admission also allows the minikube ingress controller to function but without that safety net of course. Reasonable work-around until the bug is fixed though.

**Comment by medyagh** [comment]
thank you everyone for reporting this bug, this seems to be side effect of this PR https://github.com/kubernetes/minikube/pull/10879 that we tried to update the ingress to new version, unfortunately our integration test did not catch this problem,
Please stay tuned, we will create a fix for this and hopefully by adding an integration test this should never happen again.

Thank you for your patience

**Comment by medyagh** [comment]
CC: @govargo

**Comment by govargo** [comment]
Sorry for this unablement to use ingress addon. I investigated why this happens.

> CC: @govargo could this be related to upstream bug kubernetes/ingress-nginx#5401 ?

Yes. This is the issue of the admission webhook.
Currently, upstream ingress-nginx admission controller doesn't allow Ingress of `networking.k8s.io/v1`.
The closest issue is https://github.com/kubernetes/ingress-nginx/issues/7066

I confirmed the admission controller of ingress-nginx and found out it doesn't support v1 version.
It only supports `networking.k8s.io/v1beta` version.
https://github.com/kubernetes/ingress-nginx/blob/controller-v0.44.0/internal/admission/controller/main.go#L46-L52

As a result of further investigation, It used to support `networking.k8s.io/v1` in ingress-nginx v0.40.0 by https://github.com/kubernetes/ingress-nginx/pull/6187 in the past.
However, it was removed in v0.41.0 by https://github.com/kubernetes/ingress-nginx/pull/6366.
(I don't know why this was changed, because the reason wasn't written in the PR description.)

**Comment by govargo** [comment]
And I also confirmed the ingress can route with these yaml files.

```
# pod and service
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: ClusterIP
```

**This worked because the version is v1beta1**
```
# ingress v1beta1
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    integration-test: ingress
spec:
  rules:
  - host: nginx.example.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: nginx
          servicePort: 80
```

**This doesn't work because the version is v1. [the admission controller](https://github.com/kubernetes/ingress-nginx/blob/master/internal/admission/controller/main.go) always rejects**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    integration-test: ingress
spec:
  rules:
  - host: nginx.example.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
```

**Error with v1 version**
```
"failed to process webhook request" err="rejecting admission review because the request does not contain an Ingress resource but networking.k8s.io/v1, Kind=Ingress with name nginx-ingress in namespace default"
```
