### ISSUE TITLE
Add some format to the ListImages, such as templates or JSON

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#11165]
Follow-up to #10933

Currently ListImages API returns the images in a fixed text format...

```go
        // ListImages returns a list of images managed by this container runtime
        ListImages(ListImagesOptions) ([]string, error)
```

minikube image ls
```
k8s.gcr.io/pause:3.2
k8s.gcr.io/kube-scheduler:v1.20.2
k8s.gcr.io/kube-proxy:v1.20.2
k8s.gcr.io/kube-controller-manager:v1.20.2
k8s.gcr.io/kube-apiserver:v1.20.2
k8s.gcr.io/etcd:3.4.13-0
k8s.gcr.io/coredns:1.7.0
gcr.io/k8s-minikube/storage-provisioner:v5
docker.io/library/busybox:latest
docker.io/kubernetesui/metrics-scraper:v1.0.4
docker.io/kubernetesui/dashboard:v2.1.0
```

NOTE: That "busybox" image came from the cache:

```json
{
    "cache": {
        "busybox": null
    }
}
```

As suggested, it could be useful with _other_ formats: https://github.com/kubernetes/minikube/pull/11007#pullrequestreview-629443503

---

`crictl` offers three different formats:

### table (default)

minikube ssh -- sudo crictl images --output table k8s.gcr.io/pause
```text
IMAGE               TAG                 IMAGE ID            SIZE
k8s.gcr.io/pause    3.2                 80d28bedfe5de       683kB
```

### json
```json
minikube ssh -- sudo crictl images --output json k8s.gcr.io/pause
{
  "images": [
    {
      "id": "sha256:80d28bedfe5dec59da9ebf8e6260224ac9008ab5c11dbbe16ee3ba3e4439ac2c",
      "repoTags": [
        "k8s.gcr.io/pause:3.2"
      ],
      "repoDigests": [
        "k8s.gcr.io/pause@sha256:927d98197ec1141a368550822d18fa1c60bdae27b78b0c004f705f548c07814f"
      ],
      "size": "682696",
      "uid": null,
      "username": ""
    }
  ]
}
```

### yaml

minikube ssh -- sudo crictl images --output yaml k8s.gcr.io/pause
```yaml
images:
- id: sha256:80d28bedfe5dec59da9ebf8e6260224ac9008ab5c11dbbe16ee3ba3e4439ac2c
  repoDigests:
  - k8s.gcr.io/pause@sha256:927d98197ec1141a368550822d18fa1c60bdae27b78b0c004f705f548c07814f
  repoTags:
  - k8s.gcr.io/pause:3.2
  size: "682696"
  uid: null
  username: ""

```
