### ISSUE TITLE
get ETCD version from kubernetes constants

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11290]
currently in https://github.com/medyagh/minikube/blob/a67a4ccbedd932f184b5713c70498dc434942621/pkg/minikube/bootstrapper/images/images.go#L86
we have 
```
// etcd returns the image used for etcd
func etcd(v semver.Version, mirror string) string {
	// Should match `DefaultEtcdVersion` in:
	// https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go
	ev := "3.4.13-0"

	switch v.Minor {
	case 17, 18:
		ev = "3.4.3-0"
	case 16:
		ev = "3.3.15-0"
	case 14, 15:
		ev = "3.3.10"
	case 12, 13:
		ev = "3.2.24"
	case 11:
		ev = "3.2.18"
	}

	// An awkward special case for v1.19.0 - do not imitate unless necessary
	if v.Equals(semver.MustParse("1.19.0")) {
		ev = "3.4.9-1"
	}

	return path.Join(kubernetesRepo(mirror), "etcd:"+ev)
}

```

instead we should use this map in kuberentes so we dont have to update this manually

https://github.com/kubernetes/kubernetes/blob/b58a7e233e06f5e4b58a637af8e36cb4f59c001b/cmd/kubeadm/app/constants/constants.go#L452
```

	// SupportedEtcdVersion lists officially supported etcd versions with corresponding Kubernetes releases
	SupportedEtcdVersion = map[uint8]string{
		13: "3.2.24",
		14: "3.3.10",
		15: "3.3.10",
		16: "3.3.17-0",
		17: "3.4.3-0",
		18: "3.4.3-0",
		19: "3.4.13-0",
		20: "3.4.13-0",
		21: "3.4.13-0",
		22: "3.4.13-0",
		23: "3.4.13-0",
	}

```

**Comment by afbjorklund** [comment]
It's not really in kubernetes but in `kubeadm`, and we can access these through `config images list`

```console
$ ~/.minikube/cache/linux/v1.21.0/kubeadm config images list
k8s.gcr.io/kube-apiserver:v1.20.0
k8s.gcr.io/kube-controller-manager:v1.20.0
k8s.gcr.io/kube-scheduler:v1.20.0
k8s.gcr.io/kube-proxy:v1.20.0
k8s.gcr.io/pause:3.4.1
k8s.gcr.io/etcd:3.4.13-0
k8s.gcr.io/coredns/coredns:v1.8.0
```

**Comment by afbjorklund** [comment]
@medyagh : better fix all of them, if you fix one ?

```go
// Pause returns the image name to pull for a given Kubernetes version
func Pause(v semver.Version, mirror string) string

// coreDNS returns the images used for CoreDNS
func coreDNS(v semver.Version, mirror string) string

// etcd returns the image used for etcd
func etcd(v semver.Version, mirror string) string

```

**Comment by medyagh** [comment]
Agree. Anyone picking up this task fix all verisons. To get vers through kubeadm

**Comment by Srikrishnabh** [comment]
@medyagh I would like to fix this.

**Comment by Srikrishnabh** [comment]
@vigothehacker If you dont mind can I work on this had already started, missed the assign command ?

**Comment by Srikrishnabh** [comment]
> @medyagh : better fix all of them, if you fix one ?
> 
> ```go
> // Pause returns the image name to pull for a given Kubernetes version
> func Pause(v semver.Version, mirror string) string
> 
> // coreDNS returns the images used for CoreDNS
> func coreDNS(v semver.Version, mirror string) string
> 
> // etcd returns the image used for etcd
> func etcd(v semver.Version, mirror string) string
> ```
> 
> The original code is in cmd/kubeadm/app/images/images.go
> 
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/images/images.go
> (https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go)
> 
> I think the problem was with accessing the earlier releases ?

yes to get the older release versions.

**Comment by afbjorklund** [comment]
I think the reason was that we wanted to know the versions _before_ we downloaded kubeadm...

And that not all platforms were able to execute `kubeadm`, without wrapping it in docker or similar ?

One solution would be to make some kind of mapping table. That is, in markup instead of in code ?

```yaml
---
v1.21.0:
    k8s.gcr.io/kube-apiserver: v1.21.0
    k8s.gcr.io/kube-controller-manager: v1.21.0
    k8s.gcr.io/kube-scheduler: v1.21.0
    k8s.gcr.io/kube-proxy: v1.21.0
    k8s.gcr.io/pause: 3.4.1
    k8s.gcr.io/etcd: 3.4.13-0
    k8s.gcr.io/coredns/coredns: v1.8.0
v1.20.0:
    k8s.gcr.io/kube-apiserver: v1.20.0
    k8s.gcr.io/kube-controller-manager: v1.20.0
    k8s.gcr.io/kube-scheduler: v1.20.0
    k8s.gcr.io/kube-proxy: v1.20.0
    k8s.gcr.io/pause: 3.2
    k8s.gcr.io/etcd: 3.4.13-0
    k8s.gcr.io/coredns: 1.7.0
v1.19.0:
    k8s.gcr.io/kube-apiserver: v1.19.0
    k8s.gcr.io/kube-controller-manager: v1.19.0
    k8s.gcr.io/kube-scheduler: v1.19.0
    k8s.gcr.io/kube-proxy: v1.19.0
    k8s.gcr.io/pause: 3.2
    k8s.gcr.io/etcd: 3.4.9-1
    k8s.gcr.io/coredns: 1.7.0
```

**Comment by Srikrishnabh** [comment]
> I think the reason was that we wanted to know the versions _before_ we downloaded kubeadm...
> 
> And that not all platforms were able to execute `kubeadm`, without wrapping it in docker or similar ?
> 
> One solution would be to make some kind of mapping table. That is, in markup instead of in code ?
> 
> ```yaml
> ---
> v1.21.0:
>     k8s.gcr.io/kube-apiserver: v1.21.0
>     k8s.gcr.io/kube-controller-manager: v1.21.0
>     k8s.gcr.io/kube-scheduler: v1.21.0
>     k8s.gcr.io/kube-proxy: v1.21.0
>     k8s.gcr.io/pause: 3.4.1
>     k8s.gcr.io/etcd: 3.4.13-0
>     k8s.gcr.io/coredns/coredns: v1.8.0
> v1.20.0:
>     k8s.gcr.io/kube-apiserver: v1.20.0
>     k8s.gcr.io/kube-controller-manager: v1.20.0
>     k8s.gcr.io/kube-scheduler: v1.20.0
>     k8s.gcr.io/kube-proxy: v1.20.0
>     k8s.gcr.io/pause: 3.2
>     k8s.gcr.io/etcd: 3.4.13-0
>     k8s.gcr.io/coredns: 1.7.0
> v1.19.0:
>     k8s.gcr.io/kube-apiserver: v1.19.0
>     k8s.gcr.io/kube-controller-manager: v1.19.0
>     k8s.gcr.io/kube-scheduler: v1.19.0
>     k8s.gcr.io/kube-proxy: v1.19.0
>     k8s.gcr.io/pause: 3.2
>     k8s.gcr.io/etcd: 3.4.9-1
>     k8s.gcr.io/coredns: 1.7.0
> ```
> 
> Note that you also have to supply --kubernetes-version, or it will auto-update (within each release).

@afbjorklund I'm able to collect the image versions thanks for the inputs.

where do we want to stores this image to k8s version map, did you mean this will be some yaml and we use in code to load?

**Comment by afbjorklund** [comment]
I'm not sure if the best is to embed some kind of resource, or convert the lookup back into code again.

The original input is like:

```console
$ ./kubeadm-linux-amd64-1.13.0 --kubernetes-version=v1.13.0 config images list
k8s.gcr.io/kube-apiserver:v1.13.0
k8s.gcr.io/kube-controller-manager:v1.13.0
k8s.gcr.io/kube-scheduler:v1.13.0
k8s.gcr.io/kube-proxy:v1.13.0
k8s.gcr.io/pause:3.1
k8s.gcr.io/etcd:3.2.24
k8s.gcr.io/coredns:1.2.6
```

I converted it to some yaml markup like:
```yaml
v1.13.0:
    k8s.gcr.io/kube-apiserver: v1.13.0
    k8s.gcr.io/kube-controller-manager: v1.13.0
    k8s.gcr.io/kube-scheduler: v1.13.0
    k8s.gcr.io/kube-proxy: v1.13.0
    k8s.gcr.io/pause: 3.1
    k8s.gcr.io/etcd: 3.2.24
    k8s.gcr.io/coredns: 1.2.6
```

It would also be possible to use go code:
```go
	images := make(map[string]map[string]string)
	images["v1.13.0"] = map[string]string{
		"k8s.gcr.io/kube-apiserver":          "v1.13.0",
		"k8s.gcr.io/kube-controller-manager": "v1.13.0",
		"k8s.gcr.io/kube-scheduler":          "v1.13.0",
		"k8s.gcr.io/kube-proxy":              "v1.13.0",
		"k8s.gcr.io/pause":                   "3.1",
		"k8s.gcr.io/etcd":                    "3.2.24",
		"k8s.gcr.io/coredns":                 "1.2.6",
	}
```

Maybe @medyagh has some more thoughts, on what would be the best way to store these constants ?
