### ISSUE TITLE
Create a test that verifies that DNS is working

### ISSUE THREAD

**Issue by luxas** [kubernetes/minikube#114]
This can be accomplished by starting a pod like this:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
```

and then by executing `kubectl exec -it busybox /bin/sh -c "nslookup kubernetes"`. It should output:
```console
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      kubernetes
Address 1: 10.0.0.1
```
so if one is able to `grep 10.0.0.1` and `10.0.0.10`, it's working.
This could be an integration test
