### ISSUE TITLE
Test Flake: "TestFunctional/parallel/LogsCmd"

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11442]
as seen here

https://github.com/kubernetes/minikube/pull/11431/checks?check_run_id=2606299017

**Comment by dinever** [comment]
Haven't managed to reproduce this issue but the error seems to be `crictl logs` failing to get logs for `kube-proxy` and `kube-scheduler`

```
failed to try resolving symlinks in path \"/var/log/pods/kube-system_coredns-74ff55c5b-vq4zk_c786e2a0-38e3-48ed-b5ec-c78677f0c404/coredns/1.log\": lstat /var/log/pods/kube-system_coredns-74ff55c5b-vq4zk_c786e2a0-38e3-48ed-b5ec-c78677f0c404/coredns/1.log: no such file or directory
```

**Comment by dinever** [comment]
Was able to accidentally reproduce this issue in my local env today, after repeating the functional tests many times.

The issue seems to be some containers exits before they start (this seems to be random, not sure why), so `containerd` has to recreate the containers, leaving the old containers in the `CREATED` state. Since the old containers were not even started, there are no logs.

![Group 1](https://user-images.githubusercontent.com/1311594/119292529-95036300-bc1e-11eb-8ab1-6687630598ad.png)

From the pod:
```yaml
  containerStatuses:
  - containerID: containerd://106945daaacbf4f1ac9a81dfdcf486d3ec40050fe18bbabd95e9fc6e9676bf0e
    image: k8s.gcr.io/kube-scheduler:v1.20.2
    imageID: k8s.gcr.io/kube-scheduler@sha256:304b3d70497bd62498f19f82f9ef164d38948e5ae94966690abfe9d1858867e2
    lastState:
      terminated:
        containerID: containerd://0426cf266f7717905cc413fc4d8996394ef31e59b46bf2d8926fca87e50aba57
        exitCode: 0
        finishedAt: null
        startedAt: null
    name: kube-scheduler
    ready: true
    restartCount: 3
    started: true
    state:
      running:
        startedAt: "2021-05-24T02:42:05Z"
```

As `crictl logs` returns an error when there is no log for a container, `minikube logs` returns error status as well which failed the test.

`containerd` logs didn't give much info on why it recreates the containers.

[containerd.log](https://github.com/kubernetes/minikube/files/6529731/containerd.log)

[logcmd.log](https://github.com/kubernetes/minikube/files/6529733/logcmd.log)

To resolve the flakiness, I think one option might be simply don't return exit code 1 when failed to retrieve logs from some containers, and only prints out a warning.

Another option is that we get the logs of containers that are only in state `RUNNING` or `EXITED`:

https://github.com/kubernetes/cri-api/blob/1a76359308d012205ec79297f166a47a49d93ddb/pkg/apis/runtime/v1alpha2/api.proto#L889-L894

```protobuf
enum ContainerState {
    CONTAINER_CREATED = 0;
    CONTAINER_RUNNING = 1;
    CONTAINER_EXITED  = 2;
    CONTAINER_UNKNOWN = 3;
}
```

Thanks!
