### ISSUE TITLE
Follow the Using Multi-Node Clusters is not able to access the worker node.

### ISSUE THREAD

**Issue by charleech** [kubernetes/minikube#11669]
* `minikube version `
```
minikube version: v1.21.0
commit: 76d74191d82c47883dc7e1319ef7cebd3e00ee11
```

* `minikube start --nodes 2 --docker-opt bip=172.18.0.1/16`
```
* minikube v1.21.0 on Centos 7.7.1908
  - MINIKUBE_HOME=/opt/minikube.home
* Automatically selected the docker driver
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* Downloading Kubernetes v1.20.7 preload ...
    > preloaded-images-k8s-v11-v1...: 492.20 MiB / 492.20 MiB  100.00% 29.16 Mi
    > gcr.io/k8s-minikube/kicbase...: 359.09 MiB / 359.09 MiB  100.00% 10.08 Mi
* Creating docker container (CPUs=2, Memory=4000MB) ...
* Preparing Kubernetes v1.20.7 on Docker 20.10.7 ...
  - opt bip=172.18.0.1/16
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Configuring CNI (Container Networking Interface) ...
* Verifying Kubernetes components...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v5
* Enabled addons: storage-provisioner, default-storageclass

* Starting node minikube-m02 in cluster minikube
* Pulling base image ...
* Creating docker container (CPUs=2, Memory=4000MB) ...
* Found network options:
  - NO_PROXY=192.168.49.2
* Preparing Kubernetes v1.20.7 on Docker 20.10.7 ...
  - opt bip=172.18.0.1/16
  - env NO_PROXY=192.168.49.2
* Verifying Kubernetes components...
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

I follow the example from https://minikube.sigs.k8s.io/docs/tutorials/multi_node/ by creating the `hello-svc.yaml` and `hello-deployment.yaml` as the following: -

```yaml
#
# hello-svc.yaml
#
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 80
      targetPort: http
```

```yaml
#
# hello-deployment.yaml
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions: [{ key: app, operator: In, values: [hello] }]
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: hello-from
        image: pbitty/hello-from:latest
        ports:
          - name: http
            containerPort: 80
      terminationGracePeriodSeconds: 1
```

**Steps to reproduce the issue:** 

1. `minikube delete --all --purge`
2.  `minikube start --nodes 2 --docker-opt bip=172.18.0.1/16`
3. `kubectl get nodes`
```
NAME           STATUS   ROLES                  AGE    VERSION
minikube       Ready    control-plane,master   113s   v1.20.7
minikube-m02   Ready    <none>                 72s    v1.20.7
```
4.  `minikube status`
```
minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured

minikube-m02
type: Worker
host: Running
kubelet: Running
```
5. `kubectl apply -f hello-deployment.yaml`
```
deployment.apps/hello created
```
6. `kubectl rollout status deployment/hello`
```
Waiting for deployment "hello" rollout to finish: 0 of 2 updated replicas are available...
Waiting for deployment "hello" rollout to finish: 1 of 2 updated replicas are available...
deployment "hello" successfully rolled out
```
7. `kubectl apply -f hello-svc.yaml`
```
service/hello created
```
8. `kubectl get pods -o wide`
```
NAME                     READY   STATUS    RESTARTS   AGE   IP           NODE           NOMINATED NODE   READINESS GATES
hello-695c67cf9c-64b5z   1/1     Running   0          34s   10.244.1.2   minikube-m02   <none>           <none>
hello-695c67cf9c-q7dfx   1/1     Running   0          34s   10.244.0.3   minikube       <none>           <none>
```
9. `minikube service list`
```
|-------------|------------|--------------|---------------------------|
|  NAMESPACE  |    NAME    | TARGET PORT  |            URL            |
|-------------|------------|--------------|---------------------------|
| default     | hello      |           80 | http://192.168.49.2:31000 |
| default     | kubernetes | No node port |
| kube-system | kube-dns   | No node port |
|-------------|------------|--------------|---------------------------|
```
10. 
```
for i in `seq 1 10`; do curl http://192.168.49.2:31000; echo; done
```
```
Hello from hello-695c67cf9c-q7dfx (10.244.0.3) # <---- Only able to connect to node = `minikube`
Hello from hello-695c67cf9c-q7dfx (10.244.0.3)
curl: (28) Failed to connect to 192.168.49.2 port 31000: Connection timed out # <---- Is not able to connect to node = `minikube-m02`

Hello from hello-695c67cf9c-q7dfx (10.244.0.3)
Hello from hello-695c67cf9c-q7dfx (10.244.0.3)
curl: (28) Failed to connect to 192.168.49.2 port 31000: Connection timed out # <---- Is not able to connect to node = `minikube-m02`

curl: (28) Failed to connect to 192.168.49.2 port 31000: Connection timed out # <---- Is not able to connect to node = `minikube-m02`

Hello from hello-695c67cf9c-q7dfx (10.244.0.3)
Hello from hello-695c67cf9c-q7dfx (10.244.0.3)
Hello from hello-695c67cf9c-q7dfx (10.244.0.3)
```

**Full output of `minikube logs` command:**
N/A

**Full output of failed command:**
N/A
