### ISSUE TITLE
Add cifs support for Azure File volumes

### ISSUE THREAD

**Issue by jmalobicky** [kubernetes/minikube#1197]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

Add cifs support for utilizing Azure Files storage volumes. Currently when trying to utilize 

```
apiVersion: v1
kind: Pod
metadata:
 name: azure
spec:
 containers:
  - image: kubernetes/pause
    name: azure
    volumeMounts:
      - name: azure
        mountPath: /mnt/azure
 volumes:
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: k8stest
          readOnly: false
```

reference https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/azure_file

The output of `kubectl describe pods` ends with `Output: mount: unknown filesystem type 'cifs'`

**Minikube version** (use `minikube version`): minikube version: v0.16.0

**What you expected to happen**: The volume would have been successfully created in Azure
