### ISSUE TITLE
Add configuration for buildkit, in order to not have to use flags

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#12264]
We can pass the setup as configuration, rather than flags.

That makes it easier to start from systemd units, and so on.

We want to use the containerd worker, by default.

`-oci-worker false --containerd-worker true `

And store the result in the "k8s.io" namespace.

`--containerd-worker-namespace k8s.io`

Helps with #9947

**Comment by afbjorklund** [comment]
`/etc/buildkit/buildkitd.toml`

https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md

```toml
[worker.oci]
  enabled = false
[worker.containerd]
  enabled = true
  namespace = "k8s.io"
```
