### ISSUE TITLE
minikube tunnel doesn't appear to support UDP LoadBalancers

### ISSUE THREAD

**Issue by ChristopherMillon** [kubernetes/minikube#12362]
**Steps to reproduce the issue:** 

1. minikube start --vm-driver=docker --memory 8192 --cpus 6
2. kubectl apply -f
```
kind: Service
apiVersion: v1
metadata:
  name: udp
spec:
  ports:
    - name: nginx-udp
      protocol: UDP
      port: 11500
      targetPort: 11500
  type: LoadBalancer
```
3. minikube tunnel
```
❯ minikube tunnel
🏃  Starting tunnel for service nginx-udp.
```
4. sudo lsof -i -P -n | grep 11500
```
ssh       14238           user    5u  IPv6 0xe5c1af091405c8ef      0t0    TCP [::1]:11500 (LISTEN)
ssh       14238           user    6u  IPv4 0xe5c1af092c227f77      0t0    TCP 127.0.0.1:11500 (LISTEN)
```

As observed here, the opened tunnel is TCP and not UDP which means I'm unable to route UDP traffic to my nginx load balancer.
