### ISSUE TITLE
Ingress addon missing an IngressClass resource

### ISSUE THREAD

**Issue by jeyjeyemem** [kubernetes/minikube#12455]
**Steps to reproduce the issue:** 

1. minikube start
2. minikube addons enable ingress

`ingress-nginx-controller` is not able to process `Ingress` resources marked with `ingressClassName: nginx` due to lack of an `IngressClass` resource in the addon manifest:
https://github.com/kubernetes/minikube/blob/master/deploy/addons/ingress/ingress-deploy.yaml.tmpl

**Comment by xavidram** [comment]
I downgraded the minikube version and the addon was enabled successfully so this is an issue with the latest build for minikube.

**Comment by mans0954** [comment]
My workaround for this is to manually create the IngressClass resource (using the config info from [ingres-nginx](https://kubernetes.github.io/ingress-nginx/):
```
# ingressclass.yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: nginx
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx
```
I apply this as follows:
```
kubectl apply -f ingressclass.yaml
```
```
kubectl get IngressClass
NAME    CONTROLLER             PARAMETERS   AGE
nginx   k8s.io/ingress-nginx   <none>       16m
```
My ingress then get class `nginx` associated with them (but no IP address?):
```
kubectl get ingress
NAME          CLASS   HOSTS                  ADDRESS   PORTS   AGE
web-ingress   nginx   www.example.com             80      15m
```
Looking in the ingress controller logs I see:
```
kubectl --namespace ingress-nginx logs ingress-nginx-controller-************-*****
...
I0914 11:09:28.560506       8 main.go:101] "successfully validated configuration, accepting" ingress="web-ingress/default"
I0914 11:09:28.565437       8 store.go:365] "Found valid IngressClass" ingress="default/web-ingress" ingressclass="nginx"
...
```
Curling the host works as expected, so I'm happy.
```
curl --resolve www.example.com:80:$(minikube ip) http://www.example.com/
```
