### ISSUE TITLE
Alpine Image cannot use DNS on Mac OSX

### ISSUE THREAD

**Issue by dmlond** [kubernetes/minikube#12567]
**Steps to reproduce the issue:** 

1. minikube start --driver=virtualbox --addons=ingress-dns,ingress
2. Create a web namespace with dnsutils, and alpine pods
```
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: web
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: web
spec:
  containers:
  - name: httpd
    image: alpine 
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
EOF
```

3. wget google.com in both
```
kubectl exec -n web dnsutils -- wget -O- google.com
kubectl exec -n web web-server -- wget -O- google.com
```

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>
output of dnsutils
Connecting to google.com (142.250.177.14:80)
Connecting to www.google.com (172.217.13.4:80)
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description"><meta content="noodp" name="robots">
..... rest of google.com source truncated
</html>

output from web-server
wget: bad address 'google.com'

</details>

OS: Mac OSX Big Sur 11.6
ISO Version: minikube-v1.23.1.iso
