### ISSUE TITLE
[Question] How to use ImagePolicyWebhook with minikube?

### ISSUE THREAD

**Issue by jason-riddle** [kubernetes/minikube#1264]
I have the following setup.

image-review.yml

```yml
# clusters refers to the remote service.
clusters:
- name: image-review-server
  cluster:
    server: https://mockbin.com/bin/7bd2c6ed-b62c-4405-ba53-15eb0981b8e8

# users refers to the API server's webhook configuration.
users:
- name: kube-apiserver
  user:
    token: blue-token

current-context: webhook

contexts:
  - context:
      cluster: image-review-server
      user: kube-apiserver
    name: webhook
```

admission_controller.json

```json
{
  "imagePolicy": {
     "kubeConfigFile": "/Users/me/Projects/Minikube/image_review.yml",
     "allowTTL": 50,
     "denyTTL": 50,
     "retryBackoff": 500,
     "defaultAllow": true
  }
}
```

I use the following command to start up minikube

```bash
minikube start \
  --extra-config=apiserver.GenericServerRunOptions.AdmissionControl=ImagePolicyWebhook \
  --extra-config=apiserver.GenericServerRunOptions.AdmissionControlConfigFile=/Users/me/Projects/Minikube/admission_controller.json
```
When I start minikube, there is an exception and the following stack trace is shown: https://gist.github.com/jason-riddle/245ab74e1bbbf94a6b0bee96bfa48d29

The last line indicates.

```
Mar 20 04:33:44 minikube systemd[1]: localkube.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

but I'm not sure what the invalid argument is in this case?

### Minikube Version

```
minikube version: v0.17.1
```
