### ISSUE TITLE
Logs not showing for init containers using kubectl logs

### ISSUE THREAD

**Issue by F21** [kubernetes/minikube#1278]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): 0.17.1

**Environment**:
- **OS** (e.g. from /etc/os-release): Windows 10 64-bit (latest updates)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): VirtualBox 5.1.18
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v1.0.7
- **Install tools**: No installation. Copied binary to folder and added the folder to my PATH.
- **Others**: I am using cmder mini v1.3.2 as my shell: https://github.com/cmderdev/cmder/releases/tag/v1.3.2

**What happened**:
I created a deployment with an init-container. I made sure that the init-container would fail so that it would emit a message.

The init container did fail and the deployment failed. However, if I try to look at the logs, I see nothing:
```
$ kubectl logs sample-app-2667625384-2vp0w -c install
```
If I ssh into the machine, find the container and run `docker logs 2776ba83f133`, I do see the output:

```
time="2017-03-23T05:02:59Z" level=fatal msg="Failed to create vault auth token because we timed out after 30s before receiving the secret_id. Exiting."
```

**What you expected to happen**:
`kubectl logs` should show logs for init containers when requested.

**How to reproduce it** (as minimally and precisely as possible):
1. Deploy the following:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
      annotations:
        pod.boostport.com/vault-approle: sample-app
        pod.boostport.com/vault-init-container: install
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "install",
            "image": "boostport/kubernetes-vault-init:0.3.0",
            "imagePullPolicy": "Always",
            "env": [
                {
                    "name": "VAULT_ROLE_ID",
                    "value": "c0275bd0-0fda-8bd6-8e2c-9bc4190a68c7"
                },
                {
                    "name": "TIMEOUT",
                    "value": "30s"
                }
            ],
            "volumeMounts": [
                {
                    "name": "vault-token",
                    "mountPath": "/var/run/secrets/boostport.com"
                }
            ]
          }
        ]'
    spec:
      containers:
      - name: sample-app
        image: boostport/kubernetes-vault-sample-app:0.3.0
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
      volumes:
      - name: vault-token
        emptyDir: {}
```

2. The init container will fail.

3. Check the logs: `kubectl logs sample-app-2667625384-mp4bn -c install`. It should show nothing.

4. SSH into the machine, find the container and run `docker logs container_id` and it should show output.

**Anything else do we need to know**:

N/A
