### ISSUE TITLE
DNS in Minikube does not resolve pod hostname in a StatefulSet

### ISSUE THREAD

**Issue by akomakom** [kubernetes/minikube#12788]
Containers in pods in minikube can resolve external names but not themselves or other containers.  
The name is in `/etc/hosts` file, but not in DNS.

**Steps to reproduce the issue:** 

* OS: Ubuntu 20.04
* VirtualBox: 6.1.26-dfsg-3~ubuntu1.20.04.2
* minikube: 1.23.2-0 (.deb)
* kubectl: 1.22.2

1. minikube config set driver virtualbox 
2. minikube start
2. kubectl apply -f test.yaml # below
3. kubectl exec -ti pod/akom1-0 -- /bin/sh # and check DNS:
```shell
/ # hostname
akom1-0

# nslookup  akom1-0
Server:         10.96.0.10
Address:        10.96.0.10#53

** server can't find akom1-0: NXDOMAIN

/ # hostname -f
akom1-0.akom1.default.svc.cluster.local
/ # nslookup  akom1-0.akom1.default.svc.cluster.local
Server:         10.96.0.10
Address:        10.96.0.10#53

** server can't find akom1-0.akom1.default.svc.cluster.local: NXDOMAIN

/ # cat /etc/resolv.conf 
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local 
options ndots:5
/ # nslookup kubernetes.com
Server:         10.96.0.10
Address:        10.96.0.10#53

Non-authoritative answer:
Name:   kubernetes.com
Address: 52.217.138.221
** server can't find kubernetes.com: NXDOMAIN
```

## Deployment file (test.yaml)

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: akom1
  name: akom1
spec:
  selector:
    matchLabels:
      app: akom1
  serviceName: akom1
  # replica set definition
  replicas: 1
  template:
    metadata:
      labels:
        app: akom1
    spec:
      # pod definition
      containers:
      - name: akom1
        image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
        imagePullPolicy: Always #ensure the node will always try to pull from the registry
        resources:
          requests:
            memory: 2Gi
        command:
        - sleep
        - "3600"
```

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**
[logs.txt](https://github.com/kubernetes/minikube/files/7421367/logs.txt)

**Full output of failed command if not `minikube start`:**
<details>

```
/ # nslookup $(hostname -f)
Server:         10.96.0.10
Address:        10.96.0.10#53

** server can't find akom1-0.akom1.default.svc.cluster.local: NXDOMAIN
```

## DNS logs:

```
$ kubectl logs --namespace=kube-system -l k8s-app=kube-dns
[INFO] 172.17.0.1:58291 - 56111 "A IN akom1-0.akom1.default.svc.cluster.local. udp 57 false 512" NXDOMAIN qr,aa,rd 150 0.000197577s
```

</details>
