### ISSUE TITLE
Cannot bind a socket in pod on mount folder in privileged container

### ISSUE THREAD

**Issue by huguesBouvier** [kubernetes/minikube#12789]
Hello,

I have a pod that listening on a socket. I am trying to mount the folder where that socket is located on my host so can do debugging from my host environment.

I have a very simple debugging setup:
1. Start with minikube start
2. Mounted the folder: minikube mount --uid root --gid root --mode="0777" /home/azureuser/socket:/home/azureuser/socket
3. The module deployment file::
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registrymanager
  labels:
    app: registrymanager
spec:
  selector:
    matchLabels:
      app: registrymanager
  template:
    metadata:
      labels:
        app: registrymanager
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: registrymanager
          image: ubuntu
          securityContext:
            privileged: true
          command: ["sleep"]
          args: ["1000000000"]
          volumeMounts:
            - name: spire-server-socket
              mountPath: /tmp/spire-server/private/
      volumes:
        - name: spire-server-socket
          hostPath:
            path: /home/azureuser/socket
```
I have set it to privileged so it can mount sockets.
Then I log inside the container:
kubectl exec -it registrymanager-6d65f6c5f7-t5lgj -n spire -- /bin/bash
And do:
python -c "import socket as s; sock = s.socket(s.AF_UNIX); sock.bind('/tmp/spire-server/private/test.sock')"

But I get: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 1] Operation not permitted.

The container is privileged but it seems like the privileged status doesn't work.
