### ISSUE TITLE
Curl inside a pod: curl: (60) SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by rahulanand16nov** [kubernetes/minikube#12924]
Hello maintainers,

I was trying to learn Kubernetes and got stuck on an issue for hours that prevents making an HTTPS request from any container to outside.

Things I did:
Create minkube/kind cluster:
```bash
minikube start
```

Installed Istio components

```bash
istioctl install
```

Tried to execute curl request from istiod component and I get:
```
istio-proxy@istiod-67764fc6c9-5cj57:/$ curl -v https://raw.githubusercontent.com/istio/tools/release-1.11/bin/root-transition.sh
*   Trying 95.216.67.149:443...
* TCP_NODELAY set
* Connected to raw.githubusercontent.com (95.216.67.149) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
I can curl fine from the outside.

**Comment by medyagh** [comment]
@rahulanand16nov

```
istio-proxy@istiod-67764fc6c9-5cj57:
```

1- does not seem like u are inside minikube, are u using `minikube ssh` to get inside?
2- are you using a VPN ?

3- can you please attach this file

```
minikube logs --out=log.txt

```

**Comment by rahulanand16nov** [comment]
@medyagh 1. I can curl fine when using `minikube ssh` but not when inside any container.

I applied the follow resource:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toystore
  labels:
    app: toystore
spec:
  selector:
    matchLabels:
      app: toystore
  template:
    metadata:
      labels:
        app: toystore
    spec:
      containers:
        - name: toystore
          image: quay.io/3scale/authorino:echo-api
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
              name: http
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: toystore
spec:
  selector:
    app: toystore
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
```
used bash: `kubectl exec deployment/toystore -it -- /bin/bash` to make curl cmd as above and fails due to cert issue.

The fact that I can do the curl inside a similar container on another machine makes it look like a kubernetes/minikube problem.

2. No, I am not using VPN.

3. [logs.txt](https://github.com/kubernetes/minikube/files/7518012/logs.txt)
