### ISSUE TITLE
Running minikube under multipass

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#12946]
Our friends at Canonical have made a "workflow" for running minikube with [multipass](https://multipass.run/)...

It will create an Ubuntu VM for you, install Docker Engine and then run `minikube` on it:

```
$ multipass launch minikube
Launched: minikube

$ multipass exec minikube -- minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured
```

See https://github.com/canonical/multipass-workflows/blob/main/v1/minikube.yaml

(it is using the deb installation from https://docs.docker.com/engine/install/ubuntu/)

```shell
adduser ubuntu docker
...
sudo -u ubuntu minikube start --driver=docker
```

**Comment by afbjorklund** [comment]
This script would probably have been easier to do, if minikube hadn't been removed from the Ubuntu app store:

* Issue https://github.com/kubernetes/minikube/issues/7977

Before:
```yaml
        snap:
          commands:
          - snap install minikube
```

After:
```yaml
        packages:
        - dpkg-dev

        runcmd:
        - wget https://storage.googleapis.com/minikube/releases/latest/minikube_latest_$( dpkg-architecture -q DEB_HOST_ARCH ).deb
        - apt-get install --yes --no-install-recommends -o Debug::pkgProblemResolver=yes ./minikube_latest_$( dpkg-architecture -q DEB_HOST_ARCH ).deb
```
