### ISSUE TITLE
Minikube start with profile name should create cluster with a "minikube-" prefix

### ISSUE THREAD

**Issue by nicksieger** [kubernetes/minikube#13008]
In order for development tools to distinguish between local/development clusters from production clusters, K8s distributions that create local clusters have been using a `{distro}-` prefix as part of the cluster context name (e.g.,  `kind-`). It would be great if Minikube could adopt this convention as well!

**Steps to reproduce the issue:** 

1. `minikube start -p mykube`
2. `kubectl config view -o jsonpath='{range .contexts[*]}{.name}{"\n"}{end}'` would then show `minikube-mykube`

#### Background

https://github.com/kubernetes-sigs/kind/releases/tag/v0.6.0
https://github.com/kubernetes-sigs/kind/pull/1029
https://github.com/tilt-dev/tilt/issues/5206

**Comment by medyagh** [comment]
Hi @nicksieger we have added metadata to kubeconfig
That labels who created a cluster. We would love to make that a standard for all local kubernetes development.

**Comment by nicksieger** [comment]
We could look at the metadata too, I think that would solve the problem. I also like the metadata approach, what can we do to shop that around to Kind, K3d and others? Start with related issues there?

**Comment by medyagh** [comment]
I think metadata is best way to verify, since a minikube cluster can be called easily anything by the user.
```
minikube start -p gke
minikube start -p k3d
```

here is how kubeconfig shows for minikube and docker desktop
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1URXhOekU1TXpReE5sb1hEVE14TVRFeE5URTVNelF4Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2JLCmk0NThFdTNmOG8rL1JCZEdWNDlKT05Xejh0V29NejVlZm9qc0k5Vjl6S1VqT0FPV25PQUVuME05bVdqZzBSZXUKemdPNjZ2VXZQeDN6S3VBczdCQm8zVUlwQ1RPdTBjSFpqNHQxRUFFblMzUkM2YVJtNG44WENIR0NsZVI1bXcwNAoydFZFd2wvREtwN0RUWWRKVVFNTHJycG1ZOC8yMjZFT3NEdFYvc1p1VnV6NUNQTHNtdkFRdGw5UlJMVVg4OXp5ClR4UmVqVWhGUzh1cFd5ckNzbGQ5T1gzTk8xWkxUR0I1b2MrczJ6T0o2dngwc3BGZVlNM3J2VExicXozWi9RR0oKMS9UQWladWRXeDl5c3VhSlAyRFYxZ2d6WUR1T3k4cllHeno4YmorbnpoMHpoRTUyT25VNXYwaTYxM2tIYWw1TQppZnF2OTZHRlYzNjJ3azU1UHQ4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQMnBPTElxdUZ2UFFFdUxJYytPZ3FnN0dTRUtNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBN0hCZm5FQ1FJL1ZjbkgveDVkWEdyRVRkN09nNndZNzN5WWVINnRsNmJUenIzd0hPNQoyZ3kxZm84L1IyTDIrZEFEUE5YNHpCcEFXSHJWVXRnZXlieUlidU5leW1nMmtvUXNYdUpkREgzeWpNWmhUMStUCnN6d3dlYy81b3ZqTS8wTjBBaGF4UjkyaEQ1bWRYZGNMZmJ3RkhsLy84OUNvdnArMDhTUmMydC9JM29FK0VZc0YKYXBiNC81OXF5SVdhVHdoenVYbll4ZWdTcTZZMGtGTTVXZDh6SHAwdkErVmg2VjlRd1lCcFJhK2JMcG91RDZodgp6TWhDcktGam9VZk0ybU05MEJKeTRrNDJxOFRtVTZ4ampaWWNyWVRpRXVsQVZYOTNYNk4xUUVhSGpPbjFmRUc0CktTZnZ0cURzVGZEYkJMY2ZLSXpBUVVsa3VMbDNIRWtsQ3liTgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    certificate-authority: /Users/medya/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 23 Nov 2021 11:00:47 PST
        provider: minikube.sigs.k8s.io
        version: v1.23.2
      name: cluster_info
    server: https://127.0.0.1:57438
  name: minikube
contexts:
```

for minikube there is an extension metadata shows what version of minikube created the context

```
    - extension:
        last-update: Tue, 23 Nov 2021 11:00:47 PST
        provider: minikube.sigs.k8s.io
        version: v1.23.2
```

I suggest we add this as a standard for all local kubernetes tools. it would worth a industry-wide collaboration.
