### ISSUE TITLE
Minikube 1.24.0 update unable to get ingress address

### ISSUE THREAD

**Issue by bocian67** [kubernetes/minikube#13068]
Had a setup to create some services inside minikube cluster, retrieve the address of the ingress and assign a local hostname to that ip (for example minikube.local on 192.168.64.10). Since updating from minikube 1.23.x to 1.24.0 this is not working anymore, since address is always localhost, not an IP anymore. 

Using kubernetes version 1.22.2

**Steps to reproduce the issue:** 

1. minikube start --driver=hyperkit -p minikube --kubernetes-version=v1.22.2
2. minikube addons enable ingress
3. kubectl create namespace test
4. install any helm chart to be deployed on the cluster
5. kubectl get ingress --all-namespaces
```
NAMESPACE            NAME               CLASS   HOSTS            ADDRESS     PORTS     AGE
test   example-ingress   nginx   minikube.local   localhost   80, 443   81s
```

Here is a part of the values.yaml of the helm chart we are deploying:
```
ingress:
  example:
    namespace: platform-namespace
    # If `true`, an Ingress is created
    enabled: true
  
    # The Service port targeted by the Ingress
    servicePort: http
    # Ingress annotations
    annotations: { 
      nginx.ingress.kubernetes.io/ssl-redirect: "false",
      cert-manager.io/issuer: "selfsigned-issuer"
    }
    # Additional Ingress labels
    labels: {}
    # List of rules for the Ingress
    rules:
      - host: minikube.local
        # Paths for the host
        paths:
          - /auth
    # TLS configuration
    tls:
      - hosts:
          - minikube.local
        secretName: example-tls
```

With the template of ingress:
```
{{- range $name, $ingress := .Values.ingress -}}
{{- if $ingress.enabled }}
---
apiVersion: {{ include "keycloak.ingressAPIVersion" $ }}
kind: Ingress
metadata:
  name: {{ include "keycloak.fullname" $ }}-{{$name}}
  {{- with $ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "keycloak.labels" $ | nindent 4 }}
    {{- range $key, $value := $ingress.labels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
spec:
{{- if $ingress.tls }}
  ingressClassName: nginx
  tls:
    {{- range $ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ tpl . $ | quote }}
      {{- end }}
      {{- with .secretName }}
      secretName: {{ tpl . $ }}
      {{- end }}
    {{- end }}
{{- end }}
  rules:
    {{- range $ingress.rules }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "keycloak.fullname" $ }}-http
                port:
                  name: {{ $ingress.servicePort }}
            {{- else }}
            backend:
              serviceName: {{ include "keycloak.fullname" $ }}-http
              servicePort: {{ $ingress.servicePort }}
            {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end -}}
```

Ingress controller log when executing the helm chart and setting up the ingress:
```
I1202 09:12:30.358634       8 event.go:282] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"test", Name:"example-ingress", UID:"45627022-ce5d-4945-a37d-c8b22dd738e8", APIVersion:"networking.k8s.io/v1", ResourceVersion:"739", FieldPath:""}): type: 'Normal' reason: 'Sync' Scheduled for sync
```

Since it worked on the version before, I assume this is a minikube problem. My first though was that there was a breaking change, but could not find any suitable changes in the CHANGELOG.md.
