### ISSUE TITLE
Setup minikube as CI step in github actions

### ISSUE THREAD

**Issue by drdkadtr** [kubernetes/minikube#13192]
I have tried GH action by using example flow but it fails: https://github.com/drdkadtr/gh-action-minikube-app/runs/4567460563?check_suite_focus=true

Any help troubleshooting would be greatly appreciated!

**Comment by mprimeaux** [comment]
FWIW, we use a [different Github action](https://github.com/manusa/actions-setup-minikube) for Minikube in our CI pipeline than what you're using and it works well. Here is a snippet:

```yaml
# See https://github.com/manusa/actions-setup-minikube
- name: Setup Minikube
  uses: manusa/actions-setup-minikube@v2.4.2
  with:
     minikube version: 'v1.24.0'
     driver: docker
     kubernetes version: ${{ matrix.k8s }}
     start args: "--addons registry "
     github token: ${{ secrets.GITHUB_TOKEN }}
```

Our strategy matrix is:

```yaml
jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The following strategy matrix is for Minikube
        # https://kubernetes.io/releases/
        k8s: ["1.21.7", "1.22.4"]
```
