### ISSUE TITLE
deployment error --kubernetes

### ISSUE THREAD

**Issue by ahmedas1980** [kubernetes/minikube#13453]
### What Happened?

kubectl apply -f mongo-deployment.yaml
error: error validating "mongo-deployment.yaml": error validating data: [ValidationError(Deployment.spec.template.spec): unknown field "limits" in io.k8s.api.core.v1.PodSpec, ValidationError(Deployment.spec.template.spec): unknown field "requests" in io.k8s.api.core.v1.PodSpec]; if you choose to ignore these errors, turn validation off with --validate=false

Im having trouble deployment this mongo db with secret 
i can deploy it with out the secret "env"   but not with the secret 

i was able to creat the secret first  but not the deployment ****

### Attach the log file

**mongo-deployment.yaml**

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: mongo-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mongo-secret
              key: mongo-root-password
------------------------------------------------------------------------------------
**mongo-secret.yaml**

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username:  dXNlcm5hbWU=
  mongo-root-password:  cGFzc3dvcmQ=

### Operating System

Other

**Comment by klaases** [comment]
Hi @[ahmedas1980](https://github.com/ahmedas1980), is this an error with minikube?

**Comment by klaases** [comment]
Hi @ahmedas1980  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by babuvarunkrishna** [comment]
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
```
