### ISSUE TITLE
Getting "panic: runtime error" when using minikube service in 1.25.2

### ISSUE THREAD

**Issue by purejgleason** [kubernetes/minikube#13736]
### What Happened?

I create a new minikube cluster

    minikube start --memory=8192 --cpus=4 -n 2

I create a namespace and deploytment/service...

    kubectl create ns foo
    kubectl apply -f test-app/app.yml
    
  

```
app.yml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: foo
  name: test-app
---
apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: foo
  labels:
    app: test-app
    service: test-app
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: test-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
      version: v1
  template:
    metadata:
      labels:
        app: test-app
        version: v1
    spec:
      serviceAccountName: test-app
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: Always
        name: test-app
        ports:
        - containerPort: 80

```

Next I start up as a service...

    minikube service test-app -n foo --url
    
in `1.25.1` everything runs fine when I try from `1.25.2` I get...

```
minikube service test-app -n foo --url    
😿  service foo/test-app has no node port
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
k8s.io/minikube/cmd/minikube/cmd.glob..func35(0x70d4760?, {0xc000ec42c0?, 0x1, 0x4})
	/Users/.../Code/lib/minikube/cmd/minikube/cmd/service.go:138 +0x645
github.com/spf13/cobra.(*Command).execute(0x70d4760, {0xc000ec4280, 0x4, 0x4})
	/Users/.../go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x70d4260)
	/Users/.../go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8164510/log.txt)

### Operating System

macOS (Default)

### Driver

Docker
