### ISSUE TITLE
Kubelet not running readiness probe on termating pods

### ISSUE THREAD

**Issue by rajeshkodali** [kubernetes/minikube#13786]
### What Happened?

Here is the Dockerfile
```
FROM nginx
RUN cat /dev/null > /test_file
COPY readiness.sh .
```
Here is readiness.sh
```bash
#!/bin/sh

cat ./test_file && curl localhost > /dev/null
```
And minikube start --driver=virtualbox --kubernetes-version=v1.23.3

Here is the deployment file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-test
  name: nginx-test
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx-test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      terminationGracePeriodSeconds: 150
      containers:
      - image: nginx-test:2022030602
        name: nginx-test
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
            - name: Custom-Header
              value: live
          failureThreshold: 1
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh 
            - -c 
            - /readiness.sh
          failureThreshold: 1
          periodSeconds: 5
          successThreshold: 3
        lifecycle:
          preStop:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "rm -f /test_file && sleep 20 && /usr/sbin/nginx -s stop"
        resources: 
          limits:
            cpu: "60m"
            memory: "200Mi"
          requests:
            cpu: "10m"
            memory: "100Mi"
```

This config works fine all terminating will go 0/1 before getting deleted in Docker desktop but on minikube only 1 or 2 pods go to 0/1 and then terminate after 20-30 seconds. I have checked the binary on the VM and the binary looks to be same as in github.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8251969/log.txt)

### Operating System

Ubuntu

### Driver

VirtualBox
