### ISSUE TITLE
minikube addons enable registry-creds does not prompt

### ISSUE THREAD

**Issue by AlecTroemel** [kubernetes/minikube#1391]
BUG REPORT

minikube version: v0.18.0
OS: macOS Sierra 10.12.4
VM Driver: virtualbox
ISO: minikube-v0.18.0.iso

**What happened**:
After upgrading from minikube 0.17 -> 0.18, enabling the registry-creds addon does not prompt me for anything
```
❯ minikube addons enable registry-creds                          
registry-creds was successfully enabled
```

**What you expected to happen**:
prompts for private registry information.

**How to reproduce it**
from clean minikube install (no `~/.minikube/`)
```
minikube start
minikube addons enable registry-creds
```

**Anything else do we need to know**:
No registry-creds pod is created until `minikube stop` and `minikube start` are run. Then the pod is stuck in `ContainerCreating` status. Doing a describe shows that it is expecting a k8 secret which is never created.
```yaml
Name:           registry-creds-0srv3
Namespace:      kube-system
Node:           minikube/192.168.99.100
Start Time:     Thu, 20 Apr 2017 14:11:38 -0500
Labels:         kubernetes.io/cluster-service=true
                name=registry-creds
                version=v1.7
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"kube-system","name":"registry-creds","uid":"2e20a556-25fd-11e7-95c1-08...
Status:         Pending
IP:
Controllers:    ReplicationController/registry-creds
Containers:
  registry-creds:
    Container ID:
    Image:              upmcenterprises/registry-creds:1.7
    Image ID:
    Port:
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Environment:
      AWS_ACCESS_KEY_ID:                <set to the key 'AWS_ACCESS_KEY_ID' in secret 'registry-creds-ecr'>                     Optional: false
      AWS_SECRET_ACCESS_KEY:            <set to the key 'AWS_SECRET_ACCESS_KEY' in secret 'registry-creds-ecr'>                 Optional: false
      awsaccount:                       <set to the key 'aws-account' in secret 'registry-creds-ecr'>                           Optional: false
      awsregion:                        <set to the key 'aws-region' in secret 'registry-creds-ecr'>                            Optional: false
      DOCKER_PRIVATE_REGISTRY_PASSWORD: <set to the key 'DOCKER_PRIVATE_REGISTRY_PASSWORD' in secret 'registry-creds-dpr'>      Optional: false
      DOCKER_PRIVATE_REGISTRY_SERVER:   <set to the key 'DOCKER_PRIVATE_REGISTRY_SERVER' in secret 'registry-creds-dpr'>        Optional: false
      DOCKER_PRIVATE_REGISTRY_USER:     <set to the key 'DOCKER_PRIVATE_REGISTRY_USER' in secret 'registry-creds-dpr'>          Optional: false
    Mounts:
      /root/.config/gcloud from gcr-creds (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hs8v9 (ro)
Conditions:
  Type          Status
  Initialized   True 
  Ready         False 
  PodScheduled  True 
Volumes:
  gcr-creds:
    Type:       Secret (a volume populated by a Secret)
    SecretName: registry-creds-gcr
    Optional:   false
  default-token-hs8v9:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-hs8v9
    Optional:   false
QoS Class:      BestEffort
Node-Selectors: <none>
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  11m           11m             1       default-scheduler                       Normal          Scheduled       Successfully assigned registry-creds-0srv3 to minikube
  9m            2m              4       kubelet, minikube                       Warning         FailedMount     Unable to mount volumes for pod "registry-creds-0srv3_kube-system(2e2167c0-25fd-11e7-95c1-080027866608)": timeout expired waiting for volumes to attach/mount for pod "kube-system"/"registry-creds-0srv3". list of unattached/unmounted volumes=[gcr-creds]
  9m            2m              4       kubelet, minikube                       Warning         FailedSync      Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "kube-system"/"registry-creds-0srv3". list of unattached/unmounted volumes=[gcr-creds]
  11m           57s             13      kubelet, minikube                       Warning         FailedMount     MountVolume.SetUp failed for volume "kubernetes.io/secret/2e2167c0-25fd-11e7-95c1-080027866608-gcr-creds" (spec.Name: "gcr-creds") pod "2e2167c0-25fd-11e7-95c1-080027866608" (UID: "2e2167c0-25fd-11e7-95c1-080027866608") with: secrets "registry-creds-gcr" not found
```
