### ISSUE TITLE
Minikube IP is not externally accessible via Ingress/ Nodeport Servce

### ISSUE THREAD

**Issue by airza** [kubernetes/minikube#13951]
### What Happened?

I am running Minikube on my shiny new M1 and have successfully created a container and service, both of which are accessible from inside of my cluster as expected (loosely following the tutorial).  Where I run into trouble is trying to expose the service to the host machine via an `ingress` controller. I enabled the `ingress` addon to minikube and have configured my service in a fairly straightforward way:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: door-control
  labels:
    app: door-control
spec:
  selector:
    matchLabels:
      app: door-control
  template:
    metadata:
      labels:
        app: door-control
    spec:
      containers:
      - image: docker.io/arzsystems/door_controls
        name: door-control
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7777
          name: http
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: door-control
spec:
  selector:
    app: door-control
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7777
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: door-control
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: partytime.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: door-control
                port:
                  number: 80
```
The container doesn't do anything special except service up HTTP on 7777, and both it and the service are exposed via Busybox. I can see the IP address from `minikube kubectl get ingress`:
```
door-control   nginx   partytime.test   192.168.49.2   80      16m
```
My understanding is that I should be able to access this by doing the following:

- Activating the `ingress-dns` addon for minikube
- Adding the IP for minikube (192.168.49.2) to my DNS list
- Activating `minikube tunnel` 
- Accessing partytime.test in the browser
Sadly this doesn't seem to work. I can't access anything on `192.168.49.2`. If I run `minikube tunnel` and add `partytime.test` to `/etc/hosts` I am able to access the IP, but I don't seem to be having success with getting the DNS addon to work at all. :(

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8475115/log.txt)

### Operating System

macOS (Default)

### Driver

Docker
