### ISSUE TITLE
Is it possible to mount a volume with container existing data

### ISSUE THREAD

**Issue by brahama** [kubernetes/minikube#14004]
### What Happened?

I need to mount a volume so that it does not get overwritten by the host empty dir, but instead it gets the container data and then of course persisted in the host.

```
      volumeMounts:
        - mountPath: /home/user/data
          name: node-vol
      volumes:
      - name: node-vol
        hostPath:
          path: /minikube-host/user/vol-node-1
          type: DirectoryOrCreate
```

The container already has a bunch of files and subdirs in /home/user/data that are generated at startup. When i use the mount above, that directory gets stepped on with the empty directory in the host.

In docker compose i avoided this by creating the volume and then attaching it in compose and the container would fill the host dir with the container data.

Is this possible with K8s and minikube?

Thanks!

### Attach the log file

nolog file

### Operating System

macOS (Default)

### Driver

HyperKit
