### ISSUE TITLE
Can't access a service from a singleton pod behind that service

### ISSUE THREAD

**Issue by mapadofu** [kubernetes/minikube#14063]
### What Happened?

If you create a service that is backed by a single pod, you cannot access that service from that pod.

Here's the config:

```

apiVersion: v1
kind: Service
metadata:
    name: skeleton-api
spec:
    type: ClusterIP
    ports:
        - name: skeleton
          port: 8008
          targetPort: 8008
    selector:
        app: skeleton
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: skeleton
spec:
    replicas: 1
    selector:
        matchLabels:
            app: skeleton
    template:
        metadata:
            labels:
                app: skeleton
        spec:
            containers:
                - name: skeleton
                  image: python:3.8
                  command: ["python"]
                  args: ["-m", "http.server", "8008"]
                  ports:
                      - containerPort: 8008
                        protocol: TCP
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 8008 
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: alternate
spec:
    replicas: 1
    selector:
        matchLabels:
            app: alternate
    template:
        metadata:
            labels:
                app: alternate
        spec:
            containers:
                - name: alternate
                  image: python:3.8
                  command: ["python"]
                  args: ["-m", "http.server", "8008"]
                  ports:
                      - containerPort: 8008
                        protocol: TCP
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 8008 
```
Then

`kubectl apply -f config.yml` creates the above objects.

`kubectl exec skeletion-xxx -- curl skeleton-api:8008` 
just hangs.

`kubectl exec alternate-xxx -- curl skeleton-api:8008` works fine.

Expected behaviour is that the behaviour of the service is the same from any pod in the cluster, including those that "back" the service.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8575203/logs.txt)

### Operating System

Ubuntu

### Driver

Docker
