### ISSUE TITLE
[Question]My app works properly on docker compose but not on minikube

### ISSUE THREAD

**Issue by hiroaki2020** [kubernetes/minikube#14326]
### What Happened?

My laravel app does not work properly on minikube while it does on docker compose.
**My question** is **"does this happen because of poor resource allocation or this could be caused by something else?"**

**Symptom**
There are 2 types of errors and I get either of them every time I refresh.
The errors are the following.
1. The web page is not shown and browser says 500 server error.
2. The web page is shown without background img (picture) and favicon. Browser says 404 not found but I confirmed they are in a related container. In addition, my js code does not work as it is written (Again, it does on docker compose).
I suspect resource allocated is not enough to run my app properly.
I use 2 nodes with default node resource setting.
My app consists of 3 pods and the resource allocation is following.

A. app pod
It contains 1 container and resource allocation is like
```
resources:
          limits:
            memory: 256Mi
            cpu: 300m
          requests:
            memory: 128Mi
            cpu: 100m
```
B. web pod
It contains 1 container and resource allocation is like
```
resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 50m
```
C. db pod
It contains 2 init containers with default resource setting and 2 containers with resource allocation like
```
resources:
          limits:
            memory: 512Mi
            cpu: 300m
          requests:
            memory: 64Mi
            cpu: 50m
```
I try to minimize resource allocation which might cause this problem.
Or any other cause you can think of? Please share your thoughts.

### Attach the log file

I will provide it if necessary.

### Operating System

macOS (Default)

### Driver

Docker
