### ISSUE TITLE
Cannot reach the external-ip using minikube tunnel

### ISSUE THREAD

**Issue by MrDesjardins** [kubernetes/minikube#14525]
### What Happened?

Hello,
I'm using a load-balancer service and trying to reach it from my Chrome browser. I am using a Windows 11 machine.

```
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: realtimepixel-prod
  labels:
    app: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: webapplication
  ports:
    - nodePort: 30062
      port: 3501
      targetPort: 3501
```
(Full yaml file in this [repository](https://github.com/MrDesjardins/realtimepixel/blob/kubernetes/kubernetes/production.yaml))

I am also running the tunnel: `minikube tunnel`

Performing the ` kubectl get service frontend-service`, I can see that an external-ip is assigned (only if the tunnel is running).

```
NAME               TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
frontend-service   LoadBalancer   10.98.130.100   127.0.0.1     3501:30062/TCP   28h`
```
However, going on Chrome and using `http://127.0.0.1:3501` produces a `ERR_CONNECTION_RESET` error.

I added the ingress addon (`minikube addons enable ingress`) without more success.

Is there something I am configuring wrongly?

 

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9068821/log.txt)

### Operating System

Windows
