### ISSUE TITLE
ExternalName type Service in minikube/virtualbox?

### ISSUE THREAD

**Issue by tony-kerz** [kubernetes/minikube#1508]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): maybe a bug?

**Minikube version**: 0.18.0
**Environment**:
- **OS**: `osx 10.11.6`
- **VM Driver**: `virtualbox`
- **ISO version**: `minikube-v0.18.0.iso`
- **Install tools**: `brew cask install`

**What happened**:
1. i submitted this yaml via `kubectl`:
```
kind: Service
apiVersion: v1
metadata:
  name: my-db
spec:
  type: ExternalName
  externalName: my-db.me.com
```
1. added `my-db.me.com` to `/etc/hosts` on my macbook setting to ip-addr returned by `ipconfig getifaddr en0`
1. referred to `my-db` from a `Deployment` of a pod requiring a connection to `my-db` like so:
```
        env:
          - name: DB_URL
            value: mysql://user1:s3cret@my-db/db1
```
**What you expected to happen**:
the pod requiring the connection `my-db` to connect successfully, but saw:
```
getaddrinfo ENOTFOUND my-db my-db:3306
```
