### ISSUE TITLE
Using Multi-Node Clusters Referenced Files Incorrect Formatting

### ISSUE THREAD

**Issue by niallminer** [kubernetes/minikube#15362]
The YAML files used as references in this tutorial are incorrectly formatted, thus making the tutorial hard/confusing to follow. It seems they are being parsed/loaded incorrectly and do not retain their proper indentation or comments, it looks like it was translated to Markdown or something similar.

Current File in Tutorial:
![image](https://user-images.githubusercontent.com/114624749/202011448-75c26ee2-8a1b-4477-bec4-edbeba4ef06f.png)

Expected File:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      affinity:
        #This ensures pods will land on separate hosts
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions: [{ key: app, operator: In, values: [hello] }]
              topologyKey: “kubernetes.io/hostname”
      containers:
        - name: hello-from
          image: pbitty/hello-from:latest
          ports:
            - containerPort: 80
              name: http
              terminationGracePeriodSeconds: 1


```
