### ISSUE TITLE
Feature Request: add service entry to ingress add-on

### ISSUE THREAD

**Issue by bryanlarsen** [kubernetes/minikube#1538]
FEATURE REQUEST

Problem:  We need an https path that routes successfully both outside and inside kubernetes.   For our production clusters, we just use the CNAME of the ingress load balancer.

For dev, we can't use https://$(minikube ip)/ because:

- do to annoying legacy reasons we can't just pass this address in as a config variable, it needs to be built into the docker container
- the ingress controller validates the CN on the certificate, so we need to put it into the cert

Our solution was to add an nginx ingress service entry, and then add `ingress.kube-system` to /etc/hosts on our dev machines.

Here's the service we added:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress-controller
```

That appears to work fine for us, but I opened this PR because it seems that this is something that should exist in the default install.  Nobody may quite have our use case, but I'm sure there are others.

minikube: v.0.19.0
OS: Ubuntu 16.04.2 LTS
VM Driver: kvm
ISO version: v0.18.0
