### ISSUE TITLE
Unable to npm install certain modules in mounted directories

### ISSUE THREAD

**Issue by cmaher** [kubernetes/minikube#1563]
**BUG REPORT**

**Minikube version**:
minikube version: v0.19.1

**Environment**:
- **OS**: macOS X 10
- **VM Driver**: VirtualBox
- **ISO version**: v0.18.0

**What happened**:
`npm install grpc` fails in directories mounted from the host and succeeds in standard directories

**What you expected to happen**:
`npm install grpc` should succeed in mounted directories

**How to reproduce it** (as minimally and precisely as possible):
Create the following pod:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: node-runner
spec:
  containers:
  - image: node:6
    name: node-runner
    command: ["bash"]
    args:
    - -c
    - >
      trap : TERM INT;
      sleep 100000d & wait
    volumeMounts:
    - mountPath: /mounted
      name: codebase
  volumes:
  - name: codebase
    hostPath:
      path: /some/path/on/host/system
```

shell into the pod and run
```
$ cd /mounted
$ npm install grpc@1.3.8
# this fails with
# ENOENT: no such file or directory, chmod '/mounted/node_modules/grpc/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js'
$ cd /root
$ npm install grpc@1.3.8 
# this succeeds
```
