### ISSUE TITLE
Unable to pull images from private docker hub repo

### ISSUE THREAD

**Issue by juweins** [kubernetes/minikube#15861]
### What Happened?

Hey guys,

so I tried to pull an image that lives inside my private dockerhub repo. 

So far, I tried:
- I followed the steps as discribed in the official documentation. 
- Patched the serviceaccount 
- Cross-checked the secret in minikube dashboard
- Docker login from both, terminal and from inside the minikube container
- Retried by using the registry-creds addon and enabled it
- Verified, that the installation can at least reach my public repo copy

- I also tried to use an alternative endpoint: registry-1.docker.io/v2

Still facing the issue in ARGO UI

> ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: pull access denied for juweins/privatedocker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

I am using Win10/WSL2 with Ubuntu 20.04. I have not specified any driver, so I guess its docker

Am I missing an essential step or is it simply not possible in minikube?

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/10744043/log.txt)

![image](https://user-images.githubusercontent.com/26652109/219057536-32da3e5f-14b2-4a89-9a21-aadf784ccbfc.png)

### Operating System

Ubuntu

### Driver

Docker

Addition 1:

I am pulling with this section of my argoworkflow:

```yaml
spec:
  entrypoint: orchestrator
  templates:
  - name: orchestrator
    container:
      image: juweins/privatedocker:latest
      command: ["python3", "-c", "print('Hi')"]
    imagePullSecrets:
      - name: regcred



```

**Comment by juweins** [comment]
Addition 1:

I am pulling with this section of my argoworkflow:

```yaml
spec:
  entrypoint: orchestrator
  templates:
  - name: orchestrator
    container:
      image: juweins/privatedocker:latest
      command: ["python3", "-c", "print('Hi')"]
    imagePullSecrets:
      - name: regcred



```
