### ISSUE TITLE
Ingress redirecting HTTP to HTTPS by default

### ISSUE THREAD

**Issue by AidanDelaney** [kubernetes/minikube#1607]
BUG REPORT 
**Minikube version**: v0.19.1

**Environment**:
- **OS**: Fedora 25
- **VM Driver**: virtualbox
- **ISO version** : 0.18.0
- **Install tools**: From upstream i.e. `curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/`

**What happened**

I've created a hello world service, which simply writes "hello world" in a simple web page served on port 80.  Ingress is provided by the ingress extension.  The system is set up to Ingress on port 80 redirecting /hello to / within the service listening on port 80.  The service is handled by the trivial deployment configuration.
```yaml
---
kind: Service
apiVersion: v1
metadata:
    name: hello-world
spec:
    selector:
        app: hello-world
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: strm/helloworld-http
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: hello-ingress
    annotations:
        ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
        - http:
              paths:
                  - path: /hello
                    backend:
                        serviceName: hello-world
                        servicePort: 80
```

**What you expected to happen**:

I expect `curl -v -k http://192.168.99.100/` to return a 404 and `curl -v -k http://192.168.99.100/hello` tor return 200 OK with "hello world" somewhere in the content

What actually happens is that all http requests are 301 to an equivalent https location:

```bash
$ curl -v -k http://192.168.99.100/
*   Trying 192.168.99.100...
* TCP_NODELAY set
* Connected to 192.168.99.100 (192.168.99.100) port 80 (#0)
> GET / HTTP/1.1
> Host: 192.168.99.100
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.11.12
< Date: Mon, 19 Jun 2017 14:52:49 GMT
< Content-Type: text/html
< Content-Length: 186
< Connection: keep-alive
< Location: https://192.168.99.100/
< Strict-Transport-Security: max-age=15724800; includeSubDomains; 
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.11.12</center>
</body>
</html>
* Curl_http_done: called premature == 0
* Connection #0 to host 192.168.99.100 left inta
```

**How to reproduce it** (as minimally and precisely as possible):

```bash
$ minikube start
$ kubectl create -f hello-world.yaml
$  curl -v -k http://192.168.99.100/
$  curl -v -k https://192.168.99.100/hello
```

**Anything else do we need to know**:

Accessing the https redirect leads to an EOF issue

```bash
$ curl -v -k https://192.168.99.100/
*   Trying 192.168.99.100...
* TCP_NODELAY set
* Connected to 192.168.99.100 (192.168.99.100) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* NSS error -5938 (PR_END_OF_FILE_ERROR)
* Encountered end of file
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
curl: (35) Encountered end of file
```
