### ISSUE TITLE
Exiting due to SVC_UNREACHABLE: service not available: no running pod for service story-service found

### ISSUE THREAD

**Issue by AKASH-2998** [kubernetes/minikube#17027]
### What Happened?

I have tied to run the service in minikube but unfortunately i got this error message like this, I have attached the error detail's, TIA.

```
akash@Master-AK:~/Downloads/kub-data-01-starting-setup$ kubectl get service
NAME            TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
kubernetes      ClusterIP      10.96.0.1      <none>        443/TCP        65m
story-service   LoadBalancer   10.98.48.153   <pending>     80:31525/TCP   15s
akash@Master-AK:~/Downloads/kub-data-01-starting-setup$ minikube service story-service
|-----------|---------------|-------------|-----------------------------|
| NAMESPACE |     NAME      | TARGET PORT |             URL             |
|-----------|---------------|-------------|-----------------------------|
| default   | story-service |          80 | http://192.168.59.103:31525 |
|-----------|---------------|-------------|-----------------------------|

❌  Exiting due to SVC_UNREACHABLE: service not available: no running pod for service story-service found
```

### Attach the log file

I have followed the **minikube logs --file=log.txt** command but i didn't find any log's, Same that senario also i have attached below, TIA.

```
akash@Master-AK:~/Downloads/kub-data-01-starting-setup$ minikube logs --file=log.txt
akash@Master-AK:~/Downloads/kub-data-01-starting-setup$ minikube version
minikube version: v1.31.1
commit: fd3f3801765d093a485d255043149f92ec0a695f
akash@Master-AK:~/Downloads/kub-data-01-starting-setup$ 
```

### Operating System

Ubuntu

### Driver

VirtualBox

**Comment by AmitBhandari7777** [comment]
kubectl logs podname

Let me know if it helps

**Comment by imouahrani** [comment]
hi, did you resolve this problem please ??

**Comment by vineeth-r15** [comment]
facing same issue

**Comment by henrikzhupani** [comment]
I faced the same issue, the solution that worked for me :
 - The binding between the service and the pod was not correct. In the yaml file, the name that you are using to create the pod on Deployment, should be the same name with the Service - spec - selector app: name
 
 example
 
 apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dep
  labels:
    app: demo-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: **demo**
          image: test/demo:latest
          ports:
            - containerPort: {testPort}

---
apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-service
spec:
  selector:
    app: **demo**
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {testPort}
      targetPort: {testPort}
      nodePort: {testNodePort}

**Comment by harshan89** [comment]
This usually happens when service unable to find deployment please refer provided simple setup

your app

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      run: webapp
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        run: webapp
        app: webapp
    spec:
      containers:
        - name: webapp
          image: webapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
```

your service

```
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000
```
