### ISSUE TITLE
problem using csi-hostpath-sc and cloning a dynamic pvc ( claim in dataSource not bound or invalid )

### ISSUE THREAD

**Issue by abate** [kubernetes/minikube#17112]
### What Happened?

( the spec of my example at the end of the message )

I'm trying to setup a dynamic pvc that is populated with some data ( and not empty ). I've a deployment that in order to start fast needs to have access to some context data. Since I want to be able to scale up this deployment, I need a dynamic pvc to be created for each replica with exactly the same data ( in my example below the data is held in the datadir-static pv ). I'm using minikube as I want to be able to experiment with this deployment locally. In production I'm going to use a public cluster.

I initialized minikube as :
```
#minikube addons disable storage-provisioner
#minikube addons disable default-storageclass
#minikube addons enable volumesnapshots
#minikube addons enable csi-hostpath-driver
#kubectl patch storageclass csi-hostpath-sc -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}
```
so that `storageclasses.storage.k8s.io` is my default storage provisioner.

The `datadir-template` pvc is ok, the data is there ( clearly the data is mounted using `minikube mount ...` ). But the `datadir` pvc is not created correctly and this is the error :

```
$ k describe pvc datadir
Name:          datadir
Namespace:     default
StorageClass:  csi-hostpath-sc
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: hostpath.csi.k8s.io
               volume.kubernetes.io/selected-node: minikube
               volume.kubernetes.io/storage-provisioner: hostpath.csi.k8s.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
DataSource:
  Kind:   PersistentVolumeClaim
  Name:   datadir-template
Used By:  datadir-inspector
Events:
  Type     Reason                Age                From                                                                               Message
  ----     ------                ----               ----                                                                               -------
  Normal   Provisioning          15s (x5 over 30s)  hostpath.csi.k8s.io_csi-hostpathplugin-722ct_4884fcbe-db3f-4350-9900-510dd8d3b4f5  External provisioner is provisioning volume for claim "default/datadir"
  Warning  ProvisioningFailed    15s (x5 over 30s)  hostpath.csi.k8s.io_csi-hostpathplugin-722ct_4884fcbe-db3f-4350-9900-510dd8d3b4f5  failed to provision volume with StorageClass "csi-hostpath-sc": error getting handle for DataSource Type PersistentVolumeClaim by Name datadir-template: claim in dataSource not bound or invalid
  Normal   ExternalProvisioning  8s (x6 over 39s)   persistentvolume-controller                                                        waiting for a volume to be created, either by external provisioner "hostpath.csi.k8s.io" or manually created by system administrator
```

When I look at the `pv datadir-static` and `datadir-template` they are both ok, and I can't understand the error : `claim in dataSource not bound or invalid` :

```
$ k get pv datadir-static 
NAME             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                      STORAGECLASS      REASON   AGE
datadir-static   10Gi       RWO            Retain           Bound    default/datadir-template   csi-hostpath-sc            2m53s

$ k get pvc datadir-template 
NAME               STATUS   VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS      AGE
datadir-template   Bound    datadir-static   10Gi       RWO            csi-hostpath-sc   3m21s
```

I'm not sure if this is a problem with the provisioner or minikube. 

This is the complete specification
```
# create a pv with a copy of the node datadir
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-static
  labels:
    name: datadir-static
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /datadir
  storageClassName: csi-hostpath-sc
---
# bound this pvc to the datadir-static pv
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: datadir-template
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-hostpath-sc
  selector:
    matchLabels:
      name: "datadir-static"
---
# use the datadir-template as data source for the dynimic provisioning
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: datadir
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: datadir-template
  storageClassName: csi-hostpath-sc
---
apiVersion: v1
kind: Pod
metadata:
  name: datadir-inspector
spec:
  containers:
  - image: busybox
    name: datadir-inspector
    command: ["tail"]
    args: ["-f", "/dev/null"]
    volumeMounts:
    - mountPath: /pvc
      name: pvc-mount
  volumes:
  - name: pvc-mount
    persistentVolumeClaim:
      claimName: datadir
```
after `k apply -f example.yml` I can run `k exec -it datadir-inspector -- sh` and I would expect my data in `ls /pvc` . but there is none.

I believe this issue is similar or related : https://github.com/kubernetes-csi/csi-driver-host-path/issues/398

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/12417094/log.txt)

### Operating System

Ubuntu

### Driver

Docker
