### ISSUE TITLE
Add cloud-build file to manage release via CI

### ISSUE THREAD

**Issue by prnvkv** [kubernetes/minikube#17807]
Usually, projects built on community infra will have a cloudbuild yaml file with instructions to kick off the build in their own GCP project.

See a sample here: https://github.com/kubernetes-sigs/bom/blob/main/cloudbuild.yaml

This activity is part of the Security-slam
/ @puerco

**Comment by ArangoGutierrez** [comment]
Example -> https://github.com/kubernetes-sigs/kueue/blob/main/cloudbuild.yaml

**Comment by ArangoGutierrez** [comment]
```yaml
# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 3000s
# A build step specifies an action that you want Prow to perform.
# For each build step, Prow executes a job.
steps:
  # see https://github.com/kubernetes/test-infra/tree/master/config/jobs/image-pushing
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20221214-1b4dd4d69a'
    entrypoint: make
    args:
      - image-push
    env:
      - IMAGE_REGISTRY=gcr.io/$PROJECT_ID
      - GIT_TAG=$_GIT_TAG
      - EXTRA_TAG=$_PULL_BASE_REF
      - DOCKER_BUILDX_CMD=/buildx-entrypoint
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '0.0.0'
  # _PULL_BASE_REF will contain the ref that was pushed to trigger this build -
  # a branch like 'main' or 'release-0.2', or a tag like 'v0.2'.
  _PULL_BASE_REF: 'main'
options:
  substitution_option: ALLOW_LOOSE
```
