### ISSUE TITLE
Minikube only allow curl to service with port 80?

### ISSUE THREAD

**Issue by hoangdangduy** [kubernetes/minikube#18087]
### What Happened?

I create Deployment and expose Service with the manifest file below. When I use port 80 I can curl http://$(minikube ip):32000, and minikube ssh I also curl <cluster IP>. However, when I changed the port to difference 80, it couldn't connect. Does it mean do run minikube service only on port 80?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: isocias-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx
        name: nginx-deployment
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: isocias-dev
spec:
  ports:
  - port: 8099
    protocol: TCP
    targetPort: 8099
    nodePort: 32000
  selector:
    app: nginx-deployment
  type: NodePort
status:
  loadBalancer: {}
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/14156469/log.txt)

### Operating System

macOS (Default)

### Driver

QEMU
