### ISSUE TITLE
My custom Docker image differs when loaded on a Deployment

### ISSUE THREAD

**Issue by mbaragiola** [kubernetes/minikube#1843]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.21.0
- **OS** (e.g. from /etc/os-release): macOS 10.13 Beta
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.0.iso
- **Install tools**: brew?
- **Others**:
`docker version`:
```
docker version
Client:
 Version:      17.06.0-ce
 API version:  1.29 (downgraded from 1.30)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        unknown-buildtime
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**What happened**: Build custom Django app image. Try to load it with `minikube` but the image loaded is different for some reason.

**What you expected to happen**: Get the same custom image loaded.

**How to reproduce it** (as minimally and precisely as possible):

`Dockerfile`:

```
FROM python:3.5-slim

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get -y install \
    libjpeg-dev \
    libtiff5-dev \
    libfreetype6-dev \
	liblcms2-dev \
    libwebp-dev \
    gettext \
    libgettextpo-dev \
    build-essential \
    libssl-dev \
    python3-dev \
    && apt-get clean

COPY . /app
RUN pip install --no-cache-dir -r /app/requirements/production.pip \
    && rm -rf /app/requirements \
    /app/compose \
    /app/.git \
    /app/.tox \
    /app/.coverage \
    /app/kubernetes \
    /app/htmlcov \
    && rm /app/Dockerfile \
    /app/README.md \
    /app/TODO.txt \
    /app/docker-compose.yml \
    /app/.gitignore \
    /app/.dockerignore \
    /app/.DS_Store

WORKDIR /app

CMD ["bash"]
```

I build the image using: `docker build -t django:latest .`
Image is correctly built and tagged. If I run `docker run django:latest pwd` I get `/app` and if I run `docker run django:latest ls` I get the django app files listed.

Here's my `stage.yml` file:

```yaml
#
# POSTGRES
#
apiVersion: v1
kind: Service
metadata:
  name: postgres-master
  labels:
    app: postgres
    tier: backend
    role: master
spec:
  selector:
    app: postgres
    tier: backend
    role: master
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/postgres-data/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdata-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: dGVzdGluZwo=
  password: dGVzdGluZwo=
  database: dGVzdGluZwo=
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-master
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  minReadySeconds: 15
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: postgres
        role: master
        tier: backend
    spec:
      containers:
      - image: postgres:9.6-alpine
        imagePullPolicy: "IfNotPresent"
        name: master
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        ports:
        - containerPort: 5432
          name: postgres-master
        volumeMounts:
        - name: postgres-data
          mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgresdata-claim
#
# REDIS CACHE
#
---
apiVersion: v1
kind: Service
metadata:
  name: cache-master
  labels:
    app: cache
    tier: backend
    role: master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: cache
    tier: backend
    role: master
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cache-master
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  minReadySeconds: 15
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: cache
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis:4.0-alpine
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 6379
#
# REDIS SESSIONS
#
---
apiVersion: v1
kind: Service
metadata:
  name: session-master
  labels:
    app: session
    tier: backend
    role: master
spec:
  selector:
    app: session
    tier: backend
    role: master
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: session-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/session-data/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sessiondata-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: session-master
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  minReadySeconds: 15
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: session
        role: master
        tier: backend
    spec:
      containers:
      - image: redis:4.0-alpine
        imagePullPolicy: "IfNotPresent"
        name: master
        ports:
        - containerPort: 6379
          name: session-master
        volumeMounts:
        - name: session-data
          mountPath: /var/lib/redis/
      volumes:
        - name: session-data
          persistentVolumeClaim:
            claimName: sessiondata-claim
#
# REDIS CELERY BROKER
#
---
apiVersion: v1
kind: Service
metadata:
  name: broker-master
  labels:
    app: broker
    tier: backend
    role: master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: broker
    tier: backend
    role: master
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: broker-master
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  minReadySeconds: 15
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: broker
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis:4.0-alpine
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 6379
#
# Django + Gunicorn
#
---
apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
    tier: midend
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: django
    tier: midend
---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  secret-key: YW13MDU0cS0zanR2NDhheTUjJnptMiY9akBfbmdtQGF1JTFoITQxdDN4bXc3X3l4MD0K
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  minReadySeconds: 15
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: django
        tier: midend
    spec:
      containers:
      - name: django
        image: django:latest
        imagePullPolicy: "IfNotPresent"
        command: ["ls"]
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: config.settings.staging
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: secret-key
        - name: DJANGO_DATABASE_HOST
          value: postgres-master
        - name: DJANGO_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DJANGO_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DJANGO_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        - name: DJANGO_SECURE_SSL_REDIRECT
          value: nay
        - name: DJANGO_SESSION_REDIS_HOST
          value: session-master
        - name: DJANGO_SESSION_REDIS_PORT
          value: '6379'
        - name: DJANGO_SESSION_REDIS_DB
          value: '0'
        - name: DJANGO_CACHE_REDIS_HOST
          value: cache-master
        - name: DJANGO_CACHE_REDIS_PORT
          value: '6379'
        - name: DJANGO_CACHE_REDIS_DB
          value: '0'
        - name: CELERY_BROKER_URL
          value: redis://broker-master:6379/0
        ports:
        - containerPort: 8000
      initContainers:
      - name: init-postgres
        image: busybox:1.27
        imagePullPolicy: "IfNotPresent"
        command: ['sh', '-c', 'until nslookup postgres-master; do echo waiting for postgres; sleep 2; done;']
      - name: init-cache
        image: busybox:1.27
        imagePullPolicy: "IfNotPresent"
        command: ['sh', '-c', 'until nslookup cache-master; do echo waiting for redis-cache; sleep 2; done;']
      - name: init-session
        image: busybox:1.27
        imagePullPolicy: "IfNotPresent"
        command: ['sh', '-c', 'until nslookup session-master; do echo waiting for redis-session; sleep 2; done;']
```

The line that has the `command: ["ls"]` should be where `gunicorn` or `celery` gets triggered, but I rewrote it to `ls` so I can show that `/app` doesn't exist on that `django:latest` that is loaded.

**Output of `minikube logs` (if applicable)**:

```
$ kubectl get pods
NAME                               READY     STATUS             RESTARTS   AGE
broker-master-1813013339-bbgcb     1/1       Running            0          14s
cache-master-962058144-gm91m       1/1       Running            0          14s
django-1525332021-vkd8g            0/1       CrashLoopBackOff   1          14s
postgres-master-2420790967-mwpwg   1/1       Running            0          15s
session-master-711038512-gs20z     1/1       Running            0          14s
```

```
$ kubectl logs --previous django-1525332021-vkd8g
bin
boot
dev
etc
home
lib
lib64
media
mnt
opt
proc
root
run
sbin
srv
sys
tmp
usr
var
```

**Anything else do we need to know**:

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
django              latest              212971fe6dc0        About an hour ago   706MB
postgres            9.6-alpine          e9e9c4470522        7 days ago          37.7MB
python              3.5-slim            6b00db1e9ed3        8 days ago          200MB
redis               4.0-alpine          9d8fa9aa0e5b        3 weeks ago         27.5MB
busybox             1.27                efe10ee6727f        4 weeks ago         1.13MB
nginx               1.13-alpine         ba60b24dbad5        5 weeks ago         15.5MB
```

I'm lost with this. At first I got errors that user `django` had no passwd entry, so I removed the user from `Dockerfile` and used root instead. Then I realized that `/app` is not in the image loaded by `minikube`.

If I can do anything else to further debug this problem, please let me know. Thanks in advance!
