### ISSUE TITLE
Proposal: Suggest NFS as default filesystem for local dev

### ISSUE THREAD

**Issue by eecue** [kubernetes/minikube#1889]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  FEATURE REQUEST

Please provide the following details:

**Environment**: 

**Minikube version**: v0.21.0
- **OS**: OS X 
- **VM Driver**: Virtualbox
- **ISO version**: minikube-v0.23.0.iso
- **Install tools**: brew
- **Others**:

**What happened**:

We noticed our application ran significantly slower in k8s/minikube compared to vagrant.  We changed our local files to mount via NFS instead of 9p and our dev system is now much faster than vagrant.

**What you expected to happen**:

We should update the docs to recommend using NFS for local dev instead of 9p, at least for OS X, but probably makes sense on linux, too.   We're going to test on Windows shortly to see if it has the same effect which I assume it will.

**How to reproduce it** (as minimally and precisely as possible):

Set up a persistent volume store using NFS and use it instead of 9p:

1) Update your `/etc/exports` to allow minikube to access it:

`$ echo "/Users -alldirs -mapall="$(id -u)":"$(id -g)" 192.168.99.100"| sudo tee -a /etc/exports`

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.99.1
    path: /Users/Shared/Sites/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cr-volume
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
```

**Anything else do we need to know**:

If you think this is a good idea, I'll make a PR for the update docs.  It's been life changing for our devs.
