### ISSUE TITLE
PodSecurityPolicies in Minikube

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/minikube#1956]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **Minikube version** : v0.21.0 (I couldn't use the current version because of: https://github.com/kubernetes/minikube/issues/1952)
- **Kubernetes version**: 1.7.0 (default Version in 0.21)
- **OS** : Windows 7 Build 7601
- **VM Driver** : virtualbox
- **ISO version** : minikube-v0.23.0.iso

**What happened**:

I tried to get PodSecurityPolicies to work in Minikube.

**What you expected to happen**:

It looks like PodSecurityPolicies are not enforced.

**How to reproduce it** (as minimally and precisely as possible):

I started Minikube with:
````
export MSYS_NO_PATHCONV=1

minikube start \
   --extra-config=apiserver.Authorization.Mode=RBAC \
   --extra-config=controller-manager.UseServiceAccountCredentials=true \
   --extra-config=apiserver.Admission.PluginNames=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,PodSecurityPolicy \
   --v=4 \
   --extra-config=apiserver.Audit.LogOptions.Path=/tmp/apiserver.log 
````

I deployed the following resources (based on [PSP example](https://github.com/kubernetes/examples/blob/master/staging/podsecuritypolicy/rbac/README.md))
````
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
      addonmanager.kubernetes.io/mode: Reconcile
  name: kube-system-default-cluster-admin
subjects:
- namespace: kube-system
  kind: ServiceAccount
  name: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: privileged
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: privileged
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: restricted
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - restricted
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: privileged
subjects:
- namespace: default
  kind: ServiceAccount
  name: privileged
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: privileged
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: restricted
subjects:
- namespace: default
  kind: ServiceAccount
  name: restricted
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: restricted
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox-restricted
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: busybox-restricted
    spec:
      serviceAccountName: restricted
      containers:
      - name: busybox
        image: busybox
        command:
        - sleep
        - "3600"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox-privileged
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: busybox-privileged
    spec:
      serviceAccountName: privileged
      containers:
      - name: busybox
        image: busybox
        command:
        - sleep
        - "3600"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-restricted
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx-restricted
    spec:
      serviceAccountName: restricted
      containers:
      - name: nginx
        image: nginx
        command:
        - sleep
        - "3600"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-privileged
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx-privileged
    spec:
      serviceAccountName: privileged
      containers:
      - name: nginx
        image: nginx
        command:
        - sleep
        - "3600"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alpine-restricted
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: alpine-restricted
    spec:
      serviceAccountName: restricted
      containers:
      - name: alpine
        image: alpine
        command:
        - sleep
        - "3600"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alpine-privileged
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: alpine-privileged
    spec:
      serviceAccountName: privileged
      containers:
      - name: alpine
        image: alpine
        command:
        - sleep
        - "3600"
````

All pods created from deployments with `privileged` ServiceAccount should run and all deployments with `restricted` ServiceAccount shouldn't be started (with some message like: `container has runAsNonRoot and image will run as root`).

Instead Pods are running / not running basically random:
````
$ kubectl get po
NAME                                  READY     STATUS    RESTARTS   AGE
busybox-privileged-1454604962-14cgp   1/1       Running                                                 0          11m
busybox-privileged-1454604962-15xqp   1/1       Running                                                 0          11m
busybox-privileged-1454604962-506w2   1/1       Running                                                 0          11m
busybox-privileged-1454604962-d3jb5   1/1       Running                                                 0          11m
busybox-privileged-1454604962-dq2pg   1/1       Running                                                 0          11m
busybox-privileged-1454604962-fbnjw   1/1       Running                                                 0          11m
busybox-privileged-1454604962-fkxrt   0/1       container has runAsNonRoot and image will run as root   0          11m
busybox-privileged-1454604962-jx89j   1/1       Running                                                 0          11m
busybox-privileged-1454604962-pzzzc   0/1       container has runAsNonRoot and image will run as root   0          11m
busybox-privileged-1454604962-qz208   1/1       Running                                                 0          11m
busybox-restricted-294384190-1c12h    0/1       container has runAsNonRoot and image will run as root   0          11m
busybox-restricted-294384190-2kjg4    1/1       Running                                                 0          11m
busybox-restricted-294384190-397qk    1/1       Running                                                 0          11m
busybox-restricted-294384190-b5bch    1/1       Running                                                 0          11m
busybox-restricted-294384190-cbkmc    1/1       Running                                                 0          11m
busybox-restricted-294384190-fbzlv    1/1       Running                                                 0          11m
busybox-restricted-294384190-sxnrw    1/1       Running                                                 0          11m
busybox-restricted-294384190-x41hm    1/1       Running                                                 0          11m
busybox-restricted-294384190-xj3kr    0/1       container has runAsNonRoot and image will run as root   0          11m
busybox-restricted-294384190-znzqm    1/1       Running                                                 0          11m
[... only busybox shown for brevity, nginx and alpine behave similarly ]
````

Usually, the PodSecurityPolicy admission controller should assign PodSecurityPolicies depending on the permissions of the ServiceAccounts of the deployments.
````
$ kubectl get po -o=jsonpath='{range .items[*]}{.metadata.name}{" psp: "}{.metadata.annotations.kubernetes\.io/psp}{"\n"}{end}'
busybox-privileged-1454604962-14cgp psp: privileged
busybox-privileged-1454604962-15xqp psp: privileged
busybox-privileged-1454604962-506w2 psp: privileged
busybox-privileged-1454604962-d3jb5 psp: privileged
busybox-privileged-1454604962-dq2pg psp: privileged
busybox-privileged-1454604962-fbnjw psp: privileged
busybox-privileged-1454604962-fkxrt psp: restricted
busybox-privileged-1454604962-jx89j psp: privileged
busybox-privileged-1454604962-pzzzc psp: restricted
busybox-privileged-1454604962-qz208 psp: privileged
busybox-restricted-294384190-1c12h psp: restricted
busybox-restricted-294384190-2kjg4 psp: privileged
busybox-restricted-294384190-397qk psp: privileged
busybox-restricted-294384190-b5bch psp: privileged
busybox-restricted-294384190-cbkmc psp: privileged
busybox-restricted-294384190-fbzlv psp: privileged
busybox-restricted-294384190-sxnrw psp: privileged
busybox-restricted-294384190-x41hm psp: privileged
busybox-restricted-294384190-xj3kr psp: restricted
busybox-restricted-294384190-znzqm psp: privileged
[... only busybox shown for brevity, nginx and alpine behave similarly ]
````

The log of localkube shows the following:
````
$ journalctl -f -u localkube --since "2017-09-13 08:07:00" --until "2017-09-13 08:12:00" > /c/Users/SBUERIN/.minikube/localkube.log
[...]
Sep 13 08:08:49 minikube localkube[3652]: I0913 08:08:49.197606    3652 admission.go:128] getting pod security policies for pod  (generate: busybox-restricted-294384190-)
Sep 13 08:08:49 minikube localkube[3652]: I0913 08:08:49.203122    3652 admission.go:344] validating pod  (generate: busybox-restricted-294384190-) against providers: privileged,restricted
Sep 13 08:08:49 minikube localkube[3652]: I0913 08:08:49.203288    3652 admission.go:161] pod  (generate: busybox-restricted-294384190-) validated against provider privileged
[...]
````

In my opinion, only the restricted psp should be returned from `getting pod security policies` for pods running with the `restricted` ServiceAccount.

I'm not really sure but I think we had the same problem in other Kubernetes clusters until we set the UseServiceAccountCredentials flag on the ControllerManager. The problem was that our ControllerManager was running as cluster-admin before and RBAC on the PSPs was not applied correctly. I guess in Minikube all Kubernetes control plane components run as cluster-admin. Could this be the problem? Am I missing something?
