### ISSUE TITLE
CNI Environment Variables Missing in Minikube

### ISSUE THREAD

**Issue by orosiferenc3** [kubernetes/minikube#20050]
### What Happened?

I have created a minimal `CNI` plugin script to log the `CNI_COMMAND` and other relevant environment variables. When using this script in `Kind`, **everything works as expected**. However, when running the same setup in `Minikube`, the environment variables (`CNI_CONTAINERID`, `CNI_NETNS`, etc.) appear to be missing or set to dummy values. It seems that the environment variables are not being passed through to the plugins in `Minikube`. Is this a bug or a by-design solution for security purposes?

### Reproduce:
1. Modify `/etc/cni/net.d/1-k8s.conflist` to the following: (I also tried other `CNI`s like `flannel` which is located in `/etc/cni/net.d/10-flannel.conflist`)
```yaml
{
  "cniVersion": "0.4.0",
  "name": "bridge",
  "plugins": [
    {
      "type": "bridge",
      "bridge": "bridge",
      "addIf": "true",
      "isDefaultGateway": true,
      "forceAddress": false,
      "ipMasq": true,
      "hairpinMode": true,
      "ipam": {
        "type": "host-local",
        "subnet": "10.244.0.0/16"
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    },
    {
      "type": "firewall"
    },
    {
      "type": "mycniplugin"
    }
  ]
}
```

2. My `CNI` plugin (`mycniplugin`) looks like this:
```bash
#!/bin/bash

STDIN="$(cat /dev/stdin)"
LOG_FILE=/tmp/cni-inspect.log

# Log a message into a log file
log() { echo -e "${@}" | tee -a ${LOG_FILE} &>/dev/null; }

# Log CNI environment variables into the log file
logAll() {
  log "CNI call for ${CNI_COMMAND} on ${CNI_CONTAINERID}
  - CNI_COMMAND: ${CNI_COMMAND}
  - CNI_CONTAINERID: ${CNI_CONTAINERID}
  - CNI_NETNS: ${CNI_NETNS}
  - CNI_IFNAME: ${CNI_IFNAME}
  - CNI_ARGS: ${CNI_ARGS}
  - CNI_PATH: ${CNI_PATH}\n"
}
logAll
```

### Expected Output (Observed in Kind):
```
CNI call for ADD on 0fa7e1e09a71eae701bc50e7bddf811f491652d5c326f0a0f0830079bbfbeea8
  - CNI_COMMAND: ADD
  - CNI_CONTAINERID: 0fa7e1e09a71eae701bc50e7bddf811f491652d5c326f0a0f0830079bbfbeea8
  - CNI_NETNS: /var/run/netns/cni-43ac5215-c830-b99c-7b57-2444340b0b39
  - CNI_IFNAME: eth0
  - CNI_ARGS: IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=pod;K8S_POD_INFRA_CONTAINER_ID=0fa7e1e09a71eae701bc50e7bddf811f491652d5c326f0a0f0830079bbfbeea8;K8S_POD_UID=c80953ae-5e5e-4a9e-8512-78e4b26c7a4f
  - CNI_PATH: /opt/cni/bin
```

### Actual Output (Observed in Minikube):
```
CNI call for VERSION on 
  - CNI_COMMAND: VERSION
  - CNI_CONTAINERID: 
  - CNI_NETNS: dummy
  - CNI_IFNAME: dummy
  - CNI_ARGS: 
  - CNI_PATH: dummy
```

### Operating System

Ubuntu

### Driver

Docker
