### ISSUE TITLE
I cannot get minikube (podman driver, inside a KVM) to expose my service to the host

### ISSUE THREAD

**Issue by flixman** [kubernetes/minikube#20412]
### What Happened?

I am learning about kubernetes and minikube. I have set up a KVM in my laptop and installed minikube inside it, with the podman driver. Everything seems to be ok (I can apply pods, deployments, services, etc.) but I cannot access them.

To start minikube I am executing "/usr/bin/minikube start --nodes=1  --force --apiserver-ips <host_ip> --listen-address 0.0.0.0", and the deployment that I am applying is:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
```

I would expect that, after the pods are up and running, I should be able to run "curl http://<host_ip>:30080" from the host itself, but I get an error.

### Attach the log file

[log.txt](https://github.com/user-attachments/files/18812080/log.txt)

### Operating System

Ubuntu

### Driver

Podman
