### ISSUE TITLE
nginx-load-balancer-conf keeps getting reset (ingress addon)

### ISSUE THREAD

**Issue by micdah** [kubernetes/minikube#2165]
Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.23.0
- **OS** (e.g. from /etc/os-release): Windows 10, 64-bit (1709)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperv
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.6.iso

**What happened**:
Whenever I change the `nginx-load-balancer-conf` after enabling the ingress addon (`minikube addons enable ingress`) it will revert to it's original values after a short duration.

I need to increase some buffers in the nginx configuration to get it to work with our application.

This is the configuration I am applying using `kubectl apply -f`:
```
apiVersion: v1
data:
  fastcgi-buffers: 16 16k
  fastcgi-buffers-size: 32k
  map-hash-bucket-size: "128"
  proxy-buffer-size: 128k
  proxy-buffers: 4 256k
  proxy-busy-buffers-size: 256k
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"map-hash-bucket-size":"128"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"nginx-load-balancer-conf","namespace":"kube-system"}}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: nginx-load-balancer-conf
  namespace: kube-system
```

**What you expected to happen**:
I expected the updated configuration to not be changed at any point, unless I changed it or disabled and then re-enabled the minikube addon.

**How to reproduce it** (as minimally and precisely as possible):
```
minikube start
minikube addons enable ingress
kubectl apply -f nginx-conf.yml
# Verify changes
kubectl get configmap -n kube-system nginx-load-balancer-conf -o yaml
# Observe that new data has been added
# Wait some time (a few minutes maybe)
kubectl get configmap -n kube-system nginx-load-balancer-conf -o yaml
# Observe that new data is now gone
```
