### ISSUE TITLE
Storage does not behave as expected

### ISSUE THREAD

**Issue by thxCode** [kubernetes/minikube#2198]
**SUGGESTION**

Please provide the following details:

**Environment**: Kubernetes 1.6 and later

**Minikube version**: v0.23.0
- **OS**: Darwin Kernel Version 17.2.0
- **VM Driver**: virtualbox
- **ISO version**: minikube-v0.23.6.iso
- **Install tools**: **kubeadm**

**What happened**:

The [guides](https://github.com/kubernetes/minikube/tree/master/deploy/addons ) of StorageClass and Storage-Provisioner already does not apply to the environment created by **kubeadm** bootstrapper.

**What you expected to happen**:

##### E1: [DefaultStorageClass](https://v1-6.docs.kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/#changing-the-default-storageclass)

https://github.com/kubernetes/minikube/blob/10f2bb578d15c6941f5de78a36ff35a53cc8520f/deploy/addons/storageclass/storageclass.yaml#L1-L11

Changing the annotation as below:

``` yaml
 ...
   ...
     storageclass.kubernetes.io/is-default-class: "true" 
  ... 
```

##### E2: Storage-Provisioner

https://github.com/kubernetes/minikube/blob/10f2bb578d15c6941f5de78a36ff35a53cc8520f/deploy/addons/storage-provisioner/storage-provisioner.yaml#L15-L28

Adding volume configuation as below:

``` yaml
...
  ...
    - ...
      volumeMounts:
            - name: pv-volume
              mountPath: /tmp/hostpath-provisioner
  volumes:
    - name: pv-volume
      hostPath:
        path: /mnt/sda1/hostpath-provisioner

```
