### ISSUE TITLE
Unable to use webhooks for authn

### ISSUE THREAD

**Issue by daniepar** [kubernetes/minikube#2201]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Minikube version** (use `minikube version`): v0.23.0
- **OS** (e.g. from /etc/os-release): macOS Sierra
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.6.iso

**What happened**: Always get the same error message (invalid bearer token) no matter what is contained in the webhook config file. 

**What you expected to happen**: Specific error messages related to config or SSL cert chain issues.

**How to reproduce it** (as minimally and precisely as possible): 
1. SSH into the minikube VM
1. Create a file called test.yaml and fill it with [contents from official docs](https://kubernetes.io/docs/admin/authentication/#webhook-token-authentication):

 ```yaml
# clusters refers to the remote service.
clusters:
  - name: name-of-remote-authn-service
    cluster:
      certificate-authority: /path/to/ca.pem         # CA for verifying the remote service.
      server: https://authn.example.com/authenticate # URL of remote service to query. Must use 'https'.

# users refers to the API server's webhook configuration.
users:
  - name: name-of-api-server
    user:
      client-certificate: /path/to/cert.pem # cert for the webhook plugin to use
      client-key: /path/to/key.pem          # key matching the cert

# kubeconfig files require a context. Provide one for the API server.
current-context: webhook
contexts:
- context:
    cluster: name-of-remote-authn-service
    user: name-of-api-sever
  name: webhook
```
3. Launch minikube with the following command:
```
minikube start --extra-config=apiserver.Authentication.Webhook.ConfigFile=/home/docker/test.yaml
```
4. Call curl against API server using any token value:
 ```
curl -k -H "Authorization: Bearer $token" -k https://192.168.99.100:8443/api/v1/nodes
```

**Output of `minikube logs` (if applicable)**: 
```
Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
  ```

**Anything else do we need to know**: 
I actually ran the kube-apiserver independently of the minikube VM and it will actually tell me if something is wrong with the config file or SSL certs. But since the kube-apiserver in minikube is always throwing the same error, it seems to indicate there is some issue there.
