### ISSUE TITLE
NFS volume cant be mounted via service name because of broken DNS

### ISSUE THREAD

**Issue by monotek** [kubernetes/minikube#2218]
BUG REPORT

**Minikube version**: v0.23.0

- **OS**: Ubuntu 17.10
- **VM Driver**: virtualbox
- **ISO version**: minikube-v0.23.6.iso
- **Install tools**: 

**What happened**: 
NFS Mount fails because of broken DNS / kuberntes nfs service name could not be resolved

**What you expected to happen**:
NFS Volume is mounted

**How to reproduce it** (as minimally and precisely as possible):
* Start the a nfs contaienr
* create a nfs service
* put the nfs servicename into a volumespec like:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mydeployment
  namespace: mynamespace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
        component: services
    spec:
      volumes:
      - name: data
        nfs:
          server: kubernetes-nfs-service
          path: /
```

** Workaround **:
* Put the ip of the nfs service inside the volume spec and it works

**Possible fix**: 
* https://github.com/kubernetes/kubernetes/pull/42376

**Comment by jingxu97** [comment]
Could you please try to use the full DNS name for the service, e.g., kubernetes-nfs-service-default.svc.cluster.local

Please check https://github.com/kubernetes/dns/blob/master/docs/specification.md
and let me know if you still have issues of mounting. Thanks!

**Comment by dbaba** [comment]
@jingxu97 minikube still doesn't resolve the FQDN address but GKE does.

minikube version: v0.28.0

I applied the same PersistentVolume yaml (see below) to minikube and GKE cluster. On minikube, mounting volume always failed.
The `kubectl describe pod` command to minikube pod showed the following error message at Events part.
```
Events:
  Type     Reason                 Age   From               Message
  ----     ------                 ----  ----               -------
  Normal   Scheduled              50s   default-scheduler  Successfully assigned my-app-9bf649db7-fnb2f to minikube
  Normal   SuccessfulMountVolume  50s   kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-f9ql6"
  Warning  FailedMount            50s   kubelet, minikube  MountVolume.SetUp failed for volume "my-app-data" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/f58175de-6fb1-11e8-88ab-080027a4eadc/volumes/kubernetes.io~nfs/my-app-data --scope -- mount -t nfs my-nfs-server.my-ns.svc.cluster.local:/ /var/lib/kubelet/pods/f58175de-6fb1-11e8-88ab-080027a4eadc/volumes/kubernetes.io~nfs/my-app-data
Output: Running scope as unit: run-ra9b82c5f871c40ab9ae41a1d53d4d5b4.scope
mount.nfs: Failed to resolve server my-nfs-server.my-ns.svc.cluster.local: Name or service not known
(snip)
```

pv-yaml: => this worked on GKE
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-app-data
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: my-nfs-server.my-ns.svc.cluster.local
    path: "/"
```
