### ISSUE TITLE
DNS not working inside minikube pods since 23.6

### ISSUE THREAD

**Issue by ceridwen** [kubernetes/minikube#2302]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.24.1
- **OS** (e.g. from /etc/os-release): Mac OS 10.12.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.23.6.iso
- **Install tools**: Homebrew
- **Others**: Kubernetes version 1.7.5, containers built using Alpine 3.6

**What happened**:

I first noticed this issues when I wasn't able to reach Dockerhub inside a pod, but it looks like DNS is failing globally.  I can ping 8.8.8.8, but if I try to reach anything using DNS, it fails.

```
/networking # nslookup registry-1.docker.io
nslookup: can't resolve '(null)': Name does not resolve
/networking # nslookup google.com
nslookup: can't resolve '(null)': Name does not resolve
```

```
/ # cat /etc/resolv.conf
nameserver 10.0.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```

Pinging 10.0.0.10 also fails to connect.

This used to work when I was on version .21.  It's broken since I upgraded to .23.6 and .24.1.

**What you expected to happen**:

DNS to work.

**How to reproduce it** (as minimally and precisely as possible):

Start a pod using this yaml with the API version added:

```
kind: Pod
metadata:
  generateName: networking-
  labels:
    test: test
spec:
  containers:
  - image: ceridwen/networking:v1
    imagePullPolicy: Always
    name: networking
    readinessProbe:
      tcpSocket:
        port: 5000
      initialDelaySeconds: 5
      periodSeconds: 1
    restartPolicy: Always
```

I also saw this using the docker:stable-dind image.

**Output of `minikube logs` (if applicable)**:

I didn't see anything in the logs that looked relevant, I can post them if needed.
