### ISSUE TITLE
 Running microsoft/dotnet:2.0-runtime image in Docker works, but fails in Kubernetes (minikube)

### ISSUE THREAD

**Issue by pr0nin** [kubernetes/minikube#2328]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:
Windows 10, 32 GB RAM, i7 processor

**Minikube version** (use `minikube version`): v0.24.1
- **OS** (e.g. from /etc/os-release):  Windows 10 Fall Creators Update
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyper-v
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.23.6
- **Install tools**: chocolatey

**What happened**:

I've built a dockerfile, tagged it and uploaded it to Azure Container Registry (nnnn.azurecr.io/worker:v1).

When executing ```docker run nnnn.azurecr.io/worker:v1``` it works as expected and writes to the console every 5 seconds.

But when creating a deployment in Minikube the only logs I can see from the pods are:

```
Logs from worker in fake-worker-698f87974f-b9fr6

Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
  http://go.microsoft.com/fwlink/?LinkID=798306&amp;clcid=0x409
```

**What you expected to happen**:

The logs for the worker running in Minikube should be the same as when running in Docker

Every 5 seconds the worker should write an INF and an ERR message.

```
PS C:\folders\worker> docker run nnnn.azurecr.io/worker:v1
[15:14:20 INF] StdOut?
[15:14:20 ERR] StdErr?
[15:14:25 INF] StdOut?
[15:14:25 ERR] StdErr?
```

**How to reproduce it** (as minimally and precisely as possible):

A dotnet core 2.0 console application set to run forever and write to console every 5 seconds.

### dockerfile
```docker
FROM microsoft/dotnet:2.0-sdk AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:2.0-runtime
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "worker.dll"]
```

### deployment yaml
```yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: faker-worker
  labels:
    app: fakeworker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakeworker
  template:
    metadata:
      labels:
        app: fakeworker
    spec:
      containers:
      - name: fakeworker
        image: nnnn.azurecr.io/worker:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: settings
          mountPath: /app
          readOnly: true
      volumes:
      - name: settings
        secret:
          secretName: settings-appsettings
      imagePullSecrets:
        - name: regsecret
```

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
