### ISSUE TITLE
spec.selector: Required value in the ReplicaSet

### ISSUE THREAD

**Issue by narunask** [kubernetes/minikube#2349]
**This is a BUG REPORT**:

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): 
```
$ minikube version
minikube version: v0.24.1
```

- **OS** (e.g. from /etc/os-release):
```
$ uname -a
Linux dev-box 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.2 (stretch)
Release:	9.2
Codename:	stretch
```
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
```
"DriverName": "none",
```
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:

```
$ kubectl create -f ReplicaSet/test.yaml 
The ReplicaSet "test-rs" is invalid: 
* spec.selector: Required value
* spec.template.metadata.labels: Invalid value: map[string]string{"rel":"dev"}: `selector` does not match template `labels`
```
**What you expected to happen**:

Docs imply that `replicasets.spec.selector` is optional and if it's left empty, it should be defaulted to the labels present on the pod template. Looks like this is not the case anymore.

```
$ kubectl explain replicasets.spec.selector
RESOURCE: selector <Object>

DESCRIPTION:
     Selector is a label query over pods that should match the replica count. If
     the selector is empty, it is defaulted to the labels present on the pod
     template. Label keys and values that must match in order to be controlled by
     this replica set. More info: https://kubernetes.io/docs/concepts/overview/
     working-with-objects/labels/#label-selectors/

    A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.

FIELDS:
   matchLabels	<object>
     matchLabels is a map of {key,value} pairs. A single {key,value} in the
     matchLabels map is equivalent to an element of matchExpressions, whose key
     field is "key", the operator is "In", and the values array contains only
     "value". The requirements are ANDed.

   matchExpressions	<[]Object>
     matchExpressions is a list of label selector requirements. The requirements
     are ANDed.
```

**How to reproduce it** (as minimally and precisely as possible):

Try to create the following *ReplicaSet*:

```
apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: test-rs
spec:
  replicas: 3
  template:
    metadata:
      labels:
        rel: dev
    spec:
      containers:
      - name: kubia
        image: busybox
```

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

It works fine when `replicasets.spec.selector` is specified:

```
apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: test-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      rel: dev
  template:
    metadata:
      labels:
        rel: dev
    spec:
      containers:
      - name: kubia
        image: busybox
```
