### ISSUE TITLE
Custom ingress default backend is never used

### ISSUE THREAD

**Issue by WesCossick** [kubernetes/minikube#2392]
**Is this a BUG REPORT or FEATURE REQUEST?**: bug report

Please provide the following details:

**Environment**: 
- **Minikube version**: v0.24.1
- **OS**: macOS 10.13.2
- **VM Driver**: hyperkit
- **ISO version**: v0.23.6

**What happened**: Regular default backend is used

**What you expected to happen**: Custom default backend should be used

**How to reproduce it** (as minimally and precisely as possible):

Create an ingress using the Minikube ingress addon, and include the following spec:

```
spec:
  backend:
    serviceName: custom-backend-service
    servicePort: 80
```

(Of course, be sure that the custom backend service exists.)

After running this, you'll see that the typical backend service (simply displays `default backend - 404`) is used instead of the custom one that's defined.

**Comment by WesCossick** [comment]
After further investigation, the default backend only works if there are no other routing rules defined. Here's a full YAML file that replicates the issue:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  backend:
    serviceName: test-service
    servicePort: 80
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: other-service
              servicePort: 80
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: test
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
```

However, the following file works as expected:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  backend:
    serviceName: test-service
    servicePort: 80
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: test
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
```
