### ISSUE TITLE
A pod can't access itself through service IP returned by DNS

### ISSUE THREAD

**Issue by haizaar** [kubernetes/minikube#2460]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

Please provide the following details:

**Environment**:
Linux

**Minikube version** (use `minikube version`):
v0.24.1
- **OS** (e.g. from /etc/os-release):
Ubuntu 16.04.03 amd64

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
minikube-v0.23.6.iso
- **Install tools**:
curl -> save to file
- **Others**:

**What happened**:
I have nginx deployment and and nginx service. Opening shell on a nginx pod and trying to access it through service *hangs*. Trying to access through `localhost` works, access from pods in other deployments works fine as well.

**What you expected to happen**:
Accessing deployment pods through service ClusterIP should work from any pod, like it does on GKE.

**How to reproduce it** (as minimally and precisely as possible):

* Appply the following yaml
```
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.13.8-alpine
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
```
* Trying to connect to itself through svc - **HANGS**
```
$ kubectl exec -ti nginx-deployment-5859cdcc94-4xsqd -- wget nginx
Connecting to nginx (10.110.129.210:80)

```
* Though localhost works
```
$ kubectl exec -ti nginx-deployment-7bccf68b7c-pffpf -- wget localhost
Connecting to localhost (127.0.0.1:80)
index.html           100% |*******************************|   612   0:00:00 ETA
```
* And accessing from other deployment pod works as well
```
$ kubectl run busybox --image=busybox -ti --restart=Never -- wget nginx
Connecting to nginx (10.110.129.210:80)
index.html           100% |*******************************|   612   0:00:00 ETA
```

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
Tried with both localkube and kubeadm bootstrappers.
