### ISSUE TITLE
Difficulty getting kubectl to recognize the correct IP of my minikube cluster

### ISSUE THREAD

**Issue by davidewatson** [kubernetes/minikube#251]
I am probably doing something silly here, but I wondered if anyone has seen this problem. I create a minikube cluster and attempt to run the hello-minikube container, however it attempts to 192.168.99.100:8080 when the cluster was created at 192.168.99.102.

```
rodin:minikube dwat$ ~/bin/minikube start
Starting local Kubernetes cluster...
Kubernetes is available at https://192.168.99.102:443.
Run this command to use the cluster: 
kubectl config use-context minikube
rodin:minikube dwat$ kubectl config set-context minikube
context "minikube" set.
rodin:minikube dwat$ kubectl run hello-minikube --image=gcr.io/google_containers/echoserver:1.4 --hostport=8000 --port=8080
The connection to the server 192.168.99.100:8080 was refused - did you specify the right host or port?
rodin:minikube dwat$ 
```

Looking at my kube config, the correct 192.168.99.102 is specified.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/dwat/.minikube/apiserver.crt
    server: https://192.168.99.102:443
  name: minikube
- cluster:
    server: http://192.168.99.101:8080
  name: test-doc
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
- context:
    cluster: test-doc
    user: ""
  name: test-doc
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/dwat/.minikube/apiserver.crt
    client-key: /Users/dwat/.minikube/apiserver.key
```

Note that I have multiple docker machines and the one named default does have the 192.168.99.100 address:

```rodin:minikube dwat$ docker-machine ls
NAME                    ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default                 -        virtualbox   Running   tcp://192.168.99.100:2376           v1.10.2       
kube-dev                -        virtualbox   Stopped                                       Unknown       
vitalogy                -        amazonec2    Running   tcp://54.218.28.56:2376             v1.11.2       
vitalogy-experimental   -        amazonec2    Running   tcp://54.186.146.56:2376            v1.12.0-rc2   
vs                      -        google       Stopped                                       Unknown       
rodin:minikube dwat$```
