### ISSUE TITLE
Minikube mount doesn't propagate to pods

### ISSUE THREAD

**Issue by RoBorg** [kubernetes/minikube#2530]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

Please provide the following details:

**Minikube version**: v0.25.0
- **OS**: Windows 10
- **VM Driver**: Hyper-v
- **ISO version**: v0.23.6

**What happened**:
When running `minikube mount` after pods have started up, files aren't available in the pods. Files are available after deleting the pods (so they recreate themselves).

**What you expected to happen**:
Files should be available as soon as `minikube mount` is run

**How to reproduce it**:
Create `mount-test.yaml`:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mount-test
  labels:
    name: mount-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mount-test
    spec:
      volumes:
        - name: mount-test-volume
          hostPath:
            path: /projects/mount-test
            type: Directory
      containers:
        - name: mount-test
          image: docker.io/alpine:3.6
          command: ["sleep", "999"]
          volumeMounts:
            - name: mount-test-volume
              mountPath: /mount-test-volume
...
```

Run 
```
minikube ssh sudo mkdir -p /projects/mount-test

# Wait for pods to come up
sleep 60

# Mount the directory
minikube mount -v10 C:\my-project:/projects/mount-test`
```

Finally exec into the pod and run ls /mount-test-volume. Files should be mounted there but aren't.

If the directory doesn't exist on the host prior to the pod starting, it seems the pod won't retry starting up.
Even if does exist, the files still won't be visible until the pod is killed and restarts.
