### ISSUE TITLE
Using apiserver.GenericServerRunOptions.AdmissionControl causes start failure

### ISSUE THREAD

**Issue by judavi** [kubernetes/minikube#2803]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report 

Please provide the following details:

**Environment**: 

**Minikube version** : v0.26.1
- **OS** (e.g. from /etc/os-release): Mac Os High Sierra
- **VM Driver** : virtualbox
- **ISO version** : v0.26.0
- **Install tools**:
- **Others**:

**What happened**:

I have the following setup.

image-review.yml

```
# clusters refers to the remote service.
clusters:
- name: image-review-server
  cluster:
    server: https://requestloggerbin.herokuapp.com/bin/f522cc0e-ef15-414b-9837-2fba6666a3bc

# users refers to the API server's webhook configuration.
users:
- name: kube-apiserver
  user:
    token: blue-token

current-context: webhook

contexts:
  - context:
      cluster: image-review-server
      user: kube-apiserver
    name: webhook
```

admission_controller.json
```
{
  "imagePolicy": {
     "kubeConfigFile": "/Users/judavi/.minikube/files/admission_controller.json/image_review.yml",
     "allowTTL": 50,
     "denyTTL": 50,
     "retryBackoff": 500,
     "defaultAllow": true
  }
}
```

I use the following command to start up minikube
```
minikube start \
  --extra-config=apiserver.GenericServerRunOptions.AdmissionControl=ImagePolicyWebhook \
  --extra-config=apiserver.GenericServerRunOptions.AdmissionControlConfigFile=/Users/judavi/.minikube/files/admission_controller.json
```

But minikube didn't start properly
```
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
```

```
kubectl get pods                                               
The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port?
```
Error:
```
panic: runtime error: slice bounds out of range

goroutine 990 [running]:
bytes.(*Buffer).ReadFrom(0xc42033e690, 0x2df6490, 0xc4209360c0, 0x2df20b0, 0xc42033e690, 0x36029be701)
	/usr/local/go/src/bytes/buffer.go:210 +0x2b4
io.copyBuffer(0x293af60, 0xc42033e690, 0x2df6490, 0xc4209360c0, 0x0, 0x0, 0x0, 0x2046de0, 0xc4207f0000, 0x2df6490)
	/usr/local/go/src/io/io.go:386 +0x2bb
io.Copy(0x293af60, 0xc42033e690, 0x2df6490, 0xc4209360c0, 0xc4209360c0, 0x1f01300, 0xc42036a120)
	/usr/local/go/src/io/io.go:362 +0x68
k8s.io/minikube/vendor/golang.org/x/crypto/ssh.(*Session).stdout.func1(0x0, 0x3000107)
	/go/src/k8s.io/minikube/vendor/golang.org/x/crypto/ssh/session.go:511 +0x85
k8s.io/minikube/vendor/golang.org/x/crypto/ssh.(*Session).start.func1(0xc4205cc120, 0xc4205d0410)
	/go/src/k8s.io/minikube/vendor/golang.org/x/crypto/ssh/session.go:383 +0x27
created by k8s.io/minikube/vendor/golang.org/x/crypto/ssh.(*Session).start
	/go/src/k8s.io/minikube/vendor/golang.org/x/crypto/ssh/session.go:382 +0x121

```

I'm new with Minikube so I will appreciate any help/guidance on how to use the ImagePolicyWebhook

**What you expected to happen**: Minikube will start
