### ISSUE TITLE
registry-creds secrets stored with different name to defaults

### ISSUE THREAD

**Issue by ohookins** [kubernetes/minikube#2805]
**Environment**:

**Minikube version** (use `minikube version`): v0.26.1
- **OS** (e.g. from /etc/os-release): MacOS 10.13.4 High Sierra
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperkit
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.26.0
- **Install tools**: homebrew

**What happened**:
Using private ECR registry images with `registry-creds` addon.

**What you expected to happen**:
Installing and configuring `registry-creds` with valid credentials would allow ECR images to be retrieved by minikube while creating pods.

**How to reproduce it** (as minimally and precisely as possible):
1. `minikube addons configure registry-creds`
2. Configure the credentials with a valid private AWS keypair and ECR registry ID/region.
3. Configure a deployment/replicaset/replicationcontroller/etc with an image located in that private registry.
4. Image fails to download.

**Output of `minikube logs` (if applicable)**:
```
2018-05-11 16:53:17 +0200 CEST   2018-05-11 16:51:41 +0200 CEST   4         user-interface-9789bc6d8-wwjns.152d9ea9f11e04d0    Pod          spec.containers{user-interface}   Warning   Failed                    kubelet, minikube       Failed to pull image "XXXX.dkr.ecr.us-east-1.amazonaws.com/XXXX/XXXX": rpc error: code = Unknown desc = Error response from daemon: Get https://XXXX.dkr.ecr.us-east-1.amazonaws.com/v2/XXXX/XXXX/manifests/latest: no basic auth credentials
```

**Anything else do we need to know**:
* Installing the registry-creds addon causes credentials to be stored in secrets named as follows:
```
$ k get secrets --namespace=kube-system | grep registry-creds                                               17:27:36
registry-creds-dpr                               Opaque                                3         35m
registry-creds-ecr                               Opaque                                6         35m
registry-creds-gcr                               Opaque                                2         35m
```
* According to the [source of registry-creds](https://github.com/upmc-enterprises/registry-creds/blob/5df4d76ffb599379d0fea188de95046858914d13/main.go#L60), the default secret name for AWS credentials in fact `awsecr-cred`
* No configuration seems to be provided to `registry-creds` to override this value, so it is left looking for secrets that don't exist:
```
time="2018-05-11T15:08:27Z" level=error msg="Error getting secret: secrets "awsecr-cred" not found"
2018/05/11 15:08:27 Finished processing secret for namespace default, secret awsecr-cred
time="2018-05-11T15:08:27Z" level=error msg="Error getting secret: secrets "dpr-secret" not found"
2018/05/11 15:08:27 Finished processing secret for namespace default, secret dpr-secret
2018/05/11 15:08:27 Refreshing credentials...
time="2018-05-11T15:08:27Z" level=info msg="------------------ [gcr-secret] ----------------------
"
time="2018-05-11T15:08:27Z" level=info msg="Error getting secret for provider gcr-secret. Skipping secret provider! [Err: google: error getting credentials using well-known file (/root/.config/gcloud/application_default_credentials.json): invalid character 'c' looking for beginning of value]"
```
* Re-storing the secret at the default path appears to work.

**Comment by aaron-prindle** [comment]
The flow for registry-creds is:
`minikube addons configure registry-creds` creates the initial secret
`minikube addons enable registry creds` runs the registry creds addon
can you verify that you also enabled the addon with `minikube addons enable registry creds`

**Comment by ohookins** [comment]
Yes, I ran both of these steps.

**Comment by adampl** [comment]
There is a similar issue with Docker Registry secret on the (currently latest) version 0.28.

Minikube logs:
```
Unable to retrieve pull secret default/docker-hub for default/application-5cd5488b7d-kqh8r due to secrets "docker-hub" not found.  The image pull may not succeed.
```

It's looking for a `docker-hub` secret while it is named `dpr-secret`.

As a workaround, I created a copy of the `dpr-secret` renamed to `docker-hub`.

**Comment by walterdolce** [comment]
The whole "enable private container registry" workflow does not work for me either. 

All I did was to follow the instructions shown [here](https://github.com/kubernetes/minikube/blob/master/docs/insecure_registry.md#private-container-registries). 

Having a deployment with pods with container images from GCR or elsewhere results in an `ErrImagePull` with an internal log of:
```
Failed to pull image "eu.gcr.io/foo/image:1.0.0": rpc error: code = Unknown desc = Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

**Comment by walterdolce** [comment]
It appears that by manually copying the content of my `.docker/config.json` inside the minikube VM at `/home/docker/.dockercfg` solved the problem for me. The content of the `.docker/config.json` for me was:

```
{
  "credHelpers" : {
    "us.gcr.io" : "gcloud",
    "asia.gcr.io" : "gcloud",
    "marketplace.gcr.io" : "gcloud",
    "gcr.io" : "gcloud",
    "eu.gcr.io" : "gcloud",
    "staging-k8s.gcr.io" : "gcloud"
  },
  "stackOrchestrator" : "swarm"
}
```

@aaron-prindle this is not documented [here](https://github.com/kubernetes/minikube/blob/master/docs/insecure_registry.md#private-container-registries), should I add it? Please let me know and I'll send over a PR. Thanks.

**Comment by tstromberg** [comment]
This sounds like an annoying behavior. Help wanted!

**Comment by Conky5** [comment]
To re-copy the secrets with the correct names:

```
kubectl --namespace=kube-system get secret registry-creds-dpr -o yaml \
  | sed 's/registry-creds-dpr/dpr-secret/' \
  | kubectl create -f -
kubectl --namespace=kube-system get secret registry-creds-ecr -o yaml \
  | sed 's/registry-creds-ecr/awsecr-cred/' \
  | kubectl create -f -
kubectl --namespace=kube-system get secret registry-creds-gcr -o yaml \
  | sed 's/registry-creds-gcr/gcr-secret/' \
  | kubectl create -f -
```

**Comment by jmcclell** [comment]
Ran into this today. Some more info for anyone who may feel like tackling this (I might give it a go if I can find some time):

If you look at the generated replication controller manifest for the registry-cred addon, it's clear that the goal is to be able to eschew the registry-cred args all-together and override them via env vars, a la:

```
spec:                                                                                                                                                                                                                                                                         
  containers:                                                                                                                                                                                                                                                                 
  - env:                                                                                                                                                                                                                                                                      
    - name: AWS_ACCESS_KEY_ID                                                                                                                                                                                                                                                 
      valueFrom:                                                                                                                                                                                                                                                              
        secretKeyRef:                                                                                                                                                                                                                                                         
          key: AWS_ACCESS_KEY_ID                                                                                                                                                                                                                                              
          name: registry-creds-ecr                                                                                                                                                                                                                                            
    - name: AWS_SECRET_ACCESS_KEY                                                                                                                                                                                                                                             
     valueFrom:                                                                                                                                                                                                                                                              
        secretKeyRef:                                                                                                                                                                                                                                                         
          key: AWS_SECRET_ACCESS_KEY                                                                                                                                                                                                                                          
          name: registry-creds-ecr                                                                                                                                                                                                                                            
    - name: AWS_SESSION_TOKEN
# ...snip
```
Luckily, registry-creds allows for this!

https://github.com/upmc-enterprises/registry-creds/blob/master/main.go#L350
```
// ...snip
func validateParams() {
	// Allow environment variables to overwrite args
	awsAccountIDEnv := os.Getenv("awsaccount")
	awsRegionEnv := os.Getenv("awsregion")
	argAWSAssumeRoleEnv := os.Getenv("aws_assume_role")
	dprPassword := os.Getenv(dockerPrivateRegistryPasswordKey)
	dprServer := os.Getenv(dockerPrivateRegistryServerKey)
	dprUser := os.Getenv(dockerPrivateRegistryUserKey)
	gcrURLEnv := os.Getenv("gcrurl")
/// ...snip
```

....for *some* parameters. Unfortunately, the AWS access credentials are not included for some odd reason.

It looks like there are 3 options to fix this:

1. The code that generates the configuration can revert to using the configmap names expected by default by registry-cred
2. The code that generates the replication controller can pass in the config map names  as args  to the container
3. registry-cred itself can be updated to allow ENV vars to override the remaining parameters
