### ISSUE TITLE
create ingress but got empty address

### ISSUE THREAD

**Issue by HUANGChaoLi** [kubernetes/minikube#2865]
**BUG REPORT**

**Environment**:

**Minikube version** : v0.27.0
- **OS** : MacOS 10.11.3
- **VM Driver**: virtualbox
- **ISO version** : minikube-v0.26.0.iso
- **Install tools**: curl -Lo minikube ....
- **Others**: none

**What happened**: address field is empty after creating one ingress which exposes the `kubernetes-dashboard` service

**What you expected to happen**: get one address

**How to reproduce it** :
I input the command `minikube addons enable ingress` to enable the ingress addon and create one ingress with yaml file like follow:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-tutorial
  namespace: kube-system
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: dashboard.k8s.me
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 80
```

**Output of `minikube logs` (if applicable)**: 

**Anything else do we need to know**: 
![image](https://user-images.githubusercontent.com/13926164/40877434-4f57fc94-66b3-11e8-8115-6b1acd9623f0.png)

**Comment by diazjf** [comment]
@HUANGChaoLi looks like it may be because of how you defined your ingress resource. `default-http-backend ` is already part of the deployment and is not required in the path.

default-http-backend performs the following:

# 1. It serves a 404 page at /
# 2. It serves 200 on a /healthz endpoint

I tried the below and was able to access the dashboard successfully.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-tutorial
  namespace: kube-system
spec:
  rules:
  - host: dashboard.k8s.me
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 80
```

Also since you are using minikube. Make sure you add the `minikube ip` to `/etc/hosts`.
