### ISSUE TITLE
ingress addon is not properly assigning ip for ingresses on windows

### ISSUE THREAD

**Issue by jguo13** [kubernetes/minikube#2922]
**Minikube version** (use `minikube version`): v0.28.0
- **OS** (e.g. from /etc/os-release): Windows 10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): iso/minikube-v0.28.0.iso
- **Install tools**: chocolatey

**What happened**: After running minikube addons enable ingress, and then kubectl creating an ingress, if you run kubectl get ing the assigned address is 10.0.2.15 and when i add this ip into my /etc/hosts file with the corresponding host, it does not hit my nginx controller running on my minikube

**What you expected to happen**:
The Ingress resource should be assigned the address of the minikube ip address. When I sub in the minikube ip address into the host file instead of the ip that shows up when i run kubectl get ing, then everything works correctly and i can hit the nginx controller on my minikube. When I run these exact same commands on my mac it automatically assigns the ip of the minikube as the address, so i think this is a windows specific issue.

**How to reproduce it** (as minimally and precisely as possible):
on a windows os, run minikube addons enable ingress, and then create and ingress resource and look at the address it gives you.

**Comment by xwlee** [comment]
i face the same issue on Mac

**Comment by jrivera97** [comment]
I'm facing the same issue on Linux Pop!_OS, can you post commands and output of the curl to the minikube ip? I'm hitting the default backend when curling the minikube IP, as expected. However, when I add the path to my ingress, I'm still resulting in 404 not found error.

**Comment by jrivera97** [comment]
The issue for me was stemming from leaving host as a default value. Was able to get around the problem by specifying different host name like in this tutorial https://medium.com/@Oskarr3/setting-up-ingress-on-minikube-6ae825e98f82

**Comment by tkautenburger** [comment]
I am facing the same issue on Mac (minikube v0.28.0). Specifing the host which I did from the beginning did not help. Always get ip address 10.0.2.15 assigned instead of the minikube ip

**Comment by jrivera97** [comment]
Did you add the minikube IP to /etc/hosts? Should be added as <minikube ip> <hostname>. After that I curl http://hostname/ and it worked. Make sure to specify whatever path after the ‘/‘ you specified for the service in the ingress yaml file

**Comment by tkautenburger** [comment]
Yes I did that in /etc/hosts. I suppose the minikube IP should also show up when I do a 

kubectl get services 

after creating the ingress object but it always resolves the hostname to 10.0.2.15 and it takes about a minute after the creation until the IP shows up at the ingress.

Von meinem iPhone gesendet

**Comment by jrivera97** [comment]
Can you post your ingress yaml file, and the output of kubectl describe for the service and the ingress?

**Comment by tkautenburger** [comment]
Sorry for not answering so long, but I had a nice vacation in the south of France. Anyway, the good news is, i got it working, the bad news is, I don't know why. In the meantime i did the following steps:

1. restarted for other reasons my macbook a couple of times
2. upgrading minikube to v0.28.2

Here is my ingress YAML script (the example is from a manning book "Kubernetes in Action"):

`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubia
spec:
  rules:
  - host: myhost.internal
    http: 
      paths:
      - path: /kubia
        backend:
          serviceName: kubia-nodeport
          servicePort: 80`

Here is the referenced backend nodeport service that has via the application selector three pods attached to it:

`apiVersion: v1
kind: Service
metadata:
  name: kubia-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30123
  selector:
    app: kubia`

Here is my host entry in the /etc/hosts file:

`192.168.99.100  myhost.internal`

And now comes the strange thing. When I list the ingress controller with "kubectl get ingress" it still shows the 10.0.2.15 as external IP address:

`NAME      HOSTS             ADDRESS     PORTS     AGE
kubia     myhost.internal   10.0.2.15   80        13m`

But when I curl the ingress controller by its hostname it round robin nicely thru the container apps in my three pods:

`$ curl http://myhost.internal/kubia
You've hit kubia-qcl9t
$ curl http://myhost.internal/kubia
You've hit kubia-7z5mc
$ curl http://myhost.internal/kubia
You've hit kubia-r4pvp
$ curl http://myhost.internal/kubia
You've hit kubia-qcl9t`
 
As I said at the beginning, I have no idea what happened, it did not work before, maybe the update or the reboot did it.

**Comment by elpadrinoIV** [comment]
@tkautenburger using the minikube IP works (that's what you're doing with the /etc/hosts file).
However, the problem still remains, the Ingress controller doesn't get the minikube IP (it gets 10.0.2.15 instead)

**Comment by tkautenburger** [comment]
OK, but why is it then when I do a `curl http://192.168.99.100/kubia`i still get the default backend of the minikube

**Comment by elpadrinoIV** [comment]
Because of this:  - host: myhost.internal`

**Comment by tkautenburger** [comment]
I got it. It's the network configuration of the minikube's virtual box. When I do a `minikube ssh`to log on the virtual machine I see the following:

```
$ ifconfig
eth0      Link encap:Ethernet  HWaddr 08:00:27:77:FA:2F  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe77:fa2f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:92 errors:0 dropped:0 overruns:0 frame:0
          TX packets:89 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:11928 (11.6 KiB)  TX bytes:13054 (12.7 KiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:15:04:B5  
          inet addr:192.168.99.100  Bcast:192.168.99.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe15:4b5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:22 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1180 (1.1 KiB)  TX bytes:2246 (2.1 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:82 errors:0 dropped:0 overruns:0 frame:0
          TX packets:82 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:6220 (6.0 KiB)  TX bytes:6220 (6.0 KiB)
```
The ingress controller takes the IP address of the eth0 interface and that's why it always resolves the external IP to 10.0.2.15. Haven't tried to change the settings of the virtual machine yet.

**Comment by holy12345** [comment]
HI everyone : )
I face the same issues, information below : 

```
kubectl get pods -n ingress-nginx

default-http-backend-5c6d95c48-l47vp        1/1       Running   0          46m
nginx-ingress-controller-6b9b6f7957-sg28z   1/1       Running   0          46m

```

```
kubectl get ing

NAME                      HOSTS     ADDRESS     PORTS     AGE
kubernetes-demo-ingress   *         10.0.2.15   80        5m

```

```
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-service
spec:
  selector:
    app: kubernetes-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-demo-ingress
spec:
  backend:
    serviceName: kubernetes-demo-service
    servicePort: 8080
```

I think if I use `kubectl get ing` it will show me  not internal `IP` (such like `192.168.1.1`) and I use it `curl http://192.168.1.1:8080` can reach my back service. but its show me `10.0.2.15` 
I don't know why : (

thanks

**Comment by tkautenburger** [comment]
Hi holy,

the reason is, that when you installed your minikube, the VM on the virtual box by default gives it two interfaces, eth0 with the IP of 10.0.2.15 and eth1 with the actual IP that the minikube VM has on the internal net, e.g. 192.168.1.1. When you create the ingress, it always takes as the external IP the IP address of eth0 interface, which is 10.0.2.15. 

But when you give your Ingress definition a DNS name for your host, e.g. like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-demo-ingress
spec:
  rules:
  - host: your-host-dns-name.local
    http: 
      paths:
      - path: /
        backend:
          serviceName: kubernetes-demo-service
          servicePort: 8080
```

and put the DNS name that you chose in your /etc/hosts file like this:

``192.168.1.1     your-host-dns-name.local``

you should be able to reach your kubernetes-demo-service via the ingress controller by curling

``http://your-host-dns.name.local/``

from your localhost. Don't wonder, that you can get it via the IP-address, only the host name works, because the ingress still has the wrong IP (10.0.2.15) in its configuration, but does not seem to care much about it.

**Comment by holy12345** [comment]
Hi @tkautenburger  Thank you so much. now I can request `kubernetes-demo-service`

First I am not change `ingress.yaml` and I use `minikube ip` command and it show me the public ip. and I think this  IP is the VM ip(because I use minikube so just one Node and the vm public IP is the ingress public IP ).  and I use this ip + port can reach my back service.

My thought is right?

Thanks again : )

**Comment by tkautenburger** [comment]
Hi holy,

yes that is right. With ``minikube ip``you'll get the minikube's vm ip, 192.168.99.100 typically that is and because you did not specify a host nor a path in your ingress, the ingress resource takes the wildcard (*) and will forward any request to the IP of the minikube vm to your demo service. If you want your ingress resource to forward incoming requests to different services later one, you would have to provide host and path definitions in your ingress definition, like I did. 

With your ingress definition you could for example try to ``curl http://192.168.99.100/any-url-path-will-do/``and it should still hit your demo service, right? That is probably not what you want, at least not for a production service.

**Comment by holy12345** [comment]
@tkautenburger  Thanks again : )

Yeah I want a summary about this, so if I want use `Ingress`  I should those step:

- First(Install Nginx ingress controller )

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml
```

- Second (Enable minikube ingress )
```
minikube addons enable ingress
```

- Third(Customize Ingress.yaml)

```
=======This situation all request  will call kubernetes-demo-service===
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-demo-ingress
spec:
  backend:
    serviceName: kubernetes-demo-service
    servicePort: 8080

=======This situation call the backend service separately===
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-demo-ingress
spec:
  rules:
  - host: ingress.demo.kube
    http:
      paths:
      - path: /serviceA
        backend:
          serviceName: serviceA -- name of service not application
          servicePort: servicePort
      - path: /serviceB
        backend:
          serviceName: serviceA
          servicePort: servicePort
```

Above step is right ? 

Now I will try use `traefik` : )
