### ISSUE TITLE
minikube mount with hostPath volumes: ENOMEM: not enough memory

### ISSUE THREAD

**Issue by Naatan** [kubernetes/minikube#3032]
**Environment**:

**Minikube version**: v0.28.0
- **OS**: Manjaro
- **VM Driver**: tried both kvm2 and virtualbox
- **ISO version**: v0.28.0

**What happened**:

When running `yarn` inside a volume mounted directory it produces the following error:

```
error An unexpected error occurred: "ENOMEM: not enough memory, scandir '/usr/src/app/node_modules'".
```

**What you expected to happen**:

The command does not run into any IO errors.

**How to reproduce it** (as minimally and precisely as possible):

Mount project directory on minikube with:

```
minikube mount `pwd -P`:`pwd -P`
```

Create a container with a volume pointing at the above mount with:

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: project
spec:
  replicas: 1
  template:
    metadata:
      name: project
      labels:
        app: project
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: project
        image: some/imageName
        volumeMounts:
        - mountPath: /usr/src/app
          name: project-volume
      volumes:
      - name: project-volume
        hostPath:
          path: /home/nathanr/.go/src/github.com/org/project/subfolder
```

**Output of `minikube logs` (if applicable)**:

This entry occurs many times which look suspicious:

```
Jul 31 15:29:48 minikube kubelet[2352]: E0731 15:29:48.329717    2352 kubelet_volumes.go:140] Orphaned pod "9a8187cc-94d4-11e8-8501-ec5add0b85c3" found, but volume paths are still present on disk : There were a total of 1 errors similar to this. Turn up verbosity to see them.
```

**Anything else do we need to know**:

Attached output of `minikube mount -v 10 ...`

The issue is not specific to yarn. If I shell into the pod and run an ls on folders I get similar errors.
[minikube-mount.txt](https://github.com/kubernetes/minikube/files/2245986/minikube-mount.txt)

**Comment by Naatan** [comment]
Anyone?

**Comment by tstromberg** [comment]
How many files are in the directory?

I'm still coming up to speed with minikube, but this may be due to limitations with the current 9p driver. 
https://github.com/kubernetes/minikube/issues/3048

**Comment by tstromberg** [comment]
Also, is the error different between kvm2 and virtualbox mounts?

**Comment by massenz** [comment]
I am seeing what is possibly a similar issue with a `minikube mount` where I share a volume with a Docker Registry, ran as a Pod inside the K8s cluster:
```
apiVersion: v1
kind: Pod
metadata:
    name: registry
    labels:
      app: registry

spec:
  containers:
  - image: registry:2
    name: registry
    ports:
    - name: registry
      containerPort: 5000
      protocol: TCP
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - name: repositories
      mountPath: /var/lib/registry

  volumes:
  - name: repositories
    hostPath:
      path: /share/registry
```
in another terminal:
```
minikube mount /data/store/registry:/share/registry
```

**Without** the external mount, this works just fine: I can see the directory being created in the Minikube VM and all push/pull from the registry work just fine.

However, **with** the shared folder (I would like this setup, so container images survive deletes of the minikube VM) a `docker push` causes a `500 Error` and this is what the logs show (several of them):
```
time="2018-09-25T07:10:02Z" level=error msg="response completed with error" err.code=unknown err.detail="filesystem: mkdir /var/lib/registry/docker/registry/v2/blobs/sha256/15/1583e51608ae710b9535f9bd1ddcb3fd93309b6942f3fe18324653719dbba566: input/output error" err.message="unknown error" go.version=go1.7.6 http.request.contenttype="application/vnd.docker.distribution.manifest.v1+prettyjws" http.request.host="192.168.99.101:30500" http.request.id=109a965d-43ba-4cae-ae18-6ec01656add8 http.request.method=PUT http.request.remoteaddr="172.17.0.1:42856" http.request.uri="/v2/serverless/base/manifests/0.5.3" http.request.useragent="docker/17.09.0-ce go/go1.8.3 git-commit/afdb6d4 kernel/4.15.0-34-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.0-ce \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=100.051109ms http.response.status=500 http.response.written=256 instance.id=e85ec90f-83c5-474e-be23-1bf7a799b871 vars.name="serverless/base" vars.reference=0.5.3 version=v2.6.2 
```
The only change is the mounted folder, everything else stays the same.
```
OS: Ubuntu 18.04
Linux gondor 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 minikube version: v0.28.0
```
