### ISSUE TITLE
Could not exec kubectl

### ISSUE THREAD

**Issue by jedipunkz** [kubernetes/minikube#312]
I could not execute kubectl.

My environments are

* kubectl : v1.3.0
* minikube : v0.5.0
* Mac OSX Yosemite
* VirtualBox 5.0.24

'minikube start' command normally finished. when I execute kubectl command, I got error.

```
$ kubectl get pods
error: read /Users/thirai: is a directory
$ kubectl run nginx --image nginx --port=80
error: read /Users/thirai: is a directory
```

My kubectl config is here.

```
kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority: ..
    server: https://192.168.99.101:443
  name: default-cluster
- cluster:
    certificate-authority: /Users/thirai/.minikube/apiserver.crt
    server: https://192.168.99.101:443
  name: minikube
contexts:
- context:
    cluster: default-cluster
    user: default-admin
  name: default-system
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: default-system
kind: Config
preferences: {}
users:
- name: default-admin
  user:
    client-certificate: ..
    client-key: ..
- name: minikube
  user:
    client-certificate: /Users/thirai/.minikube/apiserver.crt
    client-key: /Users/thirai/.minikube/apiserver.key
```

and all of containers for minkube already normally started up.

```
$ docker ps
CONTAINER ID        IMAGE                                                  COMMAND                 CREATED             STATUS              PORTS               NAMES
bf4cda565b2a        gcr.io/google-containers/kube-addon-manager-amd64:v2   "/opt/kube-addons.sh"   18 minutes ago      Up 18 minutes                           k8s_kube-addon-manager.a1c58ca2_kube-addon-manager-minikubevm_kube-system_48abed82af93bb0b941173334110923f_c9fe7c93
701232e1c514        gcr.io/google_containers/pause-amd64:3.0               "/pause"                18 minutes ago      Up 18 minutes                           k8s_POD.d8dbe16c_kube-addon-manager-minikubevm_kube-system_48abed82af93bb0b941173334110923f_807e3619
a1b5b91d4a2f        gcr.io/google_containers/pause-amd64:3.0               "/pause"                18 minutes ago      Up 18 minutes                           k8s_POD.2225036b_kubernetes-dashboard-pzdxy_kube-system_7005dce1-479a-11e6-a0ce-86b669e45864_eee2c513
```
