### ISSUE TITLE
Access to external database?

### ISSUE THREAD

**Issue by dstroot** [kubernetes/minikube#352]
**Retargeting my question**: 

Minikube sets up a local network on your host box so your dev box and minikube can talk to each other.  If I run a container inside minikube that needs access to resources/services **on the internet** (not on the local machine) is there anything special that needs to be done?  Or should it "just work"? 

**More Info**:

Running busybox inside the cluster and using traceroute I see that it stops at 10.0.2.2.  Now I just need to figure out what 10.0.2.2 is and why it stops there.  ;)

```
/ # traceroute 23.99.34.75
traceroute to 23.99.34.75 (23.99.34.75), 30 hops max, 46 byte packets
 1  172.17.0.1 (172.17.0.1)  0.004 ms  0.004 ms  0.001 ms
 2  10.0.2.2 (10.0.2.2)  0.179 ms  0.217 ms  0.183 ms
 3  *  *  *
 4^C
/ #
```

Original Question:

Using Minikube v 6 on OSX.  I have an already containerized app that talks to a database on Azure.  I thought I would just be able to spin up the container inside K8S and have it work, but DNS would only have internal K8S resources, and even if I feed it the external IP it still seems that egress/ingress is causing problems because the app cannot authenticate to the external database.  Can someone point me in the right direction?  

I tried "Services without Selectors" (http://kubernetes.io/docs/user-guide/services/) but no joy...

**Comment by dlorenc** [comment]
Can you explain what you mean by DNS not working? What's the hostname you're trying to resolve?

**Comment by dstroot** [comment]
Thanks for the quick response.  Functionally, I have a SQL database on Azure and a containerized app that updates it.  The app reads environment variables to tell it where to point.  Initially I tried just specifying the IP:

```
        - name: MSSQL_HOST
          value: "23.99.34.75"  #yms0wtdqkl.database.windows.net
        - name: MSSQL_PORT
          value: "1433"
```

Then I tried this approach:

```
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
  - port: 1433
    targetPort: 1433
    protocol: TCP
---
# Because this service has no selector, the corresponding Endpoints
# object will not be created. You can manually map the service to
# your own specific endpoints:
kind: Endpoints
apiVersion: v1
metadata:
  name: database
subsets:
  - addresses:
      - ip: "23.99.34.75"
    ports:
      - port: 1433
```

```
```
        - name: MSSQL_HOST
          value: database  
        - name: MSSQL_PORT
          value: "1433"
```

Whatever I tried so far the app inside K*S has not been able to connect to the database.  I am stumped.  A simple docker compose file that works looks like this:

```
version: '2'

services:
  web:
    image: dstroot/tpg-ttpweb
    container_name: "webserver"
    ports:
      - "80:8000"
    restart: never
    links:
      - redis
    environment:
      MSSQL_HOST: yms0wtdqkl.database.windows.net
      MSSQL_PORT: 1433
      MSSQL_USER: xxxxxxxxx
      MSSQL_PASSWORD: xxxxxxxxxx
      MSSQL_DATABASE: OLTP_SYS
      REDIS_URI: redis
      NODE_ENV: development
      PORT: 8000

  redis:
    image: redis
    container_name: "redis"
    cpu_shares: 50
    cpu_quota: 50000
    mem_limit: 256000000
    memswap_limit: 512000000
    restart: always
```
