### ISSUE TITLE
minikube tunnel should have background mode

### ISSUE THREAD

**Issue by ctcampbell** [kubernetes/minikube#3647]
It would be useful if Minikube tunnel had a background/daemon mode. It would also be nice if it could be started whenever Minikube starts without having to do anything.

**Comment by ajit555db** [comment]
minikube tunnel &> /dev/null &

**Comment by tstromberg** [comment]
I don't know that we need to reinvent our own shell backgrounding process, but perhaps it would be nice to incorporate something so that something like `minikube start --tunnel` might work.

**Comment by priyawadhwa** [comment]
If anybody is interested in implementing `minikube start --tunnel`, please feel free to assign yourself to this issue by commenting `/assign`.

**Comment by medyagh** [comment]
this issue is still open for anyone interested to do this.

**Comment by velvetkeyboard** [comment]
@medyagh Far from being an expert on Go but I think this might be a start #8266

**Comment by medyagh** [comment]
I would accept any PR that adds this feature

**Comment by m-lima** [comment]
> minikube tunnel &> /dev/null &

In general, I don't like this solution because it simply redirects the stdout and stderr and detaches the process; closing the session would still kill the tunnel. Not actually a solution for what OP wanted.
But that's besides the point I'm here to comment about: it seems like when you kill `minikube tunnel` with a `kill -INT` the **ssh forward**s survive the death of the parent process. The signal is captured by **cmd/minikube/cmd/tunnel.go**, but the ssh sessions persist.
I noticed this happening as late as `18e215fed113d3ad1bc1797860e303cae0772373`

**Comment by gtmanfred** [comment]
I would also love this feature.

**Comment by AviMoto** [comment]
+1 to this feature

**Comment by codingluke** [comment]
👍 for this feature!

**Comment by warent** [comment]
yes please! don't let this go stale

**Comment by hongliang5316** [comment]
+1

**Comment by gautambaghel** [comment]
+1

**Comment by warent** [comment]
FYI for anyone wondering I found a way to accomplish something similar and more permanently using loadbalancers.

First, you want to get the IP address to the cluster using `minikube profile list`, and then plug that into your k8s service using the `externalIPs` property, like so:

```
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  type: LoadBalancer
  selector:
    frontend: web
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 3000
      # Port to forward to inside the pod
      targetPort: 3000
      # Port accessible outside cluster
      nodePort: 31000
  externalIPs:
    - 192.168.94.2
```
