### ISSUE TITLE
Minikube Can't Curl IP v0.33.1 / MacOS with Traefik

### ISSUE THREAD

**Issue by patientplatypus** [kubernetes/minikube#3677]
This is a **bug**.

I've attempted to start up minikube and curl the IP that is outputted and get a connection refused: 

```
patientplatypus:~/Documents/HomePage:15:42:29$minikube start
Starting local Kubernetes v1.13.2 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Starting cluster components...
Verifying kubelet health ...
Verifying apiserver health ...
Kubectl is now configured to use the cluster.
Loading cached images from config file.


Everything looks great. Please enjoy minikube!
patientplatypus:~/Documents/HomePage:15:44:37$minikube ip
192.168.99.114
patientplatypus:~/Documents/HomePage:15:44:56$curl $(minikube ip)
curl: (7) Failed to connect to 192.168.99.114 port 80: Connection refused
```

**Comment by afbjorklund** [comment]
What was supposed to listen on port 80 ? The kubernetes master is now using HTTPS (8443)

Normally you don't `curl` to it, but using something like `kubectl` or `dashboard` (or a service)

**Comment by patientplatypus** [comment]
So I am trying to use traefik (see here: https://docs.traefik.io/user-guide/kubernetes/). Basically when I get to the point where I want to curl ${minikube ip} the examples die (most likely as you have said because minikube is now targetting :8443). I've gone ahead and confirmed: 

```
patientplatypus:~/Documents/HomePage:16:55:49$nmap 192.168.99.116 -Pn
Starting Nmap 7.70 ( https://nmap.org ) at 2019-02-14 16:55 CST
Nmap scan report for 192.168.99.116
Host is up (0.0029s latency).
Not shown: 996 filtered ports
PORT     STATE SERVICE
22/tcp   open  ssh
111/tcp  open  rpcbind
2049/tcp open  nfs
8443/tcp open  https-alt

Nmap done: 1 IP address (1 host up) scanned in 5.93 seconds
```

However, going through and changing the ports in the example files from 80 to 8443 doesn't allow them to work. I'm going to file a bug report over there if this is now how minikube is supposed to work.

**Comment by patientplatypus** [comment]
OK...I have to admit that at this point I'm lost. I want to create an Ingress controller and there are no examples that I can find that don't use port 80. Here is another one: https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md. If I change the file https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/deployment/nginx-ingress.yaml from having the lines:

```
spec:
      serviceAccountName: nginx-ingress
      containers:
      - image: nginx/nginx-ingress:edge
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - name: http
           containerPort: 80
        - name: https
          containerPort: 443
```

to having the lines 

```
spec:
      serviceAccountName: nginx-ingress
      containers:
      - image: nginx/nginx-ingress:edge
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - name: https
          containerPort: 8443
```

Then I get crashes and loopback errors. As I haven't configured an ingress controller before, and all examples that use port 80 appear to be broken and I can't seem to fix them using the new https port 8443, I'm stuck. This change in minikube seems to have caused a breaking change to everything that used to use it. 

Is there an example of an Ingress controller that works using only port 8443?
