### ISSUE TITLE
VirtualBox: Resolving MX/NS records returns NOTIMP/NXDOMAIN

### ISSUE THREAD

**Issue by mengzhen94** [kubernetes/minikube#3725]
Hi,
I am setting SMTP docker image with kubernetes and minikube. When sending emails, it returns an error:
```
R=dnslookup defer (-1): host lookup did not complete
smtp_connection MAIN
SMTP connection from xxx.default.svc.cluster.local  lost
```
Also, when I run `nslookup -type=MX gmail.com` inside the docker, it returns `** server can't find gmail.com: NOTIMP` which is wired. It looks like it cannot reach external mailer exchange DNS.

Am I missing any configuration or does anyone have any idea?
Thanks.

**Comment by tstromberg** [comment]
Hello @mengzhen94 - sorry to hear that things aren't working. To help you, could you include:

- How to replicate the error, including the exact command-lines used to start minikube and start your docker container
- The version of minikube used
- The operating system name and version used

Also, the output of `minikube logs` from minikube v0.34 or newer, specifically the CoreDNS portion of it, would be very handy here.

**Comment by mengzhen94** [comment]
Thanks for your reply.
- How to replicate:
I am using namshi/smtp docker image with
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-deployment
  labels:
    app: smtp-app
spec:
  selector:
    matchLabels:
      app: smtp-app
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: smtp-app
    spec:
      restartPolicy: Always
      containers:
        - name: smtp-container
          image: namshi/smtp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 25
```
and 
```
apiVersion: v1
kind: Service
metadata:
  name: smtp-service
  labels:
    app: smtp-app
spec:
  selector:
    app: smtp-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 25
      targetPort: 25
      nodePort: xxx
```
To start minikube, I first install minikube and build docker images with `docker build` and  do `minikube start --kubernetes-version v1.11.5` and `minikube addons enable ingress`

- Minikube version: : v0.33.1
- OS: Ubuntu 18.04.2

Hope that helps you. Thanks
