### ISSUE TITLE
LoadBalancer support

### ISSUE THREAD

**Issue by waprin** [kubernetes/minikube#384]
Trying to understand where this is on the roadmap. I understand it's currently not supported but is there opposition to adding it? 

Currently a lot of Kubernetes examples uses LoadBalancer. Sure, easy to replace with NodePort, but it would be ideal if we could run those with no modifications on minikube. 

Since LoadBalancer is already "cloud dependent", Minikube could likewise just make its own decision, which could be  something simple (nginx, mapping to nodeport somehow, etc). Of course it will evolve over time, add Ingress support etc but this is the one feature that would enable a lot of the getting started examples to work:

Getting started examples that use LoadBalancer and not much else: 

https://github.com/kubernetes/kubernetes/blob/master/examples/guestbook/frontend-service.yaml

https://github.com/GoogleCloudPlatform/getting-started-python/blob/master/optional-container-engine/bookshelf-service.yaml

http://www.thagomizer.com/blog/2015/07/01/kubernetes-and-deploying-to-google-container-engine.html

**Comment by jimmidyson** [comment]
LoadBalancer services run fine on minikube, just with no real external load balancer created. LoadBalancer services get a node port assigned too so you can access services via `minikube service <name>` to open browser or add `--url` flag to output service URL to terminal.

Would that cover what you need or is there something more that you'd like to see?

**Comment by waprin** [comment]
Ah I didn't know about that feature, cool thanks.

**Comment by whitecolor** [comment]
Why not support that minikube could give some address form internal pool that could be accessible from dev machine?

**Comment by bryanerayner** [comment]
Could the getting started examples be updated to include @jimmidyson 's comment? It would be tremendously helpful if this information were easier to find.

**Comment by r2d4** [comment]
@bryanerayner PRs are always welcome

**Comment by tony-kerz** [comment]
i'm running something like:
```
apiVersion: v1
kind: Service
metadata:
  name: my-ftp
spec:
  ports:
  - port: 22
  selector:
    app: my-ftp
  type: LoadBalancer
```
but minikube seems to be having an issue exposing the service:
```
⋊> kubectl get svc my-ftp                                                      
NAME      CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
my-ftp   10.0.0.47    <pending>     22:31253/TCP   5m
```
i can access the service via the internal port 31253, but not the exposed 22...?
is this just the expected behavior with `LoadBalancer`...?

> i'm running mk `v0.18.0`/osx/virtualbox

**Comment by jasonkuhrt** [comment]
I think I'm having the same issue as @tony-kerz:

```
apiVersion: v1
kind: Service
metadata:
  name: db-alexa
  labels:
    app: db-alexa
spec:
  type: LoadBalancer
  selector:
    app: db-alexa
  ports:
    - name: ui
      port: 80
      targetPort: ui
    - name: ui-default
      port: 8080
      targetPort: ui
    - name: client
      port: 9080
      targetPort: client
```
```
❯ minikube service db-alexa
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
```
