### ISSUE TITLE
--apiserver-name has no effect on ~/.kube/config

### ISSUE THREAD

**Issue by aparamon** [kubernetes/minikube#3878]
To reproduce:
````console
powtest@chlorine:~$ minikube version
minikube version: v0.35.0
````console
powtest@chlorine:~$ sudo -E minikube start --vm-driver=none --apiserver-name=chlorine.acdlabs.ru
````
File `~/.kube/config` is populated with
````yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <skip>
    server: https://82.97.201.217:8443
  name: minikube
````
Cluster is created successfully:
````console
powtest@chlorine:~$ kubectl cluster-info
Kubernetes master is running at https://82.97.201.217:8443
KubeDNS is running at https://82.97.201.217:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
````
However it's expected that `server` is https://chlorine.acdlabs.ru:8443. It works if modifying generated `~/.kube/config` manually:
````console
powtest@chlorine:~$ kubectl cluster-info
Kubernetes master is running at https://chlorine.acdlabs.ru:8443
KubeDNS is running at https://chlorine.acdlabs.ru:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
````
