### ISSUE TITLE
bypassing aufs storage overhead

### ISSUE THREAD

**Issue by andrewgdavis** [kubernetes/minikube#419]
Is there an equivalent persistent volume type in kubernetes to the use of docker `- -volumes-from`?

What I currently see is that the use of "--volumes-from my-persistent-stopped-data-container" is superior to the use of "-v /Users/foo/dir:/tmp" due to a significant performance impact that I think is caused from the following:

> One final point. Data volumes provide the best and most predictable performance. This is because they bypass the storage driver and do not incur any of the potential overheads introduced by thin provisioning and copy-on-write. For this reason, you may want to place heavy write workloads on data volumes.

Which is quoted at the very bottom of https://docs.docker.com/engine/userguide/storagedriver/aufs-driver/

Here is an example of this performance impact.

```
# with -v
docker run -it -v /Users/foo/maven-repo:/maven-repo busybox sh
cd /maven-repo
time du -sh *
253.6M  repository
8.0K    settings.xml
500.0K  test_host1.img
real    0m 5.85s
user    0m 0.00s
sys 0m 2.14s
```

vs:

```
# with --volumes-from
docker run -it --volumes-from maven-repo busybox sh
cd  /maven-repo
time du -sh *
435.4M  repository
8.0K    settings.xml
500.0K  test_host1.img
real    0m 0.04s
user    0m 0.01s
sys 0m 0.03s
```

Where maven-repo is a data-container with a declared `VOLUME /maven-repo` that actually has more content (435.4M) than the host mounted volume (253.6M).

The above is purely docker, but the slow performance is also exhibited when i tried creating a PersistentVolume 

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-mvn-repo
  labels:
    name: local-mvn-repo
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    # volume can be mounted read/write by many nodes
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/Users/foo/maven-repo"
```

So i suppose the ask is:  what is the equivalent way in kubernetes to " bypass the storage driver and do not incur any of the potential overheads" for persistent storage?  Or perhaps is emptyDir (backed byramfs?) and multiple containers in a pod the correct workaround?

Relevant docker thread on the issue: 
https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/102

Relevant stackoverflow thread:  (but doesn't talk about persistence which is what is neeeded...)
http://stackoverflow.com/questions/30538210/how-to-mimic-volumes-from-in-kubernetes
