### ISSUE TITLE
Inconsistent image pull behavior: ElasticSearch ImagePullBackOff

### ISSUE THREAD

**Issue by staticdev** [kubernetes/minikube#4200]
I am running minikube 1.0.1 on Ubuntu 19.04 using kvm2. Before the upgrade from 1.0.0 to 1.0.1 I had to `docker pull` all the images before deploying with `kubectl create`. Now some of the images can be pulled, some cannot.

Example deployment with two images (mongo and elasticsearch):
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-claim0
      restartPolicy: Always
      volumes:
      - name: mongo-claim0
        persistentVolumeClaim:
          claimName: mongo-claim0
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      initContainers:
      - name: set-vm-max-map-count
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true
      containers:
      - env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: cluster.name
          value: log
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
        name: elasticsearch
        ports:
        - containerPort: 9200
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: esdata
      restartPolicy: Always
      volumes:
      - name: esdata
        persistentVolumeClaim:
          claimName: esdata
status: {}
```
Mongo works fine, while ES gives “ImagePullBackOff". For a consistent behavior, or a pull would be needed for both, or none.

```
docker pull docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
docker pull mongo:4.0
```
