### ISSUE TITLE
fsGroup permissions are not applied when using the gitRepo plugin

### ISSUE THREAD

**Issue by andrewgdavis** [kubernetes/minikube#482]
Minimal test case:

bad-perm.yaml:
```
kind: Pod
apiVersion: v1
metadata:
  name: bad-perm
  labels:
    app: bad-perm
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  containers:
  - name: run
    image: busybox
    imagePullPolicy: "IfNotPresent"
    command: [ "sh", "-c", "cat /etc/passwd && ls -la / && whoami" ]
    volumeMounts:
    - name: repo
      mountPath: /repo
    - name: test
      mountPath: /empty
  volumes:
    - name: test
      emptyDir: {}
    - name: repo
      gitRepo:
        repository: "https://github.com/kubernetes/minikube.git"
```

output:
```
kubectl logs -f bad-perm
root:x:0:0:root:/root:/bin/sh
daemon:x:1:1:daemon:/usr/sbin:/bin/false
bin:x:2:2:bin:/bin:/bin/false
sys:x:3:3:sys:/dev:/bin/false
sync:x:4:100:sync:/bin:/bin/sync
mail:x:8:8:mail:/var/spool/mail:/bin/false
www-data:x:33:33:www-data:/var/www:/bin/false
operator:x:37:37:Operator:/var:/bin/false
nobody:x:99:99:nobody:/home:/bin/false
total 44
drwxr-xr-x   21 root     root          4096 Aug 12 20:43 .
drwxr-xr-x   21 root     root          4096 Aug 12 20:43 ..
-rwxr-xr-x    1 root     root             0 Aug 12 20:43 .dockerenv
drwxr-xr-x    2 root     root         12288 Jun 23 20:13 bin
drwxr-xr-x    5 root     root           380 Aug 12 20:43 dev
drwxrwsrwx    2 root     1000            40 Aug 12 20:41 empty <---- Good perms on EmpyDir
drwxr-xr-x    2 root     root          4096 Aug 12 20:43 etc
drwxr-xr-x    2 nobody   nogroup       4096 Jun 23 20:13 home
dr-xr-xr-x  168 root     root             0 Aug 12 20:43 proc
drwxrwxrwx    3 root     root            60 Aug 12 20:41 repo <---- Not applied :(
drwxr-xr-x    2 root     root          4096 Jun 23 20:13 root
dr-xr-xr-x   13 root     root             0 Aug 12 20:40 sys
drwxrwxrwt    2 root     root          4096 Jun 23 20:13 tmp
drwxr-xr-x    3 root     root          4096 Jun 23 20:13 usr
drwxr-xr-x    5 root     root          4096 Aug 12 20:43 var
whoami: unknown uid 1000
```

system details:
minikube version: v0.7.1
Darwin Kernel Version 15.3.0

This PR was merged, so the functionality is there:
https://github.com/kubernetes/kubernetes/pull/22995/files
