### ISSUE TITLE
No watch events are generated using minikube

### ISSUE THREAD

**Issue by dcheese** [kubernetes/minikube#489]
When using minikube, we are not able receive pod change events when providing the watch parameter. It just hangs, with no response. It does work when we try try to curl against a full kubernetes server/installation.

> kubctl proxy &
> curl http://localhost:8001/api/v1/pods?watch=true

Is there something we need configure with minikube to get this to work?

**Comment by dlorenc** [comment]
Hmm, this worked for me:

In one terminal:
`$ kubectl proxy`

In another:
`$ curl http://localhost:8001/api/v1/pods?watch=true`

Then in a third:
`$ kubectl create -f busybox.yaml`

Where busybox.yaml is:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: gcr.io/dlorenc-vmtest4/foo
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  imagePullSecrets:
  - name: secret.json
  restartPolicy: Always
```

I see output in the curl terminal.

So this should work out of the box in minikube. Do you see anything running in Minikube with kubectl get pods --all-namespaces?
