### ISSUE TITLE
How to mount host directory with executable permissions

### ISSUE THREAD

**Issue by kickthemooon** [kubernetes/minikube#4899]
`minikube mount --ip 192.168.99.1 c://host//directory:/home/minikube/vm/directory`

```
* Mount options:
  - Type:     9p
  - UID:      docker
  - GID:      docker
  - Version:  9p2000.L
  - MSize:    262144
  - Mode:     755 (-rwxr-xr-x)
  - Options:  map[]
* Userspace file server: ufs starting
* Successfully mounted c://host//directory to /home/minikube/vm/directory

* NOTE: This process must stay alive for the mount to be accessible ...
```

OS: Windows 10
minikube version: v1.2.0
VM-Driver: virtualbox

Unfortunately all the files mounted are not executable 
`-rw-rw-rw- 1 docker docker   4128 Jul 23 05:52 Dockerfile`

When mounted in a pod:
```
containers:
  - name: nginx
    image: nginx-image
    ports:
      - containerPort: 80
    volumeMounts:
      - name: hostdir
        mountPath: /app
  - name: fpm
    image: php-image
    args:
      - php-fpm
    ports:
      - containerPort: 9000
    volumeMounts:
      - name: hostdir
        mountPath: /app
volumes:
  - name: hostdir
    hostPath:
      path: /home/minikube/vm/directory
```

None of the files are executable.

How to mount host directory allowing minikube and pods to execute files?
