### ISSUE TITLE
Pods can't find cached images in minikube with containerd

### ISSUE THREAD

**Issue by priyawadhwa** [kubernetes/minikube#4985]
Caching images doesn't work with the containerd backend, instead pods will always try to pull images from a remote registry even if they exist locally.

To reproduce, copy these files into a directory:

**Dockerfile**
```
FROM busybox
CMD sleep 6000
```
**pod.yaml**
```
apiVersion: v1
kind: Pod
metadata:
  name: cache-bug
  namespace: default
spec:
  containers:
  - name: cache-bug
    image: gcr.io/k8s-minikube/cache-bug
    imagePullPolicy: IfNotPresent
```

1. Build minikube from my branch (#4717), since I added support for caching local images on `minikube cache add` there
1. Run `docker build -t gcr.io/k8s-minikube/cache-bug .`
1. `minikube start --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock --logtostderr`
1. `minikube cache add gcr.io/k8s-minikube/cache-bug`
1. `minikube ssh -- sudo ctr images ls | grep cache-bug` should show that the image exists within Minikube
1. `kubectl apply -f pod.yaml`
1. `kubectl get pod cache-bug` should show status `ImagePullBackOff` instead of `Running` because the pod is trying to get the remote image which doesn't exist, even though the image exists locally.

The above steps with the docker runtime work as expected, with the pod having status `Running` after a few seconds.
