### ISSUE TITLE
adapt generated kubeconfig to use relative paths instead of absolute paths

### ISSUE THREAD

**Issue by hacker-h** [kubernetes/minikube#5187]
It would be great if the generated kubeconfig would not include absolute paths, but relative ones instead:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: ../.minikube/ca.crt
    server: https://172.17.17.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: ../.minikube/client.crt
    client-key: ../.minikube/client.key
```
This way all command line tools work the same for me and I can easily use the same kubeconfig inside docker containers.
