### ISSUE TITLE
Could dashboard addons service type default to be NodePort

### ISSUE THREAD

**Issue by unlikezy** [kubernetes/minikube#5267]
After dashboard is enabled, we still need to run `minikube dashboard` or `kubectl port-forward` to make dashboard accessible.
Modify dashboard service to use NodePort by applying this yaml:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"kubernetes-dashboard","kubernetes.io/minikube-addons":"dashboard","kubernetes.io/minikube-addons-endpoint":"dashboard"},"name":"kubernetes-dashboard","namespace":"kube-system"},"spec":{"ports":[{"port":80,"targetPort":9090}],"selector":{"app":"kubernetes-dashboard"}}}
  creationTimestamp: "2019-08-30T03:02:39Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: kubernetes-dashboard
    kubernetes.io/minikube-addons: dashboard
    kubernetes.io/minikube-addons-endpoint: dashboard
  name: kubernetes-dashboard
  namespace: kube-system
  selfLink: /api/v1/namespaces/kube-system/services/kubernetes-dashboard
spec:
  type: NodePort
  ports:
  - name: http
    port: 9090
  selector:
    app: kubernetes-dashboard
  sessionAffinity: None
```
will make dashboard accessible through fixed url/port, which could be checked by this
```
$minikube service list
|-------------|----------------------|-----------------------------|
|  NAMESPACE  |         NAME         |             URL             |
|-------------|----------------------|-----------------------------|
| kube-system | kube-dns             | No node port                |
| kube-system | kubernetes-dashboard | http://192.168.99.106:32300 |
| kube-system | tiller-deploy        | No node port                |
|-------------|----------------------|-----------------------------|
```
Could this be made default to dashboard addons?
Or 
is this not done because of security concern?
