### ISSUE TITLE
/data mount is not working on minikube

### ISSUE THREAD

**Issue by alexwang66** [kubernetes/minikube#5535]
**The exact command to reproduce the issue**:
kubectl create -f jenkins.yaml 

* 1. Environment: Minikube v1.2.0, on Mac with VirtualBox.
* 2. create pod, pv and pvc as in below jenkins.yaml

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data
```
```

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```
```

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      containers:
        - name: jenkins
          image: jenkins:2.3-alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-home
              mountPath: "/var/jenkins_home"
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pv-claim # must match the claim name from above
```
```

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-server
  namespace: default
  labels:
    app: jenkins-server
spec:
  ports:
    - name: port1
      protocol: TCP
      port: 8080
      nodePort: 31081
  selector:
    app: jenkins-server
  type: NodePort
```

* 3. exec:  kubectl create -f jenkins.yaml 

**The full output of the command that failed**:<details>
Here is the logs of executing minikube logs:

`Error watching for provisioning success, can't provision for claim "default/jenkins-pv-claim": events is forbidden: User "system:serviceaccount:kube-system:storage-provisioner" cannot list resource "events" in API group "" in the namespace "default"
`

</details>

**The output of the `minikube logs` command**:<details>
The pod can be started successfully but the PV is not mounted.

There is not data under /data on the minikube's vm, the default mount (mentioned in [here](https://minikube.sigs.k8s.io/docs/reference/persistent_volumes/)) is not working.  I've tried minikube mount $HOME:/hosthome but not working.

</details>

**The operating system version**:
Environment: Minikube v1.2.0, on Mac with VirtualBox.
