### ISSUE TITLE
Cannot ping ClusterIP of the service from the cluster.

### ISSUE THREAD

**Issue by Zerxoi** [kubernetes/minikube#5644]
I want to access to the pod through its service, and i have tried to `ping` the ClusterIP through `minikube ssh` in master, but not work.

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
```

**The exact command to reproduce the issue**:
```
❯ kubectl get svc
NAME             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
kubernetes       ClusterIP   10.96.0.1        <none>        443/TCP                      6h29m
nginx            ClusterIP   10.97.255.240    <none>        80/TCP                       10m

❯ minikube ssh
$ ping 10.97.255.240
PING 10.97.255.240 (10.97.255.240): 56 data bytes
^C
--- 10.97.255.240 ping statistics ---
10 packets transmitted, 0 packets received, 100% packet loss
```
but i can access pod through `curl`.
```
$ curl 10.97.255.240
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**The operating system version**:
```
Linux ArchLinux 5.3.6-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 11 18:28:05 UTC 2019 x86_64 GNU/Linux
```
