### ISSUE TITLE
release_update_brew: access_token: unbound variable

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5779]
minikube migrated from cask to brew, but the automation has not been updated to use `bump-formula-pr.rb` to trigger updates: https://github.com/Linuxbrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request.md

Here is where the automation should go:

https://github.com/kubernetes/minikube/blob/9be404689b6860f189147bb53050b6f09a15681a/hack/jenkins/release_update_brew.sh#L43

**Comment by commitay** [comment]
@tstromberg I'd suggest using the Homebrew formula update command (via GitHub Actions) instead of updating the current script.

A token for the bot would need to be added in https://github.com/kubernetes/minikube/settings/secrets

If this is okay I'll send a PR.

```yml
name: brew formula update

on:
  push:
    tags: 'v*'

jobs:
  update:
    runs-on: macOS-latest
    steps:
      - name: bump formula
        if: "!contains(github.ref, '-')" # skip beta
        env:
          HOMEBREW_DEVELOPER: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
          BOT_NAME: "minikube-bot"
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BOT_PUBLIC_REPO_TOKEN }}
        run: |
          git config --global user.name "$BOT_NAME"
          git config --global user.email "$BOT_NAME"@google.com
          brew update-reset "$(brew --repo)"
          CORE_REPO="$(brew --repo homebrew/core)"
          brew update-reset "$CORE_REPO"
          git -C "$CORE_REPO" remote add "$BOT_NAME" \
            https://"$BOT_NAME":"$HOMEBREW_GITHUB_API_TOKEN"@github.com/"$BOT_NAME"/homebrew-core.git
          brew bump-formula-pr \
            --no-audit \
            --no-browse \
            --tag="${{ github.ref }}" \
            --revision="${{ github.sha }}" \
            --message="cc @balopat"
            minikube
```
