### ISSUE TITLE
Unable to parse "": Version string empty error

### ISSUE THREAD

**Issue by galderz** [kubernetes/minikube#6291]
Minikube 1.6.2 fails to start:

```
$ minikube start
😄  [operator-minikube] minikube v1.6.2 on Darwin 10.15.1
    ▪ MINIKUBE_HOME=/opt/minikube
✨  Selecting 'virtualbox' driver from user configuration (alternates: [hyperkit])
💣  Unable to parse "": Version string empty
```

Having set this config:

```
+ PROFILE=operator-minikube
+ VMDRIVER=virtualbox
+ minikube profile operator-minikube
❌  open /opt/minikube/.minikube/profiles: no such file or directory
❌  profile "operator-minikube" not found
✅  Created a new profile : operator-minikube
✅  minikube profile was successfully set to operator-minikube
+ minikube config set memory 4096
⚠️  These changes will take effect upon a minikube delete and then a minikube start
+ minikube config set cpus 4
⚠️  These changes will take effect upon a minikube delete and then a minikube start
+ minikube config set disk-size 10GB
⚠️  These changes will take effect upon a minikube delete and then a minikube start
+ [[ -n virtualbox ]]
+ echo 'Using VM driver '\''virtualbox'\'''
Using VM driver 'virtualbox'
+ minikube config set vm-driver virtualbox
⚠️  These changes will take effect upon a minikube delete and then a minikube start
```

I've worked around by specifying the kubernetes version:

```
$ minikube start --kubernetes-version=v1.17.0
😄  [operator-minikube] minikube v1.6.2 on Darwin 10.15.1
    ▪ MINIKUBE_HOME=/opt/minikube
✨  Selecting 'virtualbox' driver from user configuration (alternates: [hyperkit])
💿  Downloading VM boot image ...
```

**Comment by afbjorklund** [comment]
Think it needs more verbose logs, to show _which_ version did not parse.

**Comment by afbjorklund** [comment]
Well, seems to duplicate easilly at least:

```console
$ minikube profile operator-minikube
❌  profile "operator-minikube" not found
✅  Created a new profile : operator-minikube
✅  minikube profile was successfully set to operator-minikube
$ minikube start
😄  [operator-minikube] minikube v1.6.2 on Ubuntu 16.04
✨  Selecting 'virtualbox' driver from user configuration (alternates: [kvm2 none])
💣  Unable to parse "": Version string empty
```

**Comment by afbjorklund** [comment]
It is the kubernetes version from your newly created profile, that doesn't parse.

```json
    "KubernetesConfig": {
        "KubernetesVersion": "",
        "NodeIP": "",
        "NodePort": 0,
        "NodeName": "",
        "APIServerName": "",
        "APIServerNames": null,
        "APIServerIPs": null,
        "DNSDomain": "",
        "ContainerRuntime": "",
        "CRISocket": "",
        "NetworkPlugin": "",
        "FeatureGates": "",
        "ServiceCIDR": "",
        "ImageRepository": "",
        "ExtraOptions": null,
        "ShouldLoadCachedImages": false,
        "EnableDefaultCNI": false
    },
```

Most likely it should have fallen back to the default kubernetes version instead.

**Comment by afbjorklund** [comment]
Once it got past the initial parsing, the rest of the values seem to fill out fine:

```yaml
    "KubernetesConfig": {
        "KubernetesVersion": "v1.17.0",
        "NodeIP": "192.168.99.100",
        "NodePort": 8443,
        "NodeName": "minikube",
        "APIServerName": "minikubeCA",
        "APIServerNames": null,
        "APIServerIPs": null,
        "DNSDomain": "cluster.local",
        "ContainerRuntime": "docker",
        "CRISocket": "",
        "NetworkPlugin": "",
        "FeatureGates": "",
        "ServiceCIDR": "10.96.0.0/12",
        "ImageRepository": "",
        "ExtraOptions": null,
        "ShouldLoadCachedImages": true,
        "EnableDefaultCNI": false
    },

```
