### ISSUE TITLE
Configure port exposed on host for NodePort services

### ISSUE THREAD

**Issue by bglusman** [kubernetes/minikube#642]
Perhaps I just can't find this documented and there's already a way to configure this, but I have a svc with config as below:
```
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: connect-web
  type: NodePort
```
It's working fine, but the port that is exposed on the host machine as shown by `minikube service --url web-svc` appears to be randomly generated, and I can't find a way to make it consistent across minikube environments on different machines, or across `minikube delete && minikube start` teardowns on the same machine.  I've got some hacky solutions in place, but this port needs to be able to be known inside configmaps for the application, so I basically have to create it, check the port, destroy it and recreate it with modified config to automate a working install on a new machine, and it would be so much simpler if I could just add another piece of configuration to the above service like, say, `externalPort: 8888` or even just using the actual port specified already, though I suppose that might be a breaking change.  Appreciate any suggestions or if this would be a new feature, appreciate anyone tackling (or perhaps I can help tackle it if someone can point me to the right part of the code base, but not even using from source at present)
