### ISSUE TITLE
latest storage-provisioner: cannot get resource "endpoints" in API group "" in the namespace "kube-system"

### ISSUE THREAD

**Issue by tolusha** [kubernetes/minikube#6523]
Not sure, but it seems related to https://github.com/kubernetes/minikube/pull/6511/files

**The exact command to reproduce the issue**:
```bash
minikube start
kubectl create namespace test
kubectl apply -f pvc.yaml
```

**The full output of the command that failed**:<details>
storage provisioner logs:
```
E0206 10:46:39.353949       1 leaderelection.go:331] error retrieving resource lock kube-system/k8s.io-minikube-hostpath: endpoints "k8s.io-minikube-hostpath" is forbidden: User "system:serviceaccount:kube-system:storage-provisioner" cannot get resource "endpoints" in API group "" in the namespace "kube-system
```

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

```bash
minikube version
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty
```

```bash
cat /etc/os-release 
NAME="Linux Mint"
VERSION="19.3 (Tricia)"
```

`pvc.yaml`:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
