### ISSUE TITLE
Not all service ports are exposed via minikube service command

### ISSUE THREAD

**Issue by crimeminister** [kubernetes/minikube#659]
BUG REPORT

**Minikube version**

```
v0.10.0
```

**Environment**:
- **OS** (e.g. from /etc/os-release):

```
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
```
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):

```
kvm
```
- **Docker version**

```
Docker version 1.12.1, build 23cf638
```

**What happened**:

After creating a service that exposes multiple ports, I am only able to access the service via a single IP:port discovered using `minikube service --url <service name>`. It seems as though only the first port listed by the service is mapped.

**What you expected to happen**:

Ideally I would get back a list IP:port pairs, one per exposed service port.

**How to reproduce it**:
Create a service that exposes multiple ports:

```
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: NodePort
  ports:
  - name: foo
    port: 8080
    targetPort: foo-port
    protocol: TCP
  - name: bar
    port: 8090
    targetPort: bar-port
    protocol: TCP
  selector:
    app: example
```

Run `minikube service --url`.

**Anything else do we need to know**:
