### ISSUE TITLE
add APIServer endpoint to `minikube profile list` 

### ISSUE THREAD

**Issue by balopat** [kubernetes/minikube#6642]
For Skaffold (https://github.com/GoogleContainerTools/skaffold/issues/3668) we know the current context. That context has an API server endpoint: 
````
- cluster:
    certificate-authority: /Users/.../.minikube/ca.crt
    server: https://127.0.0.1:32777
  name: docker3
````

**I want to be able to join my API Server endpoint to a minikube profile.** 

Currently this is not possible for the Docker driver, as the Node spec contains the node IP not the API Server endpoint:

```
....
 "Nodes": [
          {
            "Name": "docker3",
            "IP": "172.17.0.4",
            "Port": 8443,
            "KubernetesVersion": "v1.17.2",
            "ControlPlane": true,
            "Worker": true
          }
...
```

Can we add a cluster-wide property, `APIServer` to the json listing?

**Comment by medyagh** [comment]
@balopat that is a good idea ! we could add a field, 
"ApiserverEndpoint"
in VM world they used to be the same, but in docker/podman driver it is a different story.

We could do that.

**Comment by tharun208** [comment]
@medyagh , I like to work on this

**Comment by briandealwis** [comment]
An alternative is to add the profile name to the context and cluster extensions as Minikube is now doing with `cluster_info`:
```
- cluster:
    certificate-authority: /Users/bdealwis/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Mon, 22 Mar 2021 21:45:57 EDT
        provider: minikube.sigs.k8s.io
        version: v1.18.1
      name: cluster_info
    server: https://127.0.0.1:61837
  name: containerd
```

Then the minikube instance could remain blissfully ignorant of how its endpoints are exposed to the host environment.
