### ISSUE TITLE
Default host path provisioner storage class

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/minikube#685]
On minikube have a default host path provisioner storage class will allow apps to be deployed with PVCs & have volumes dynamically created by the host path provisioner. I have tested this all out & it works well, but I'm wondering if it makes sense to have a default host path provisioner? IMO it does, as there are no other types of dynamic provisioner that make sense for minikube.

**Comment by jimmidyson** [comment]
Would have liked to add this via an addon but seems like addon-manager doesn't support StorageClass kinds.

Any thoughts @dlorenc @r2d4?

**Comment by dlorenc** [comment]
Hmm, how hard would it be to add support for StorageClass to the addon-manager? This PR makes it look relatively easy: https://github.com/kubernetes/kubernetes/commit/2a589b09637aa3745a7151adf2f1fcce36e8b8ac

**Comment by jimmidyson** [comment]
Yeah it's super simple. There's a PR, kubernetes/kubernetes#31617, which adds it but mixes it up with some default provisioners so I'll put in a separate PR just to handle StorageClass kinds & see how we get on.

**Comment by r2d4** [comment]
SGTM.  Adding support for StorageClass in the addon manager seems like the right solution

**Comment by jimmidyson** [comment]
Opened kubernetes/kubernetes#34639

**Comment by dlorenc** [comment]
I think this works now, can you re-open if we're missing something?

**Comment by dlorenc** [comment]
Reopening. We don't actually have a default provisioner configured.

**Comment by dlorenc** [comment]
I did some digging, we don't have a default provisioner configured. If you use the alpha annotations:

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  annotations:
    volume.alpha.kubernetes.io/storage-class: anything
```

it works, because of a separate codepath here: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/plugins.go#L148

Basically, we don't have a "cloud" set, so it defaults to host_path.

However, the beta annotations *don't work*, because you need to configure a real default storage class:

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: anything
```

fails with:

```
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  4m		4m		1	{persistentvolume-controller }			Warning		ProvisioningFailed	StorageClass "anything" not found
```
