### ISSUE TITLE
Can't connect to nodePort in LoadBalancer

### ISSUE THREAD

**Issue by PierrickI3** [kubernetes/minikube#710]
This is a similar request than https://github.com/kubernetes/minikube/issues/636

**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**Minikube version**: v0.11.0

**Environment**:
- **OS**: OSX Sierra (10.12)
- **VM Driver**: Virtualbox
- **Docker version**: version 1.12.1, build 6f9534c
- **Install tools**: install script on releases page

**What happened**:
I created a LoadBalancer service. I know that getting an external IP is not possible outside of a cloud provider. When trying to curl to the nodePort of the service, it does not respond.

**What you expected to happen**:
`curl $(minikube ip):<nodePort specified in yaml file>` should respond after deploying

**How to reproduce it** (as minimally and precisely as possible):
Create the following service & deployment:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: kong
  name: kong
spec:
  type: LoadBalancer
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      nodePort: 30800
    - name: proxyssl
      port: 8443
      targetPort: 8443
      nodePort: 30843
    - name: adminapi
      port: 8001
      targetPort: 8001
      nodePort: 30801
  selector:
    app: kong

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kong
  name: kong
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong
    spec:
      containers:
        #also need to deploy go-dnsmasq (https://github.com/Mashape/kong/issues/1601)
        - name: go-dnsmasq
          image: janeczku/go-dnsmasq:release-1.0.5
          args:
            - --listen
            - "127.0.0.1:53"
            - --default-resolver
            - --append-search-domains
            - --hostsfile=/etc/hosts
        - name: kong
          image: mashape/kong:cassandra3
          env:
            - name: KONG_DATABASE
              value: cassandra
            - name: KONG_CASSANDRA_CONTACT_POINTS
              value: cassandra-peers
            - name: KONG_PG_USER
              value: kong
            - name: KONG_PG_DATABASE
              value: kong
            - name: KONG_PG_PASSWORD
              value: kong
            - name: KONG_CASSANDRA_KEYSPACE
              value: kong
            - name: KONG_PG_HOST
              value: cassandra-peers.default.svc.cluster.local
            - name: KONG_LOG_LEVEL
              value: info
          ports:
            - name: proxy
              containerPort: 8000
            - name: proxyssl
              containerPort: 8443
            - name: adminapi
              containerPort: 8001
            - name: cluster
              containerPort: 7946
            - name: clusterudp
              containerPort: 7946
              protocol: UDP
```

Once it's deployed, running `curl $(minikube ip):30801` does not respond, nor does `curl $(minikube ip):30801`.

When I run `kubectl get svc`, I get this (note the `kong` service in `pending` state):

```
NAME              CLUSTER-IP   EXTERNAL-IP   PORT(S)                      AGE
cassandra         10.0.0.149   <none>        9042/TCP                     38m
cassandra-peers   None         <none>        7000/TCP,7001/TCP            38m
kafka             10.0.0.36    <none>        9092/TCP                     33m
kong              10.0.0.178   <pending>     8000/TCP,8443/TCP,8001/TCP   2m
kubernetes        10.0.0.1     <none>        443/TCP                      6d
ping              10.0.0.13    <none>        3000/TCP                     33m
zookeeper         10.0.0.32    <none>        2181/TCP,2888/TCP,3888/TCP   33m
```

Output of `kubectl describe svc kong`:

```
Name:           kong
Namespace:      default
Labels:         name=kong
Selector:       app=kong
Type:           LoadBalancer
IP:         10.0.0.178
Port:           proxy   8000/TCP
NodePort:       proxy   30800/TCP
Endpoints:      <none>
Port:           proxyssl    8443/TCP
NodePort:       proxyssl    30843/TCP
Endpoints:      <none>
Port:           adminapi    8001/TCP
NodePort:       adminapi    30801/TCP
Endpoints:      <none>
Session Affinity:   None
No events.
```

**Anything else do we need to know**:

I believe it used to work in minikube 0.10.0. I used to be able to run a local script to create API routes in kong without having to do it from inside the pod.

**Comment by PierrickI3** [comment]
@r2d4 any workaround you might know of?

**Comment by r2d4** [comment]
I think the LoadBalancer support is still working.  I was able to get it to work with a simpler example 

```
apiVersion: v1
kind: Service
metadata:
  name: echoheaders
  labels:
    app: echoheaders
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 30302
    targetPort: 8080
    protocol: TCP
    name: echoheaders-1
  - port: 80
    nodePort: 30303
    targetPort: 8080
    protocol: TCP
    name: echoheaders-2
  selector:
    app: echoheaders
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: echoheaders
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      containers:
      - name: echoheaders-1
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - containerPort: 8080
      - name: echoheaders-2
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - containerPort: 8080
```

You should be able to access the echoheaders containers on either of the node ports.

I wasn't able to get your example working, although I noticed that the pod seems to be unhealthy and keeps restarting because of mashape/kong:cassandra3

```
  1m	14s	6	{kubelet minikube}				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kong" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=kong pod=kong-286286885-a0ens_default(dfd5481b-9afa-11e6-ae6e-d26e01d06a7c)"
```
