### ISSUE TITLE
Service nginx-service was not found in "default" 

### ISSUE THREAD

**Issue by ramesh-kumarjha** [kubernetes/minikube#7106]
service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-nam
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31567 

getting thhis error    Error opening service: Service nginx-service was not found in "default" namespace. You may select another namespace by using 'minikube service nginx-service -n <namespace>: Temporary Error: Error getting service nginx-service: services "nginx-service" not found

**Comment by ramesh-kumarjha** [comment]
error

**Comment by tstromberg** [comment]
Can you share the command-line you used?

This should be`minikube service nginx-service -n my-nam`.

**Comment by ramesh-kumarjha** [comment]
> Can you share the command-line you used?
> 
> This should be`minikube service nginx-service -n my-nam`.

I am using the same command

**Comment by ramesh-kumarjha** [comment]
I am using the same command which you have mentioned

**Comment by priyawadhwa** [comment]
Hey @ramesh-kumarjha I tried to reproduce the error at HEAD by running:

```
kubectl create ns my-nam
kubectl apply -f service.yaml
```

where service.yaml is:

```yaml
apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    namespace: my-nam
spec:
    selector:
        app: nginx
    type: NodePort
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31567
```

and then running:

```
$ minikube service nginx-service -n my-nam
|-----------|---------------|-------------|-----------------------------|
| NAMESPACE |     NAME      | TARGET PORT |             URL             |
|-----------|---------------|-------------|-----------------------------|
| my-nam    | nginx-service |             | http://192.168.64.149:31567 |
|-----------|---------------|-------------|-----------------------------|
🎉  Opening service my-nam/nginx-service in default browser...
```

which worked as expected with the hyperkit driver on mac OS. 

Could you try upgrading to the latest version of minikube and provide:

* What operating system you're running on
* What driver you're using with minikube
* The output of `kubectl get svc -A`
