### ISSUE TITLE
not able to integrate jenkins with minkube

### ISSUE THREAD

**Issue by jatinkushwaha** [kubernetes/minikube#7444]
I using minikube start command to start minikube and expose my Jenkins using command-
minikube service jenkins -n jen

1.i install Kubernetes plugin on Jenkins and add config file as a secret file for the credential.
but when I test the connection it following error-
Error testing connection : java.nio.file.NoSuchFileException: /home/jatin/.minikube/ca.crt
but file present at above location.
2.this is config file 

apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/jatin/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/jatin/.minikube/client.crt
    client-key: /home/jatin/.minikube/client.key
 
Please help me to connect jenkins to my cluster.

**Comment by priyawadhwa** [comment]
Hey @jatinkushwaha I have some clarification questions:

Are you trying to run a jenkins service on minikube, and trying to expose that service? Or are you trying to run minikube in jenkins?

**Comment by jatinkushwaha** [comment]
Hii.. @priyawadhwa  i deploy jenkins on minikube and also expose jenkins using service. 
I also use config file as secret file for credentials. But it give above mention error.

**Comment by tstromberg** [comment]
Please make sure the `/home/jatin/.minikube/ca.crt` file exists.

**Comment by fans3210** [comment]
Hi @tstromberg 

I'm also facing this issue when trying to config kubernetes-cd plugin. My jenkins is running as a NodePort on my local k8s cluster(minikube).
I'm facing below error:
<img width="1290" alt="Screenshot 2020-07-29 11 56 59" src="https://user-images.githubusercontent.com/6023208/88755107-e70c6100-d192-11ea-8be0-896b69f53071.png">

However, my .crt file exists on that path:

<img width="633" alt="Screenshot 2020-07-29 11 54 06" src="https://user-images.githubusercontent.com/6023208/88755141-ff7c7b80-d192-11ea-94be-a2d3d09a8a82.png">


Below if my kubeconfig:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    certificate-authority: /Users/fans3210/.minikube/ca.crt
    server: https://192.168.99.101:8443
  name: minikube
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-for-desktop
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: minikube
  user:
    client-certificate: /Users/fans3210/.minikube/profiles/minikube/client.crt
    client-key: /Users/fans3210/.minikube/profiles/minikube/client.key
```


Another thing that confuses me is that when I'm configuring the plugin, If I set credentials to none, test connection will pass. If I set to use credentials to my kubeconfig file, the above error would be shown.

Appreciated if you could provide me some tips.
