### ISSUE TITLE
looking up node via spec.nodeName `dial tcp: lookup minikube on 10.0.0.10:53: server misbehaving`

### ISSUE THREAD

**Issue by arussellsaw** [kubernetes/minikube#757]
Bug Report:

**minikube version:** (use `minikube version`): v0.12.0

**Environment**:
- **OS** (e.g. from /etc/os-release): OSX 10.11
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): VirtualBox
- **Docker version** (e.g. `docker -v`): Docker version 1.12.2, build bb80604, experimental

**What happened**: nodes trying to resolve `minikube` nodename but i get:

```
2016-10-26T14:10:56.356538450Z E 1026 14:10:56.356377 queue producer.go:318     1 (minikube:4150) error connecting to nsqd - dial tcp: lookup minikube on 10.0.0.10:53: server misbehaving
```

**What you expected to happen**: should resolve to node ip

**How to reproduce it** (as minimally and precisely as possible):

running nsq as DaemonSet: 

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nsq
spec:
  template:
    metadata:
      labels:
        name: nsq
        member: nsq
    spec:
      containers:
        - image: nsqio/nsq:latest
          name: nsq
          args:
            - "nsqd"
          ports:
            - containerPort: 4150
              protocol: TCP
              name: nsqd-tcp
            - containerPort: 4151
              protocol: TCP
              name: nsqd-http
```

running another DaemonSet, a go binary that connects to nsqd:

the container is private, but all it needs to do is try to connect and publish to nsq on the passed NODE_NAME:4150

```
piVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: sidecard
spec:
  template:
    metadata:
      labels:
        name: sidecard
        member: sidecard
    spec:
      imagePullSecrets:
        - name: dockerhubsecret
      containers:
        - image: avocet/sidecard:latest
          name: sidecard
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
```

**Comment by arussellsaw** [comment]
an empty minikube with this daemonSet yaml will reproduce: 

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: test
spec:
  template:
    metadata:
      labels:
        name: test
        member: test
    spec:
      containers:
        - image: arussellsaw/test:latest
          name: test
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
```

arussellsaw/test is simply this go binary: 
```go
package main

import (
        "fmt"
        "net"
        "os"
)

func main() {
        fmt.Println(net.LookupIP(os.Getenv("NODE_NAME")))
}
```
