### ISSUE TITLE
how can I allocate my service (type=NodePort) on nodePort: 80

### ISSUE THREAD

**Issue by dani8art** [kubernetes/minikube#836]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Minikube version** (use `minikube version`):  v0.12.2

**Environment**:
- **OS** : windows
- **VM Driver** : virtualbox
- **Docker version** (e.g. `docker -v`): Docker version 1.11.1, build 5604cbe
- **Install tools**:
- **Others**:

**What happened**:

When I create a service (type=NodePort)  and I want to allocate it to port 80 or 27017, kubectl responds:

`The Service "pets-service" is invalid.
spec.ports[0].nodePort: Invalid value: 80: provided port is not in the valid range`

I've seem the documentation and I think that you can change some parameters on `minikube start` with `--extra-config` and in other issues that I could see say that I must change the `ServiceNodePortRange`. I've tried to execute: 

`minikube start --extra-config=apiserver.GenericServerRunOptions.ServerRunOptions.ServiceNodePortRange=1-30000` 

but this doesn't work. 

I kwon I can set nodePort to other port in the range 30000-31000, but this solution isn't good for me. 

any hint?  

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

#### Run minikube
`minikube start`

#### Create service

`kubectl create -f pets-service.yaml`

**Anything else do we need to know**:

My service file: 
```
apiVersion: v1
kind: Service
metadata:
 name: pets-service
 labels:
   name: pets-service
spec:
 type: NodePort
 ports:
   - port: 80
     targetPort: 80
     nodePort: 80
     protocol: TCP
 selector:
   name: pets-service
```
