### ISSUE TITLE
Cat caching files in mounted hostPath directories with image minikube-iso

### ISSUE THREAD

**Issue by syhol** [kubernetes/minikube#845]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

When in a container shell session, using the `cat` tool on a file inside a mounted hostPath seems to be caching its contents, first run of `cat` will work fine, then subsequent runs produced the same output even if the file has been edited. So far this only seems to effect `cat`. 

**Minikube version**:
v0.12.2

**Environment**:
- **OS**: Ubuntu 14.04.5 LTS
- **VM Driver**: virtualbox
- **Docker version**: Local: 1.12.3, Minikube: 1.11.1
- **Install tools**: kubectl v1.4.6, helm v2.0.0-beta.2
- **Others**: 
  - Minikube Kubernetes Version: v1.4.3
  - MINIKUBE_ISO_URL=http://storage.googleapis.com/minikube/iso/buildroot/minikube-v0.0.6.iso

**What happened**:
the `cat` tool is caching files in the mounted directory

**What you expected to happen**:
The `cat` tool not caching files in the mounted directory 

**How to reproduce it**:

Summary:
- Create pod/container with a mounted hostpath at /src
- `kubectl exec` into a shell session for the container
- Create a file in the mounted /src directory to experiment with
  - Use the linux `cat` command on the file
  - Edit the file 
  - Use the linux `cat` command on the file again, the output should reflect the changes but does not

Reproduction:
kubectl create
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-isolated-app
  labels:
    app: app-isolated-app
    chart: "app-0.0.1"
    release: "app-isolated"
    heritage: "Tiller"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-isolated-app
    spec:
      containers:
      - name: "app-isolated-app-workspace"
        image: "php:7-alpine"
        imagePullPolicy: IfNotPresent
        command: ["sleep", "100000"]
        volumeMounts:
        - name: application
          mountPath: /src
      - name: "app-isolated-app-nginx"
        image: "nginx:latest"
        volumeMounts:
        - name: application
          mountPath: /var/www
      - name: "app-isolated-app-php"
        image: "php:7-fpm"
      volumes:
      - name: application
        hostPath:
          path: /hosthome/my-user/my-project/
```

Dummy terminal session:
```shell
user@host ~/my-project $ POD=$(kubectl get pods --selector=app=app-isolated-app -o jsonpath="{.items..metadata.name}")
user@host ~/my-project $ kubectl exec "$POD" -- /bin/sh
root@container ~/src $ echo "foo" > foofile
root@container ~/src $ cat foofile
foo
root@container ~/src $ # Worked as expected
root@container ~/src $ echo "bar" >> foofile 
root@container ~/src $ cat foofile
foo
root@container ~/src $ # Was expecting 1 line with "foo" and 1 line with "bar"
root@container ~/src $ echo "baz" > foofile 
root@container ~/src $ cat foofile
foo
root@container ~/src $ # Was expecting 1 line with "baz"
```

**Anything else do we need to know**:
- This issue does not happen with other tools like:
  - vi ./filename
  - php -r 'echo file_get_contents("./filename");'
- This issue does not happen outside the mounted directory

**Comment by r2d4** [comment]
I haven't gotten a chance to try to reproduce this with your environment and YAML but here's what I was able to put together for now.
I used 

```
MINIKUBE_ISO_URL=https://storage.googleapis.com/minikube/iso/minikube-v1.0.1.iso
minikube version: v0.12.2
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: gcr.io/google-containers/busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: test
      mountPath: /src
  volumes:
    - name: test
      hostPath:
        path: /hosthome
  restartPolicy: Always
```

```bash
kubectl exec -it busybox sh
```

```
/src # echo "foo" > foofile
/src # cat foofile 
foo
/src # echo "bar" >> foofile 
/src # cat foofile
foo
bar
/src # echo "baz" > foofile 
/src # cat foofile
baz
```

In your examples it looks like you're in `~/src` although the folder is mounted in `/src` and the second line should return `foo bar`. 

I'll give it another try with trying to reproduce it exactly with your manifest.
