### ISSUE TITLE
Add addon for external DNS

### ISSUE THREAD

**Issue by segevfiner** [kubernetes/minikube#8980]
Add an addon for installing external DNS. See https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/coredns.md which uses CoreDNS as the DNS server.

Unlike ingress-dns, which is minikube specific:
1. This is sometimes used in production, so will give similar behavior in development to production.
2. Will support LoadBalancer services.

Some notes about configuring the host that also apply for ingress-dns:
1. For Linux distros using `systemd-resolved`, you can use [`systemd.network` units](https://www.freedesktop.org/software/systemd/man/systemd.network.html) for configuring DNS domain specific DNS servers. Using the `Domains` & `DNS` keys in a new network unit matching the required interface. I used it before, but don't remember the details.
2. For Windows, there is NRPT which should allow setting this.

**Comment by priyawadhwa** [comment]
Hey @segevfiner by default minikube has coredns running:

```
$ kubectl get po -A
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
kube-system   coredns-66bff467f8-6wtb9           1/1     Running   0          34s
```

is this what you're looking for?

**Comment by segevfiner** [comment]
That one is for the cluster internal DNS. Handling DNS foe services and pods inside the cluster.

The external DNS setup referenced is for setting another CoreDNS server for out of cluster DNS emulating what you get with Kubernetes external DNS for real Kubernetes deployments where it configures DNS providers like AWS Route53. Similar to what the ingress-dns addon achieves but with the benefits mentioned in the description.

I hope this clarifies what this is about.

**Comment by priyawadhwa** [comment]
@segevfiner thanks for clarifying! Would you be interested in contributing this addon?

If so, documentation can be found here: https://minikube.sigs.k8s.io/docs/contrib/addons/

**Comment by segevfiner** [comment]
Looking into this further, there are some things to iron out first:

First, the setup in the tutorial there is not the cleanest, I tried to make a simpler one here using just helm to get started:
```sh
helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm repo add bitnami https://charts.bitnami.com/bitnami
helm upgrade -i etcd-operator stable/etcd-operator --set customResources.createEtcdClusterCRD=true
helm upgrade -i coredns stable/coredns -f coredns-values.yaml
helm upgrade -i external-dns bitnami/external-dns --set provider=coredns --set coredns.etcdEndpoints=http://etcd-cluster-client:2379
```

<details><summary><code>coredns-values.yaml</code></summary>

```
isClusterService: false

serviceType: NodePort

servers:
- zones:
  - zone: .
  port: 53
  plugins:
  - name: errors
  # Serves a /health endpoint on :8080, required for livenessProbe
  - name: health
    configBlock: |-
      lameduck 5s
  # Serves a /ready endpoint on :8181, required for readinessProbe
  - name: ready
  # Required to query kubernetes API for data
  - name: kubernetes
    parameters: cluster.local in-addr.arpa ip6.arpa
    configBlock: |-
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
      ttl 30
  # Serves a /metrics endpoint on :9153, required for serviceMonitor
  - name: prometheus
    parameters: 0.0.0.0:9153
  - name: forward
    parameters: . /etc/resolv.conf
  - name: cache
    parameters: 30
  - name: loop
  - name: reload
  - name: loadbalance
  - name: etcd
    parameters: test
    configBlock: |-
      stubzones
      path /skydns
      endpoint http://etcd-cluster-client:2379
```

</summary>
(Yes, had to copy that entire large block from the `values.yaml` cause it's an array 🤷‍♂️ )

And after it is all up and running, I can create some `LoadBalancer` service and annotate it:
```sh
kubectl create deployment nginx --image nginx
kubectl expose deployment nginx --port 80 --type LoadBalancer
kubectl annotate service nginx "external-dns.alpha.kubernetes.io/hostname=nginx.test"
```

Start `minikube tunnel` so the `LoadBalancer` service gets an IP and is accessible.

Get the CoreDNS IP & port:
```sh
  export COREDNS_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[0].nodePort}" services coredns-coredns)
  export COREDNS_IP=$(kubectl get nodes --namespace default -o jsonpath="{.items[0].status.addresses[0].address}")
```

And query it:
```sh
dig @$COREDNS_IP -p $COREDNS_PORT nginx.test
```

Problems:
1. This is a complex helm deployment that needs to somehow be untangled and simplified to fit in a minikube addon.
2. It uses the archived/unmaintained etcd-operator to setup the etcd cluster. Now only is it unarchived/unmaintained, but it might be too big of a thing to install in an addon just for this.
3. CoreDNS is exposed using a NodePort which doesn't use the standard DNS port, meaning it can't be configured in most hosts. Can't use LoadBalancer either because it uses both UDP and TCP. Maybe there is a workaround to get LoadBalancer to work, or maybe we should make it available under the right port using a different means, e.g. `hostNetwork` like `ingress-dns` uses or `hostPort`, or some other proxy shenanigans.
4. We might want to make the domain configurable, shouldn't really be a problem.

Host configuration afterwards will be similar to `ingress-dns` where the instructions can probably be expanded with information for more operating systems or possibly automated at some point (Being careful not to destroy the host...)
