### ISSUE TITLE
hostpath volume not mounting, data kept in /var/lib/docker/overlay2/

### ISSUE THREAD

**Issue by tempacct4q** [kubernetes/minikube#9013]
Hey been trying each available examples online to get a hostpath persistent volume to mount into pod, but each one ends up creating a volume in /var/lib/docker/overlay2.  I've attempted on multiple workstations, one using ubuntu, one using centos, one using redhat. all same results.  Also tried changing /rewriting for pod, and statefulset.

so, lets just work this one version:

minikube version: v1.12.3

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Docker version 19.03.6, build 369ce74a3c
ubuntu:19.10

heres a snippet of latest pv, pvc, and deployment.
**PV:**
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: asset-tracker-mysql-volume0
  labels:
    type: local
    pvname: asset-tracker-mysql-volume0
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/asset-tracker-mysql-volume0"
```
**PVC:**
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: asset-tracker-mysql-claim0
  name: asset-tracker-mysql-claim0
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      pvname: asset-tracker-mysql-volume0
status: {}
```
**snippet from deployment:**
```yaml
        volumeMounts:
        - mountPath: /dtmp
          name: mysqldata
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mysqldata
        hostPath:
          path: /mnt/data/asset-tracker-mysql-volume0
          type: Directory
```
the /dtmp is just a tmp directory to make sure the issue wasn't over an existing directory at this time.

Also tried the claim syntax in deployment
```yaml
volumes:
      - name: asset-tracker-mysql-volume0
        persistentVolumeClaim:
          claimName: asset-tracker-mysql-claim0
```

can add what I did for pod/statefulsets but would rather stay w/ deployment

**Comment by poliander** [comment]
Make sure the Kubelet can access the paths to be mounted when the Kubelet runs in a container, e.g. add a HostConfig bind:

`
$ docker inspect kubelet

[...]

    "HostConfig": {
        "Binds": [
            "/mnt/data:/mnt/data"

[...]
`

**Comment by priyawadhwa** [comment]
Hey @tempacct4q did adding the `HostConfig` bind resolve your issue?

**Comment by tempacct4q** [comment]
Hey @priyawadhwa lemme test that and I'll you know

**Comment by tstromberg** [comment]
I too am confused about the suggestion given by @poliander

**Comment by msedzins** [comment]
Hi, @tempacct4q 

If I understand correctly:
A hostPath volume mounts a file or directory from the host node's filesystem into your Pod. In case of a minikube, the "host node" is actually a docker container. 

So looks like you try to mount the directory from your local machine (/mnt/data/asset-tracker-mysql-volume0) which is not available to minikube docker container that runs on top.

You should bind a local directory on your machine to docker container so that it can be seen by Kubelet process which runs inside. 
When you run on your machine:
docker inspect minikube

There will be section "HostConfig" which lists binds. Your directory should be on that list. Can you see it there?

**Comment by medyagh** [comment]
@tempacct4q @msedzins  I see this issue is using a very very old minikube version (v1.12.3), I remember we fixed something about the mount partitions in the ISO, I wonder if we still have this issue ? do u mind giving it another try to see if it works now with latest version (v1.18.1)

**Comment by spowelljr** [comment]
Hi @tempacct4q, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by engnatha** [comment]
I know this is an old issue, but I believe I'm running into a similar thing. Happy to open a new one if that's preferable! My details are
* Ubuntu 20.04 (`5.15.0-86-generic` kernel)
* minikube v1.26.0
* docker driver version `24.0.6` in rootless mode
* containerd runtime version `1.6.24`
* k8s `v1.23.0`
* allocated 8 cpu, 6 GB ram

I set up a simple persistent volume like
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
  labels:
    name: nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: manual
  hostPath:
    path: /minikube-data
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
  labels:
    name: nfs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  selector:
    matchLabels:
      name: nfs
  resources:
    requests:
      storage: 50Gi
```
Can ignore the "nfs" verbage. It's to mimic our real setup that has an nfs system. I start minikube with `minikube start --kubernetes-version=v1.23.0 --mount-string /minikube-data:/minikube-data --mount`. The mount looks great when I `minikube ssh` in. When I attach this as a volume to a pod, I'm seeing my destination reported by `crictl inspect` point to a `/var/lib/kubelet` directory. The standard hostpath provisioning mounts show up correctly to go under `/tmp/hostpath-provisioner` (very cool feature btw!). I'm surprised my custom hostPath is redirected.

For what it's worth, it _does_ seem like this `/var/lib/kubelet` mount is still directed properly back to `/minikube-data`. When files get created at container startup time, I do see them inside `minikube ssh` and on the host machine directly.
