### ISSUE TITLE
forked Ingress addon works in scenario where upstream addon doesn't

### ISSUE THREAD

**Issue by donaldguy** [kubernetes/minikube#921]
First off, thanks for your help so far! In general, getting k8s running my workload has gone smoother and easier than I expected and has been pretty fun. I mostly wanted to post this to help out anyone else who has any confusion in the meantime.

This is maybe the wrong place for this bug. But as a k8s beginner it gave me the most frustration so far, and since minikube is likely the entrypoint for beginners going forward, this seems like a reasonable place to file it. Feel free to indicate where (else) I should file, if anywhere. With the transition between https://github.com/kubernetes/ingress and 
https://github.com/kubernetes/contrib/tree/master/ingress/controllers (and  https://github.com/nginxinc/kubernetes-ingress still hanging around and of ambiguous affiliation), I ended up a bit confused about ecosystem as well as behavior here.

I'm gonna also (try to, if I can find the right place) file a docs bug suggesting better clarification of "single-service" ingress in the docs, as I think that contributed to my confusion.

**Minikube version**: minikube version: v0.13.1 (probably slightly newer, same build I was using in #909 )

**What happened**:
After getting ingress-controller working in minikube, I looked at examples in the docs, and maybe confused between http://kubernetes.io/docs/user-guide/ingress/#name-based-virtual-hosting and http://kubernetes.io/docs/user-guide/ingress/#single-service-ingress, and/or very possibly being bad at indenting yaml properly, I wrote a (inadvertently?) valid Ingress object as (using helm version both as a redact and cause its true):

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
spec:
  rules:
  - host: {{ template "hostname" . }}
  backend:
    serviceName: {{ template "fullname" . }}
    servicePort: 8080
```

It worked! and I thought I was done writing that for now (other than revisiting to add tls) 

Then when I tried to deploy it to a cluster in AWS (using the ingress config from https://github.com/kubernetes/kops/blob/1020214f879ef7f9d1528f89860497f40a685e43/addons/ingress-nginx/v1.4.0.yaml ) it did not

In particular looking at the resulting nginx config (by `kubectl --namespace kube-system exec`ing into the pod), my original yaml resulted in a server block with the appropriate `server_name` but still doing `proxy_pass http://upstream-default-backend;` It seemed an awful lot like my ingress was right, but that the selector wasn't matching the service properly... 

I spent a couple hours debugging it badly, thinking it was something about either the new complexities of multi-node/VPC routing or the limitations of minikube services. Finally I decided to debug by rewrite and went back to http://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1beta1_ingress and discovered my error

**What you expected to happen**:

It turns out this shouldn't work by the spec as I read it / the behavior of my AWS cluster. What I needed was more like
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
spec:
  rules:
    - host: {{ template "hostname" . }}
      http:
         paths:
           - backend:
                serviceName: {{ template "fullname" . }}
                servicePort: 8080
```

I know you are currently running a slight fork of ingress (`gcr.io/k8s-minikube/nginx-ingress-controller:0.8.4` vs `gcr.io/google_containers/nginx-ingress-controller:0.8.3`) and I see the version numbers differ as well, so this may be an essentially solved issue (though as above with 2-3 repos running around its currently unclear where to look for changes that might have solved my problem). But it may also be an accidental emergent behavior, so I wanted to make you aware.
