### ISSUE TITLE
Cannot successfully use hostPath on Windows

### ISSUE THREAD

**Issue by Azim-Palmer** [kubernetes/minikube#9282]
**Steps to reproduce the issue:** 

1. Start minikube with ```minikube start --mount --mount-string="C:\Users\{yourusernamehere}"```
2. kubectl apply the following:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    io.kompose.service: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      io.kompose.service: grafana
  template:
    metadata:
      labels:
        app: grafana
        io.kompose.service: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        volumeMounts:
            - mountPath: /var/lib/grafana
              name : grafana-main
      volumes:
          - name: grafana-main
            hostPath:
              path: /grafanaData
              type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
   - port: 30
     targetPort: 3000
  selector:
    app: grafana
```
2. The pod will fail to start with
```mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
GF_PATHS_DATA='/var/lib/grafana' is not writable.
```

I have tried :

```
securityContext:
    windowsOptions:
      runAsUserName: "MyUserName"
```

which changes nothing.

Please help this is driving me insane.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
```
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
```

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
This feels like a real bug in windows.

**Comment by spowelljr** [comment]
Hi @Azim-Palmer, sorry for the overdue response, I just took a look at this and believe I found the cause of your issue. You're trying to create a folder in `/var/lib/` which is owned by root and it's trying to be created with a non-root user.

You were close with the `securityContext`, you just need to add:
```
securityContext:
  runAsUser: 0
```
So it looks like:
```
spec:
  selector:
    matchLabels:
      app: grafana
      io.kompose.service: grafana
  template:
    metadata:
      labels:
        app: grafana
        io.kompose.service: grafana
    spec:
      securityContext:
        runAsUser: 0
```
That will run the command as root and can create the folder you're trying to create.
```
NAME                      READY   STATUS    RESTARTS   AGE
grafana-f7c9f9d56-fddvd   1/1     Running   0          29s
```

Since this issue has been open for over a year I'm going to close it, but if you're still following it feel free to respond and can re-open the issue if you're still having issues.
