### ISSUE TITLE
Multi-Node is not producing exact replica nodes (getting file write permission errors on extra node)

### ISSUE THREAD

**Issue by harryttd** [kubernetes/minikube#9305]
**Steps to reproduce the issue:** 

1. `minikube start --nodes 2`
2. `kubectl apply -f /path/to/yaml` (yaml pasted below)
3. Confirm pods are on separate nodes: `k get pods -n myapp -o jsonpath='{.items[*].spec.nodeName}'`
4. Check logs of pod on node `minkube`. Should say `Created dir /var/foo/bar`.
5. Check logs of pod on node `minikube-m02`. Should say `mkdir: can't create directory '/var/foo/bar': Permission denied`.

**Full output of `minikube start` command used, if not already included:**
```
❯ minikube start --nodes 2
😄  minikube v1.13.1 on Darwin 10.15.6
✨  Automatically selected the hyperkit driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.19.2 on Docker 19.03.12 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner

❗  Multi-node clusters are currently experimental and might exhibit unintended behavior.
📘  To track progress on multi-node clusters, see https://github.com/kubernetes/minikube/issues/7538.

👍  Starting node minikube-m02 in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🌐  Found network options:
    ▪ NO_PROXY=192.168.64.31
🐳  Preparing Kubernetes v1.19.2 on Docker 19.03.12 ...
    ▪ env NO_PROXY=192.168.64.31
🔎  Verifying Kubernetes components...
🏄  Done! kubectl is now configured to use "minikube" by default
```

### yaml for reproducing issue:

My use case's image sets the uid of the container to 100 so mimicking here for reproduction. Running the container as root does not result in any issues.
```
apiVersion: v1
kind: Namespace
metadata:
  name: myapp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pvc
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      storage-type: var-files
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: busybox
          command:
            - /bin/sh
          args:
            - -c
            - |
              mkdir -p /var/foo/bar && echo Created dir /var/foo/bar
              # Keep container running
              until false; do sleep 2; done;
          securityContext:
            # My use case's image sets the uid to 100
            runAsUser: 100
          volumeMounts:
            - mountPath: /var/foo
              name: var-volume
      volumes:
        - name: var-volume
          persistentVolumeClaim:
            claimName: myapp-pvc
```
