### ISSUE TITLE
Ingress nginx for TCP and UDP services --- Step "Patch the ingress-nginx-controller" bug

### ISSUE THREAD

**Issue by harryttd** [kubernetes/minikube#9354]
```
❯ minikube version
minikube version: v1.13.1
commit: 1fd1f67f338cbab4b3e5a6e4c71c551f522ca138
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
https://minikube.sigs.k8s.io/docs/tutorials/nginx_tcp_udp_ingress/#patch-the-ingress-nginx-controller

Running the directed command: `kubectl patch deployment ingress-nginx-controller --patch "$(cat ingress-nginx-controller-patch.yaml)" -n kube-system` results in an error `The Deployment "ingress-nginx-controller" is invalid: spec.template.spec.containers[0].image: Required value`.

EDIT:
I think the real problem is that the container name mentioned in the docs is `ingress-nginx-controller`. The deployment `ingress-nginx-controller` has container `controller`. That container is what should be patched.

From the docs:
```
spec:
  template:
    spec:
      containers:
      - name: ingress-nginx-controller
        ports:
         - containerPort: 6379
           hostPort: 6379
```
