### ISSUE TITLE
Pod not accessible on NodePort via the Windows 10 host machine.

### ISSUE THREAD

**Issue by willemodendaal** [kubernetes/minikube#9499]
I'm struggling with Minikube on Windows 10. I have a pod and a service, but the nodePort on the service does not seem to work. When accessing my service using curl I get: `curl: (7) Failed to connect to 192.168.49.2 port 31985: Timed out
This site can’t be reached`

I honestly don't know if this is a Minikube issue, or a Kubernetes issue, or a Skaffold issue, or a plain windows networking issue. Hoping someone can point me in the right direction, and hopefully help folks with a similar issue in future.

**Steps to reproduce the issue:** 

1. Run `minikube start`  (no extra parameters)
2. Use skaffold to run `kubectl apply` to release pod and service (see yaml below)
3. Try to access pod with curl from within the cluster, it works fine.
4. On the host machine, run `minikube service list` to get url to the pod.
4. Try to access the pod using curl from the host machine (Windows10), but I get timeouts.

**Kubebernetes yaml being applied**

I `kubectl apply` the following to the minikube cluster:
```
apiVersion: v1
kind: Service
metadata:
  name: doxie-budget-api-svc-local
  labels:
    app: doxie-budget-api-svc
    environment: local
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 31985
    protocol: TCP
  selector:
    app: doxie-budget-api
    environment: local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doxie-budget-api-deployment-local
  labels:
    environment: local
    app: doxie-budget-api
spec:
  replicas: 1
  selector:
    matchLabels:
        environment: local
        app: doxie-budget-api
  template:
    metadata:
      labels:
        environment: local
        app: doxie-budget-api
    spec:
      containers:
      - name: doxie-budget-api
        image: doxie-budget-api
        ports:
        - containerPort: 80
```

Kubectl is definitely pointing to minikube:
![image](https://user-images.githubusercontent.com/915354/96598800-8a32c980-12ef-11eb-84fc-7b8e00468a85.png)

The service is running and points to the pod, see endpoint:
![image](https://user-images.githubusercontent.com/915354/96599018-c36b3980-12ef-11eb-9e26-e89fd33b8a31.png)

I can connect to the pod from within the cluster, no problem:

![image](https://user-images.githubusercontent.com/915354/96599251-04fbe480-12f0-11eb-9a87-66de4375cb58.png)

I can also connect to the pod via the service within the cluster (using the service port):

![image](https://user-images.githubusercontent.com/915354/96599816-9a977400-12f0-11eb-8459-fcae87db76e0.png)

Minikube shows that the service can be accessed at  http://192.168.49.2:31985

![image](https://user-images.githubusercontent.com/915354/96599404-2e1c7500-12f0-11eb-9a87-2e92196f0074.png)

But no luck when I access that url from the _host machine_ using curl or the browser:

![image](https://user-images.githubusercontent.com/915354/96600338-227d7e00-12f1-11eb-81e4-5f7139c9ed03.png)

I tried accessing the same port on the minikube ip for good measure, but no luck either:

![image](https://user-images.githubusercontent.com/915354/96600437-388b3e80-12f1-11eb-8e28-0810afdbb6c7.png)

I added windows defender firewall rules (both incoming and outgoing) to allow traffic on that port. Not sure what else I can do... can anyone help?

**Version information**

Minikube:
```
minikube version: v1.14.0
commit: b09ee50ec047410326a85435f4d99026f9c4f5c4
```

Kubectl:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

Windows:
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
```
