### ISSUE TITLE
使用minikube搭建本地集群时，负载均衡没有体现

### ISSUE THREAD

**Issue by LargeOrange** [kubernetes/minikube#9602]
**重现问题所需的命令**：
首先用： 
```
minikube start --cpus=2 --memory=2048mb --registry-mirror=https://t65rjofu.mirror.aliyuncs.com --driver=virtualbox --nodes=3 
```
创建3个minikube节点
```
dacheng.sun@MacBook-Pro  ~/k8s/k8s-msa-in-action/ch05/07   master ●  kubectl get no
NAME           STATUS   ROLES    AGE   VERSION
minikube       Ready    master   87m   v1.19.0
minikube-m02   Ready    <none>   86m   v1.19.0
minikube-m03   Ready    <none>   86m   v1.19.0
```

我的pod yaml文件
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo
spec:
  selector:
    matchLabels:
      app: docker-demo
  minReadySeconds: 10
  replicas: 3
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
        - name: docker-demo
          image: sundacheng/docker_demo:v1.0.1
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

```
我的svc文件
```
apiVersion: v1
kind: Service
metadata:
  name: docker-demo
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 31080
#  - protocol: "TCP"
#    port: 3000
#    targetPort: 3000
#  type: LoadBalancer
  selector:
    app: docker-demo
  type: NodePort
```
执行部署后
```
dacheng.sun@MacBook-Pro  ~/k8s/k8s-msa-in-action/ch05/07   master ●  kubectl get all
NAME                               READY   STATUS    RESTARTS   AGE
pod/docker-demo-6745fbc685-k9j55   1/1     Running   0          13m
pod/docker-demo-6745fbc685-t2ds6   1/1     Running   0          13m
pod/docker-demo-6745fbc685-x8csx   1/1     Running   0          10m

NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/docker-demo   NodePort    10.110.58.152   <none>        3000:31080/TCP   13m
service/kubernetes    ClusterIP   10.96.0.1       <none>        443/TCP          91m

NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/docker-demo   3/3     3            3           13m

NAME                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/docker-demo-6745fbc685   3         3         3       13m
dacheng.sun@MacBook-Pro  ~/k8s/k8s-msa-in-action/ch05/07   master ●  minikube service docker-demo --url
http://192.168.99.111:31080
```

我的镜像有个env接口，调用后会输出对应pod的podname
但是我curl调用接口输出
```
dacheng.sun@MacBook-Pro  ~/k8s/k8s-msa-in-action/ch05/07   master ●  curl http://192.168.99.111:31080/env
docker-demo-6745fbc685-x8csx%                                                                     
dacheng.sun@MacBook-Pro  ~/k8s/k8s-msa-in-action/ch05/07   master ●  curl http://192.168.99.111:31080/env
docker-demo-6745fbc685-x8csx%                                                                     
dacheng.sun@MacBook-Pro  ~/k8s/k8s-msa-in-action/ch05/07   master ●  curl http://192.168.99.111:31080/env
docker-demo-6745fbc685-x8csx%                                                                     
dacheng.sun@MacBook-Pro  ~/k8s/k8s-msa-in-action/ch05/07   master ●  curl http://192.168.99.111:31080/env
```
从现象上看只有master节点上的pod接受了请求

```
kubectl get pod -o wide
NAME                           READY   STATUS    RESTARTS   AGE   IP           NODE           NOMINATED NODE   READINESS GATES
docker-demo-6745fbc685-k9j55   1/1     Running   0          18m   172.17.0.2   minikube-m03   <none>           <none>
docker-demo-6745fbc685-t2ds6   1/1     Running   0          18m   172.17.0.2   minikube-m02   <none>           <none>
docker-demo-6745fbc685-x8csx   1/1     Running   0          14m   172.17.0.3   minikube       <none>           <none>
```

请问这是什么原因，我应该怎么做去实践负载均衡

**使用的操作系统版本**：
Mac os 10.15.5
Minikube v1.13.0
