### ISSUE TITLE
ClusterIP service not available as hostname to other pods ? (Works in google cloud)

### ISSUE THREAD

**Issue by matanshukry** [kubernetes/minikube#9968]
**Steps to reproduce the issue:** 

1. minikube start
2. kubectl apply -f mariadb.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  type: ClusterIP
  ports:
    - port: 3306
      name: mariadb
  selector:
    app: mariadb
    tier: db
  clusterIP: None
---
<mariadb deployment/statefulset here>
```
I was a bit lazy to paste my mariadb config because it also includes password, but it's fairly simple.
If it's required let me know and I'll reduct it and paste it as well

3. kubectl run curl --image=radial/busyboxplus:curl -i --tty
3.1 nslookup mariadb

Expected: IP of the service of MaraDb
Actual: `nslookup: can't resolve 'mariadb'`

**Comment by blueelvis** [comment]
Hi!

I just tried with some minor edits to the above YAML file (Removed `clusterIP: None`) and then this worked as expected on my minikube -
```
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  type: ClusterIP
  ports:
    - port: 3306
      name: mariadb
  selector:
    app: mariadb
    tier: db
```

Here is the output I got after running - `kubectl run curl --image=radial/busyboxplus:curl -i --tty -- nslookup mariadb`
![image](https://user-images.githubusercontent.com/6985763/102351250-2285bb80-3fcc-11eb-9eef-2cfc788777f7.png)

Can you try and see if this gets resolved?
